act_code: '163538'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 30 декабря 2021 года № 14/114
title:
  rus: О бюджете села Тенге на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Теңге ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '163003000002'
version_date:
  kaz: 2021-12-30
  rus: 2021-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163538/kaz/30.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163538/rus/30.12.2021
