act_code: '89442'
requisite: Решение маслихата Мунайлинского района от 20 марта 2015 года № 30/316. Зарегистрировано Департаментом юстиции Мангистауской области от 30 апреля 2015 года № 2702
title:
  rus: О схем зонирования и поправочных коэффициентах к базовой ставке земельного налога для целей налогообложения села Баянды
  kaz: Баянды ауылын салық салу мақсатында аймақтарға бөлу схемасы және жер салығының базалық мөлшерлемелеріне түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-20
approved_by:
- '163008000002'
version_date:
  kaz: 2018-04-27
  rus: 2018-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/89442/kaz/27.04.2018
  rus: https://zan.gov.kz/client/#!/doc/89442/rus/27.04.2018
caused_by:
  code: '121886'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 27 апреля 2018 года № 22/274. Зарегистрировано Департаментом юстиции Мангистауской области 18 мая 2018 года № 3607
  title:
    rus: О внесении изменений в некоторые решения Мунайлинского районного маслихата
    kaz: Мұнайлы аудандық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121886/rus
