act_code: '219793'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 26 декабря 2025 года № 37/178
title:
  rus: О бюджетах города районного значения, сел, сельского округа на 2026 – 2028 годы
  kaz: 2026 - 2028 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '163006000002'
version_date:
  kaz: 2026-05-21
  rus: 2026-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/219793/kaz/21.05.2026
  rus: https://zan.gov.kz/client/#!/doc/219793/rus/21.05.2026
caused_by:
  code: '225843'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 21 мая 2026 года № 42/202
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 26 декабря 2025 года № 37/178 «О бюджетах города районного значения, сел, сельского округа на 2026 – 2028 годы»
    kaz: «2026 - 2028 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеттері туралы» Түпқараған аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 37/178 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225843/rus
