act_code: '176749'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 29 декабря 2022 года № 18/193
title:
  rus: О бюджетах сел, сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '163004000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/176749/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176749/rus/15.12.2023
caused_by:
  code: '190149'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 15 декабря 2023 года № 7/62
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 29 декабря 2022 года № 18/193 «О бюджетах сел, сельских округов на 2023 - 2025 годы»
    kaz: Маңғыстау аудандық мәслихатының 2022 жылғы 29 желтоқсанындағы № 18/193 «2023 - 2025 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190149/rus
