act_code: '59046'
requisite: Решение акима Каракиянского раойна от 25 апреля 2011 года № 39. Зарегистрировано Департаментом юстиции Мангистауской области 26 мая 2011 года № 11-4-117. Утратило силу решением акима Каракиянского района Мангистауской области от 7 октября 2011 года № 92
title:
  rus: Об образовании избирательных участков по Каракиянскому району
  kaz: Қарақия ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-25
approved_by:
- '163005000003'
version_date:
  kaz: 2011-04-25
  rus: 2011-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/59046/kaz/25.04.2011
  rus: https://zan.gov.kz/client/#!/doc/59046/rus/25.04.2011
