act_code: '183837'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 4 июля 2023 года № 5/34
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Каракиянскому району на 2023 - 2024 годы
  kaz: Қарақия ауданы бойынша 2023 - 2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-04
approved_by:
- '163005000002'
version_date:
  kaz: 2024-10-11
  rus: 2024-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/183837/kaz/11.10.2024
  rus: https://zan.gov.kz/client/#!/doc/183837/rus/11.10.2024
caused_by:
  code: '201880'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 11 октября 2024 года № 19/158
  title:
    rus: О внесении изменений и дополнений в решение Каракиянского районного маслихата от 4 июля 2023 года № 5/34 «Об утверждении Плана по управлению пастбищами и их использованию по Каракиянскому району на 2023 - 2024 годы»
    kaz: Қарақия аудандық мәслихатының 2023 жылғы 4 шілдедегі № 5/34 «Қарақия ауданы бойынша 2023 - 2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» шешіміне өзгерістер мен толықтырлар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201880/rus
