act_code: '7638'
requisite: Решение акима Мангистауской области от 25 августа 2000 года № 489. Зарегистрировано Управлением юстиции Мангистауской области 6 сентября 2000 года № 264. Утратило силу письмом Мангистауского областного акимата от 16 июля 2012 года № 01-30-1050
title:
  rus: О мерах по профилактике заноса заболевания сибирской язвы на территорию области
  kaz: Қарасан ауруының облыс аумағына әкелуiнiң алдын алу жөнiндегi шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-08-24
approved_by:
- '163000000003'
version_date:
  kaz: 2000-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/7638/kaz/24.08.2000
