act_code: '162810'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 10 декабря 2021 года № 9/56. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2021 года № 25893
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организации здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в селах и сельских округах Тупкараганского района
  kaz: Түпқараған ауданының ауылдары мен ауылдық округтерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасы мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '163006000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/162810/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162810/rus/10.12.2021
