act_code: '92273'
requisite: Решение Мангистауского областного маслихата от 23 июня 2015 года № 26/405. Зарегистрировано Департаментом юстиции Мангистауской области от 29 июля 2015 года № 2789. Утратило силу решением Мангистауского областного маслихата от 28 мая 2021 года № 3/52
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в населенных пунктах Мунайлинского района
  kaz: Мұнайлы ауданының елді мекендерінде иттер мен мысықтарды асырау және серуендету,қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-23
approved_by:
- '163000000002'
version_date:
  kaz: 2015-06-23
  rus: 2015-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/92273/kaz/23.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92273/rus/23.06.2015
