act_code: '122683'
requisite: Решение Мангистауского областного маслихата от 30 мая 2018 года № 19/230. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2018 года № 3655. Утратило силу решением маслихата Мангистауской области от 29 мая 2020 года № 36/437
title:
  rus: О границах охранных зон, зон регулирования застройки и зон охраняемого природного ландшафта объектов историко-культурного наследия
  kaz: Тарихи-мәдени мұра объектілерін қорғау аймақтарының, құрылыс салуды реттеу аймақтары мен қорғалатын табиғат ландшафты аймақтарының шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-30
approved_by:
- '163000000002'
version_date:
  kaz: 2018-05-30
  rus: 2018-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/122683/kaz/30.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122683/rus/30.05.2018
