act_code: '128898'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 22 января 2019 года № 23/268. Зарегистрировано Департаментом юстиции Мангистауской области 29 января 2019 года № 3807
title:
  rus: О бюджете сельского округа Шайыр на 2019-2021 годы
  kaz: 2019 - 2021 жылдарға арналған Шайыр ауылдық округінің бюджеті туралы­­
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-22
approved_by:
- '163004000002'
version_date:
  kaz: 2019-06-28
  rus: 2019-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128898/kaz/28.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128898/rus/28.06.2019
caused_by:
  code: '132931'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 28 июня 2019 года № 28/328. Зарегистрировано Департаментом юстиции Мангистауской области 28 июня 2019 года № 3939
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 22 января 2019 года № 23/268 «О бюджете сельского округа Шайыр бюджет на 2019-2021 годы»
    kaz: Маңғыстау аудандық мәслихатының 2019 жылғы 22 қаңтардағы № 23/268 «2019-2021 жылдарға арналған Шайыр ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132931/rus
