act_code: '213191'
requisite: Решение Мангистауского областного маслихата от 4 августа 2025 года № 21/254
title:
  rus: Об определении перечня социально значимых сообщений, подлежащих субсидированию по Мангистаускому району
  kaz: Маңғыстау ауданы бойынша субсидиялауға жататын әлеуметтік маңызы бар қатынастарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-04
approved_by:
- '163000000002'
version_date:
  kaz: 2025-08-04
  rus: 2025-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/213191/kaz/04.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213191/rus/04.08.2025
