act_code: '206045'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 30 декабря 2024 года № 24/197
title:
  rus: О бюджета села Тенге на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Теңге ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '163003000002'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/206045/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/206045/rus/26.11.2025
caused_by:
  code: '218159'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 26 ноября 2025 года № 33/294
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 30 декабря 2024 года № 24/197 «О бюджете села Тенге на 2025 - 2027 годы»
    kaz: «2025 - 2027 жылдарға арналған Теңге ауылының бюджеті туралы» Жаңаөзен қалалық мәслихатының 2024 жылғы 30 желтоқсандағы № 24/197 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218159/rus
