act_code: '6358'
requisite: Решение акима  Мангистауской области от 30 марта 2000 года № 370. Зарегистрировано Управлением юстиции Мангистауской области 3 мая 2000 года № 215. Утратило силу решением акима  Мангистауской области от 4 апреля 2000 года № 376
title:
  rus: О мерах по организации погашения кредиторской задолженности
  kaz: Кредиторлық берешекті өтеуді ұйымдастыру жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-29
approved_by:
- '163000000003'
version_date:
  kaz: 2000-03-29
  rus: 2000-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/6358/kaz/29.03.2000
  rus: https://zan.gov.kz/client/#!/doc/6358/rus/29.03.2000
