act_code: '35836'
requisite: Маңғыстау облысы Мұнайлы аудандық мәслихатының 2007 жылғы 11 қазандағы № 2/24 шешімі. Маңғыстау облысы Әділет департаментінде 2007 жылғы 20 қарашада № 1987 болып тіркелді
title:
  rus: Аз қамтылған және аса мұқтаж азаматтарға бір жолғы материалдық көмек көрсету туралы
  kaz: Аз қамтылған және аса мұқтаж азаматтарға бір жолғы материалдық көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-11
approved_by:
- '163008000002'
version_date:
  kaz: 2007-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/35836/kaz/11.10.2007
