act_code: '105145'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 июня 2016 года № 3/26. Зарегистрировано Департаментом юстиции Мангистауской области от 3 августа 2016 года № 3105. Утратило силу решением маслихата  Бейнеуского района Мангистауской области от 16 марта 2018 года № 21/173
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салық мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-23
approved_by:
- '163007000002'
version_date:
  kaz: 2016-06-23
  rus: 2016-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/105145/kaz/23.06.2016
  rus: https://zan.gov.kz/client/#!/doc/105145/rus/23.06.2016
