act_code: '21332'
requisite: Решение акима  Мангистауской области от 14 сентября 2004 года № 54. Зарегистрировано Департаментом юстиции Мангистауской области 20 сентября 2004 года № 1754
title:
  rus: Об утверждении Порядка включения в (электротехнического происхождения), черного (рельсов, элементов железнодорожного полотна и подвижного состава, бывших в употреблении) лома
  kaz: Түсті (электротехникалық текті), қара (рельстер, темір ол төсеніштері мен жылжымалы құрамның қолданыстан шыққан элементтері) металдардың сынықтарын тапсыруды жүзеге асыратын мамандандырылған қызмет ұйымдары Тізбесіне енгізу Тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-09-13
approved_by:
- '163000000003'
version_date:
  kaz: 2004-09-13
  rus: 2004-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/21332/kaz/13.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21332/rus/13.09.2004
