act_code: '23863'
requisite: Маңғыстау облысы Ақтау қалалық мәслихатының 2005 жылғы 24 наурыздағы № 14/118 шешімі. Маңғыстау облыстық Әділет Департаментінде 2005 жылғы 13 сәуірде № 1897 тіркелді
title:
  rus: Әділет Департаментінде 2005 жылғы 4 ақпанда № 1849 тіркелген, "Бiр жолғы материалдық көмек пен ай сайынғы үстеме ақы тағайындау мен көрсету Ережесiн бекiту туралы" қалалық мәслихатының 2004 жылғы 23 желтоқсандағы № 12/92 шешіміне өзгерістер мен толықтфрулар енгізу туралы
  kaz: Әділет Департаментінде 2005 жылғы 4 ақпанда № 1849 тіркелген, "Бiр жолғы материалдық көмек пен ай сайынғы үстеме ақы тағайындау мен көрсету Ережесiн бекiту туралы" қалалық мәслихатының 2004 жылғы 23 желтоқсандағы № 12/92 шешіміне өзгерістер мен толықтфрулар енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-24
approved_by:
- '163002000002'
version_date:
  kaz: 2005-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/23863/kaz/24.03.2005
