act_code: '165520'
requisite: Решение Актауского городского маслихата Мангистауской области от 25 февраля 2022 года № 11/90. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 марта 2022 года № 27187
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов в городе Актау
  kaz: Ақтау қаласында коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-02-25
approved_by:
- '163002000002'
version_date:
  kaz: 2022-02-25
  rus: 2022-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/165520/kaz/25.02.2022
  rus: https://zan.gov.kz/client/#!/doc/165520/rus/25.02.2022
