act_code: '108819'
requisite: Решение Мангистауского областного маслихата от 8 декабря 2016 года № 6/77. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2017 года № 3238. Утратило силу решением маслихата Мангистауской области от 28 августа 2020 года № 37/451
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Мангистауского областного маслихата» и его описания
  kaz: «Маңғыстау облыстық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-08
approved_by:
- '163000000002'
version_date:
  kaz: 2016-12-08
  rus: 2016-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/108819/kaz/08.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108819/rus/08.12.2016
