act_code: '23574'
requisite: Маңғыстау облысы Маңғыстау ауданы мәслихатының 2005 жылғы 18 тамыздағы № 13/91 шешімі. Маңғыстау облысы Әділет департаменті Маңғыстау ауданының әділет басқармасында 2005 жылғы 14 қыркүйекте № 11-5-11 болып тіркелді
title:
  rus: Маңғыстау ауданының құрметті азаматы атағы жөніндегі Қағиданы бекіту туралы
  kaz: Маңғыстау ауданының құрметті азаматы атағы жөніндегі Қағиданы бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-08-18
approved_by:
- '163004000002'
version_date:
  kaz: 2005-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/23574/kaz/18.08.2005
