act_code: '52365'
requisite: Маңғыстау облысы Қарақия ауданы әкімінің 2010 жылғы 8 ақпандағы № 18 шешімі. Маңғыстау облысының Әділет департаменті Қарақия ауданының Әділет басқармасында 2010 жылғы 2 наурызда № 11-4-102 тіркелді
title:
  rus: 2010 жылдың қаңтар-наурыз айларында 1993 жылы туылған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 2010 жылдың қаңтар-наурыз айларында 1993 жылы туылған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-08
approved_by:
- '163005000003'
version_date:
  kaz: 2010-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/52365/kaz/08.02.2010
