act_code: '85674'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 24 декабря 2014 года № 27/189. Зарегестрировано Департаментом юстиции Мангистауской области от 31 декабря 2014 года № 2573
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015–2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '163006000002'
version_date:
  kaz: 2015-12-11
  rus: 2015-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/85674/kaz/11.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85674/rus/11.12.2015
caused_by:
  code: '96528'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 11 декабря 2015 года № 35/240. Зарегистрировано Департаментом юстиции Мангистауской области от 18 декабря 2015 года № 2914
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 24 декабря 2014 года №27/189 «О районном бюджете на 2015-2017 годы»
    kaz: Түпқараған аудандық мәслихатының  2014 жылғы 24 желтоқсандағы №27/189 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96528/rus
