act_code: '2698'
requisite: Решение акима Мангистауской области от 16 апреля 1999 года № 74. Зарегистрировано Управлением юстиции Мангистауской области 20 апреля 1999 года № 48. Утратило силу письмом акима Мангистауской области от 25 июня 2008 года № 08-12-985
title:
  rus: О проведении зачета по бюджетным долгам.
  kaz: Бюджеттік борыштар бойынша есептесуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-15
approved_by:
- '163000000003'
version_date:
  kaz: 1999-04-15
  rus: 1999-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/2698/kaz/15.04.1999
  rus: https://zan.gov.kz/client/#!/doc/2698/rus/15.04.1999
