act_code: '40033'
requisite: 'ИМПОРТ: Маңғыстау облысы Жаңаөзен қаласы әкімдігінің 2008 жылғы 22 сәуірдегі № 1 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының әділет басқармасында 2008 жылғы 29 мамырда № 11-2-81 болып тіркелді'
title:
  rus: Теңге ауылы көшелеріне ат қою туралы
  kaz: Теңге ауылы көшелеріне ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-24
approved_by:
- '163003000001'
version_date:
  kaz: 2008-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/40033/kaz/24.04.2008
