act_code: '132157'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 17 мая 2019 года № 30/246. Зарегистрировано Департаментом юстиции Мангистауской области 3 июня 2019 года № 3917. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 4 ноября 2021 года № 8/46
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность
  kaz: Сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды  басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-17
approved_by:
- '163006000002'
version_date:
  kaz: 2020-11-30
  rus: 2020-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/132157/kaz/30.11.2020
  rus: https://zan.gov.kz/client/#!/doc/132157/rus/30.11.2020
caused_by:
  code: '149534'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 30 ноября 2020 года № 49/362. Зарегистрировано Департаментом юстиции Мангистауской области 8 декабря 2020 года № 4361. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 4 ноября 2021 года № 8/46
  title:
    rus: О внесении изменения в решение Тупкараганского районного маслихата от 17 мая 2019 года № 30/246 «Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность»
    kaz: Түпқараған аудандық мәслихатының 2019 жылғы 17 мамырдағы № 30/246 «Сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149534/rus
