act_code: '172215'
requisite: Решение акима села Тажен Бейнеуского района Мангистауской области от 21 сентября 2022 года № 01-05/12
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-21
approved_by:
- '163007006001'
version_date:
  kaz: 2022-09-21
  rus: 2022-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/172215/kaz/21.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172215/rus/21.09.2022
