act_code: '135768'
requisite: Решение Мангистауского областного маслихата от 25 октября 2019 года № 31/368. Зарегистрировано Департаментом юстиции Мангистауской области 4 ноября 2019 года № 4009. Утратило силу решением Мангистауского областного маслихата от 13 ноября 2025 года № 23/272 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Мангистауской области
  kaz: Маңғыстау облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-25
approved_by:
- '163000000002'
version_date:
  kaz: 2019-10-25
  rus: 2019-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/135768/kaz/25.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135768/rus/25.10.2019
