act_code: '135768'
requisite: Решение Мангистауского областного маслихата от 25 октября 2019 года № 31/368. Зарегистрировано Департаментом юстиции Мангистауской области 4 ноября 2019 года № 4009. Утратило силу решением Мангистауского областного маслихата от 13 ноября 2025 года № 23/272 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Мангистауской области
  kaz: Маңғыстау облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-25
approved_by:
- '163000000002'
version_date:
  kaz: 2023-12-08
  rus: 2023-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/135768/kaz/08.12.2023
  rus: https://zan.gov.kz/client/#!/doc/135768/rus/08.12.2023
caused_by:
  code: '189941'
  requisite: Решение Мангистауского областного маслихата от 8 декабря 2023 года № 7/80. Зарегистрировано Департаментом юстиции Мангистауской области 13 декабря 2023 года № 4650-12. Утратило силу решением Мангистауского областного маслихата от 13 ноября 2025 года № 23/272 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Мангистауского областного маслихата от 25 октября 2019 года № 31/368 «Об определении размера и перечня категорий получателей жилищных сертификатов по Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2019 жылғы 25 қазандағы № 31/368 «Маңғыстау облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189941/rus
