act_code: '3853'
requisite: Решение акима города Актау Мангистауской области от 8 июня 1999 года № 4413. Зарегистрировано Управлением юстиции Мангистауской области 17 июня 1999 года № 80. Утратило силу решением  акима города Актау Мангистауской области от 27 сентября 1999 года № 4673
title:
  rus: О ликвидации государственного казенного предприятия "Актayская городская межбольничная аптека (7 микрорайон)
  kaz: «Ақтау қалалық ауруханааралық дәріхана» мемлекеттік қазыналық кәсіпорнын (7 шағын аудан) тарату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-07
approved_by:
- '163002000003'
version_date:
  kaz: 1999-06-07
  rus: 1999-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/3853/kaz/07.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3853/rus/07.06.1999
