act_code: '207042'
requisite: Решение акима села Жетыбай Каракиянского района Мангистауской области от 3 февраля 2025 года № 15
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-03
approved_by:
- '163005005001'
version_date:
  kaz: 2025-02-03
  rus: 2025-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/207042/kaz/03.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207042/rus/03.02.2025
