act_code: '44523'
requisite: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2009 жылғы 21 желтоқсандағы № 25/165 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының әділет басқармасында 2010 жылғы 29 қаңтарда № 11-2-130 болып тіркелді
title:
  rus: Жаңаөзен қаласы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
  kaz: Жаңаөзен қаласы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '163003000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/44523/kaz/21.12.2009
