act_code: '89467'
requisite: Решение маслихата Мунайлинского района от 20 марта 2015 года № 30/313. Зарегистрировано Департаментом юстиции Мангистауской области от 30 апреля 2015 года № 2708
title:
  rus: О границах ценового зонирования и поправочных коэффициентов к базовым ставкам платы за земельные участки по сельскому округу Батыр
  kaz: Батыр ауылдық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-20
approved_by:
- '163008000002'
version_date:
  kaz: 2015-03-20
  rus: 2015-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/89467/kaz/20.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89467/rus/20.03.2015
