act_code: '146401'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 11 сентября 2020 года № 53/422. Зарегистрировано Департаментом юстиции Мангистауской области 17 сентября 2020 года № 4291
title:
  rus: Об утверждении Регламента собрания местного сообщества Самского сельского округа
  kaz: Сам ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-11
approved_by:
- '163007000002'
version_date:
  kaz: 2020-09-11
  rus: 2020-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/146401/kaz/11.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146401/rus/11.09.2020
