act_code: '146401'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 11 сентября 2020 года № 53/422. Зарегистрировано Департаментом юстиции Мангистауской области 17 сентября 2020 года № 4291
title:
  rus: Об утверждении Регламента собрания местного сообщества Самского сельского округа
  kaz: Сам ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-11
approved_by:
- '163007000002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/146401/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/146401/rus/13.12.2021
caused_by:
  code: '161969'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 декабря 2021 года № 13/129
  title:
    rus: О внесении изменений и дополнений в решение Бейнеуского районного маслихата от 11 сентября 2020 года № 53/422 «Об утверждении Регламента собрания местного сообщества Самского сельского округа»
    kaz: Бейнеу аудандық мәслихатының 2020 жылғы 11 қыркүйектегі № 53/422 «Сам ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161969/rus
