act_code: '146401'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 11 сентября 2020 года № 53/422. Зарегистрировано Департаментом юстиции Мангистауской области 17 сентября 2020 года № 4291
title:
  rus: Об утверждении Регламента собрания местного сообщества Самского сельского округа
  kaz: Сам ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-11
approved_by:
- '163007000002'
version_date:
  kaz: 2021-08-06
  rus: 2021-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/146401/kaz/06.08.2021
  rus: https://zan.gov.kz/client/#!/doc/146401/rus/06.08.2021
caused_by:
  code: '157879'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 6 августа 2021 года № 10/91
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 11 сентября 2020 года № 53/422 «Об утверждении Регламента собрания местного сообщества Самского сельского округа»
    kaz: «Сам ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» Бейнеу аудандық мәслихатының 2020 жылғы 11 қыркүйектегі № 53/422 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157879/rus
