act_code: '47946'
requisite: Маңғыстау облысы Бейнеу ауданы  Боранқұл ауылдық округі  әкімінің 2009 жылғы 17 тамыздағы № 38 шешімі. Маңғыстау облысы Әділет департаменті Бейнеу ауданының әділет басқармасында 2009 жылғы 21 тамызда  № 11-3-84 болып тіркелді
title:
  rus: Көшеге ат беру туралы
  kaz: Көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-21
approved_by:
- '163007009002'
version_date:
  kaz: 2009-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/47946/kaz/21.08.2009
