act_code: '1970'
requisite: Решение акима  Мангистауской области от 7 октября 1998 года № 251. Зарегистрировано Управлением юстиции Мангистауской области 19 октября 1998 года № 19
title:
  rus: О финансовой поддержке субъектов малого предпринимательства Мангистауской области
  kaz: Маңғыстау облысының шағын кәсіпкерлік субъектілерін қаржылай қолдау туралы.
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-06
approved_by:
- '163000000003'
version_date:
  kaz: 1998-10-06
  rus: 1998-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/1970/kaz/06.10.1998
  rus: https://zan.gov.kz/client/#!/doc/1970/rus/06.10.1998
