act_code: '38711'
requisite: Решение Актауского городского маслихата Мангистауской области от 18 февраля № 6/55 и постановление акимата города Актау от 18 февраля 2008 года № 203. Зарегистрировано Управлением юстиции города Актау Департамента юстиции от 21 марта 2008 года № 11-1-79.Утратило силу постановлением акимата города Актау от 03 июля 2015 года № 844 и решением Актауского городского маслихата Мангистауской области от 03 июля 2015 года № 30/288
title:
  rus: Об установлении границ села Умирзак
  kaz: Өмірзақ ауылының шекарасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-18
approved_by:
- '163002000002'
version_date:
  kaz: 2008-02-18
  rus: 2008-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/38711/kaz/18.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38711/rus/18.02.2008
