act_code: '50972'
requisite: Маңғыстау облысы Мұнайлы ауданы әкімінің 2010 жылғы 25 қаңтардағы № 5 шешімі. Маңғыстау облысының Әділет департаменті Мұнайлы ауданының Әділет басқармасында 2010 жылғы 26 ақпанда № 11-7-68 тіркелді
title:
  rus: Мұнайлы ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне азаматтарды тіркеуге алуды ұйымдастыру туралы
  kaz: Мұнайлы ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне азаматтарды тіркеуге алуды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-25
approved_by:
- '163008000003'
version_date:
  kaz: 2010-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50972/kaz/25.01.2010
