act_code: '190449'
requisite: Решение Актауского городского маслихата Мангистауской области от 14 декабря 2023 года № 9/52
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества села Умирзак и количественного состава представителей жителей села для участия в сходе местного сообщества
  kaz: Өмірзақ ауылы жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-14
approved_by:
- '163002000002'
version_date:
  kaz: 2023-12-14
  rus: 2023-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/190449/kaz/14.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190449/rus/14.12.2023
