act_code: '76189'
requisite: Решение маслихата Мангистауской области от 10 декабря 2013 года № 13/198. Зарегистрировано Департаментом юстиции Мангистауской области 23 декабря 2013 года № 2322
title:
  rus: Об утверждении перечня социально значимых железнодорожных пассажирских межрайонных сообщений Мангистауской области
  kaz: Маңғыстау облысының әлеуметтік мәні бар ауданаралық теміржол жолаушылар қатынасының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2013-12-10
  rus: 2013-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/76189/kaz/10.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76189/rus/10.12.2013
