act_code: '118395'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 3 января 2018 года № 18/233. Зарегистрировано Департаментом юстиции Мангистауской области 25 января 2018 года № 3525
title:
  rus: О бюджете сел, сельских округов на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған ауыл, ауылдық округтер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-03
approved_by:
- '163008000002'
version_date:
  kaz: 2018-06-04
  rus: 2018-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/118395/kaz/04.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118395/rus/04.06.2018
caused_by:
  code: '122870'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 4 июня 2018 года № 24/289. Зарегистрировано Департаментом юстиции Мангистауской области 26 июня 2018 года № 3670
  title:
    rus: О внесении изменений в решение районного маслихата от 3 января 2018 года № 18/233 «О бюджете сел, сельских округов на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2018 жылғы 3 қаңтардағы № 18/233 «2018-2020 жылдарға арналған ауыл, ауылдық округтер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122870/rus
