act_code: '25412'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2005 жылғы 13 сәуірдегі № 17/106 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2005 жылғы 20 мамырда № 11-6-8 болып тіркелді
title:
  rus: Түпқараған ауданы және аудандағы елді мекендерде жануарларды ұстау ережелері туралы
  kaz: Түпқараған ауданы және аудандағы елді мекендерде жануарларды ұстау ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-13
approved_by:
- '163006000002'
version_date:
  kaz: 2005-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/25412/kaz/13.04.2005
