act_code: '42809'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2008 года № 10/116. Зарегистрировано в Департаменте юстиции Мангистауской области 12 декабря 2008 года № 2034
title:
  rus: Об областном бюджете на 2009 год
  kaz: '"2009 жылға арналған облыстық бюджет туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2009-04-10
  rus: 2009-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/42809/kaz/10.04.2009
  rus: https://zan.gov.kz/client/#!/doc/42809/rus/10.04.2009
caused_by:
  code: '45371'
  requisite: Решение Мангистауского областного маслихата от 10 апреля 2009 года № 13/159. Зарегистрировано Департаментом юстиции Мангистауской области 23 апреля 2009 года № 2043
  title:
    rus: О внесении изменений в решение областного маслихата от 10 декабря 2008 года № 10/116 "Об областном бюджете на 2009 год"
    kaz: Облыстық мәслихаттының 2008 жылғы 10 желтоқсандағы № 10/116 "2009 жылға арналған облыстық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45371/rus
