act_code: '36327'
requisite: Решение маслихата города Актау Мангистауской области от 13 декабря 2007 года № 5/34. Зарегистрировано Управлением юстиции города Актау Мангистауской области 26 декабря 2007 года № 11-1-72
title:
  rus: О городском бюджете на 2008 год
  kaz: 2008 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-13
approved_by:
- '163002000002'
version_date:
  kaz: 2008-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/36327/kaz/22.05.2008
caused_by:
  code: '40018'
  requisite: Решение Актауского городского маслихата Мангистауской области от 22 мая 2008 года № 9/88. Зарегистрировано управлением юстиции города Актау Мангистауской области 30 мая 2008 года № 11-1-83
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 13 декабря 2007 года № 5/34 "О городском бюджете на 2008 год"
    kaz: Қалалық мәслихаттың 2007 жылғы 13 желтоқсандағы "2008 жылға арналған қалалық бюджет туралы" № 5/34 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/40018/rus
