act_code: '36327'
requisite: Решение маслихата города Актау Мангистауской области от 13 декабря 2007 года № 5/34. Зарегистрировано Управлением юстиции города Актау Мангистауской области 26 декабря 2007 года № 11-1-72
title:
  rus: О городском бюджете на 2008 год
  kaz: 2008 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-13
approved_by:
- '163002000002'
version_date:
  kaz: 2008-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/36327/kaz/11.11.2008
caused_by:
  code: '42425'
  requisite: Маңғыстау облысы Ақтау қаласы мәслихатының 2008 жылғы 11 қарашадағы № 14/133 шешімі. Маңғыстау облысы Ақтау қаласының Әділет басқармасында 2008 жылғы 24 қарашада № 11-1-99 тіркелді
  title:
    rus: Қалалық мәслихаттың 2007 жылғы 13 желтоқсандағы "2008 жылға арналған қалалық бюджет туралы" № 5/34 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қалалық мәслихаттың 2007 жылғы 13 желтоқсандағы "2008 жылға арналған қалалық бюджет туралы" № 5/34 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42425/rus
