act_code: '228692'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 5 августа 2026 года № 31/232
title:
  rus: О понижении размера ставки налога при применении специального налогового режима на основе упрощенной декларации в Мангистауском районе
  kaz: Маңғыстау ауданында оңайтылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-05
approved_by:
- '163004000002'
version_date:
  kaz: 2026-08-05
  rus: 2026-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/228692/kaz/05.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228692/rus/05.08.2026
