act_code: '76964'
requisite: Решение маслихата Каракиянского района Мангистауской области от 20 декабря 2013 года № 15/145. Зарегистрировано Департаментом юстиции Мангистауской области 21 января 2014 года № 2347. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 29 июня 2015 года № 27/285
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '163005000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/76964/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76964/rus/20.12.2013
