act_code: '169844'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 30 июня 2022 года № 16/155. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 июля 2022 года № 28809
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Каракиянском районе
  kaz: Қарақия ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алудың тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-30
approved_by:
- '163005000002'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/169844/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/169844/rus/03.05.2023
caused_by:
  code: '181377'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 3 мая 2023 года № 2/15.  Зарегистрировано Департаментом юстиции Мангистауской области 16 мая 2023 года № 4563-12
  title:
    rus: О внесении изменений и дополнения в решение «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Каракиянском районе»
    kaz: «Қарақия ауданындағы мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алудың тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181377/rus
