act_code: '138996'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 января 2020 года № 45/360. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2020 года № 4117
title:
  rus: О бюджете села Бейнеу на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Бейнеу ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163007000002'
version_date:
  kaz: 2020-01-13
  rus: 2020-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/138996/kaz/13.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138996/rus/13.01.2020
