act_code: '59158'
requisite: Решение Актауского городского маслихата от 27 апреля 2011 года № 42/385. Зарегистрировано Департаментом юстиции Мангистауской области 03 мая 2011 года № 11-1-156. Утратило силу решением маслихата города Актау Мангистауской области от 19 мая 2020 года № 31/358
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность в городе Актау
  kaz: Ақтау қаласында қызметін жүзеге асыратын барлық салық төлеушілер үшін тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-27
approved_by:
- '163002000002'
version_date:
  kaz: 2016-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/59158/kaz/11.03.2016
caused_by:
  code: '101647'
  requisite: Решение Актауского городского маслихата Мангистауской области от 11 марта 2016 года № 38/381. Зарегистрировано Департаментом юстиции Мангистауской области от 25 апреля 2016 года № 3029. Утратило силу решением маслихата города Актау Мангистауской области от 19 мая 2020 года № 31/358
  title:
    rus: О внесении изменений в решение городского маслихата от 27 апреля 2011 года № 42/385 «Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность в городе Актау»
    kaz: Қалалық мәслихаттың 2011 жылғы 27 сәуірдегі № 42/385 «Қызметін Ақтау қаласында жүзеге асыратын барлық салық төлеушілер үшін бірыңғай тіркелген салық ставкасын белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101647/rus
