act_code: '35186'
requisite: Решение Маслихата Мангистауской области от 15 августа 2007 года N 26/432. Зарегистрировано Департаментом юстиции Манистауской области  21 сентября 2007 года N 1977. Утратило силу - решением Мангистауского областного маслихата от 10 апреля 2009 года N 13/163
title:
  rus: О поправочных коэффициентах к базовой ставке земельного налога и схема зонирования для целей налогообложения по городу Актау
  kaz: Ақтау қаласы бойынша жер салығының базалық ставкаларына түзету коэффиценттері мен салық салу мақсатында аймақтарға бөлу схемасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-08-15
approved_by:
- '163000000002'
version_date:
  rus: 2008-02-12
source:
  rus: https://zan.gov.kz/client/#!/doc/35186/rus/12.02.2008
caused_by:
  code: '38715'
  requisite: Решение маслихата Мангистауской области от 12 февраля 2008 года № 4/61. Зарегистрировано Департаментом юстиции Мангистауской области 13 марта 2008 года № 2005. Утратило силу - решением Мангистауского областного маслихата от 10 апреля 2009 года № 13/163
  title:
    rus: О внесении изменений в решение областного маслихата от 15 августа 2007 года № 26/432 "О поправочных коэффициентах к базовой ставке земельного налога и схема зонирования для целей налогообложения по городу Актау"
    kaz: '"Ақтау қаласы бойынша жер салығының базалық ставкаларына түзету коэффициенттері мен салық салу мақсатында аймақтарға бөлу схемасы туралы" облыстық мәслихаттың 2007 жылғы 15 тамыздағы № 26/432 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/38715/rus
