act_code: '35186'
requisite: Решение Маслихата Мангистауской области от 15 августа 2007 года N 26/432. Зарегистрировано Департаментом юстиции Манистауской области  21 сентября 2007 года N 1977. Утратило силу - решением Мангистауского областного маслихата от 10 апреля 2009 года N 13/163
title:
  rus: О поправочных коэффициентах к базовой ставке земельного налога и схема зонирования для целей налогообложения по городу Актау
  kaz: Ақтау қаласы бойынша жер салығының базалық ставкаларына түзету коэффиценттері мен салық салу мақсатында аймақтарға бөлу схемасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-08-15
approved_by:
- '163000000002'
version_date:
  kaz: 2007-08-15
  rus: 2007-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/35186/kaz/15.08.2007
  rus: https://zan.gov.kz/client/#!/doc/35186/rus/15.08.2007
