act_code: '77773'
requisite: Решение маслихата Мангистауской области от 5 февраля 2014 года № 14/216. Зарегистрировано Департаментом юстиции Мангистауской области 5 марта 2014 года № 2364
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин Мангистауской области (города, района)
  kaz: Маңғыстау облысының (қаласының, ауданының) Құрметті азаматы» атағын беру Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-05
approved_by:
- '163000000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/77773/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/77773/rus/28.12.2023
caused_by:
  code: '191487'
  requisite: Решение Мангистауского областного маслихата от 28 декабря 2023 года № 8/92. Зарегистрировано Департаментом юстиции Мангистауской области 3 января 2024 года № 4661-12
  title:
    rus: О внесении изменений и дополнения в решение Мангистауского областного маслихата от 5 февраля 2014 года № 14/216 «О Правилах присвоения звания «Почетный гражданин Мангистауской области (города, района)»
    kaz: Маңғыстау облыстық мәслихатының 2014 жылғы 5 ақпандағы № 14/216 «Маңғыстау облысының (қаласының, ауданының) Құрметті азаматы» атағын беру Қағидалары туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/191487/rus
