act_code: '47451'
requisite: Решение Актауского городского маслихата № 22/209 от 14 августа 2009 года и постановление акимата города Актау № 928 от 14 августа 2009 года. Зарегистрировано Управлением юстиции города Актау 21 августа 2009 года № 11-1-113
title:
  rus: О наименовании территории под условным названием "Фонтан", расположенной в 12 микрорайоне города Актау, в "Площадь Государственных церемоний"
  kaz: Ақтау қаласының 12 шағын ауданында орналасқан шартты атауы «Фонтан» аталатын аумақты «Мемлекеттік рәсімдер алаңы» деп атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-14
approved_by:
- '163002000002'
version_date:
  kaz: 2021-12-09
  rus: 2021-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/47451/kaz/09.12.2021
  rus: https://zan.gov.kz/client/#!/doc/47451/rus/09.12.2021
caused_by:
  code: '162686'
  requisite: Совместное решение Актауского городского маслихата Мангистауской области от 9 декабря 2021 года № 9/71 и постановление акимата города Актау Мангистауской области от 10 декабря 2021 года № 02-02/2214. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26215
  title:
    rus: О внесении изменения в совместное постановление акимата города Актау от 14 августа 2009 года № 928 и решение Актауского городского маслихата от 14 августа 2009 года № 22/209 «О наименовании территории под условным названием «Фонтан», расположенной в 12 микрорайоне города Актау, в «Площадь Государственных церемоний»
    kaz: Ақтау қаласы әкімдігінің 2009 жылғы 14 тамыздағы № 928 және Ақтау қалалық мәслихатының 2009 жылғы 14 тамыздағы № 22/209 «Ақтау қаласының 12 шағын ауданында орналасқан шартты атауы «Фонтан» аталатын аумақты «Мемлекеттік рәсімдер алаңы» деп атау туралы» бірлескен қаулысы мен шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162686/rus
