act_code: '6405'
requisite: Решение акима  Мангистауской области от 4 аперля 2000 года № 381. Зарегистрировано Управлением юстиции Мангистауской области 20 апреля 2000 года № 208. Утратило силу решением акима  Мангистауской области от 10 августа 2000 года № 478
title:
  rus: Об утверждении Положения о порядке проведения открытых тендеров по продаже объектов приватизации коммунальной собственности
  kaz: Коммуналдық меншіктегі жекешелендіру объектілерін ашық тендер арқылы сату тәртібі жөніндегі ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-03
approved_by:
- '163000000003'
version_date:
  kaz: 2000-04-03
  rus: 2000-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/6405/kaz/03.04.2000
  rus: https://zan.gov.kz/client/#!/doc/6405/rus/03.04.2000
