act_code: '49744'
requisite: Маңғыстау облысы Қарақия аудандық мәслихатының 2009 жылғы 20 қарашадағы № 21/167 шешімі. Қарақия ауданының Әділет басқармасында 2009 жылғы 15 желтоқсанда № 11-4-95 тіркелді.Күші жойылды-Маңғыстау облысы Қарақия аудандық мәслихатының 2013 жылғы 5 наурыздағы № 7/86 шешімімен
title:
  rus: Аудан базарларында қызметі дүркін-дүркін сипатта болатын жеке тұлғалар үшін біржолғы талондардың құны туралы
  kaz: Аудан базарларында қызметі дүркін-дүркін сипатта болатын жеке тұлғалар үшін біржолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-20
approved_by:
- '163005000002'
version_date:
  kaz: 2009-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/49744/kaz/20.11.2009
