act_code: '167273'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 27 апреля 2022 года № 13/78
title:
  rus: Об утверждении регламента Тупкараганского районного маслихата
  kaz: Түпқараған аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-27
approved_by:
- '163006000002'
version_date:
  kaz: 2022-04-27
  rus: 2022-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/167273/kaz/27.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167273/rus/27.04.2022
