act_code: '121046'
requisite: Решение маслихата Мангистауской области города Актау от 3 апреля 2018 года № 14/166. Зарегистрировано Департаментом юстиции Мангистауской области 18 апреля 2018 года № 3573
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Актауского городского маслихата»
  kaz: «Ақтау қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-03
approved_by:
- '163002000002'
version_date:
  kaz: 2022-02-25
  rus: 2022-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/121046/kaz/25.02.2022
  rus: https://zan.gov.kz/client/#!/doc/121046/rus/25.02.2022
caused_by:
  code: '165386'
  requisite: Решение Актауского городского маслихата Мангистауской области от 25 февраля 2022 года № 11/95
  title:
    rus: О внесении изменений в решение Актауского городского маслихата Мангистауской области от 3 апреля 2018 года №14/166 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Актауского городского маслихата»
    kaz: «Ақтау қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» Маңғыстау облысы Ақтау қалалық мәслихатының 2018 жылғы 3 сәуірдегі  №14/166 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165386/rus
