act_code: '72172'
requisite: Решение маслихата Тупкараганского района Мангистауской области от 20 марта 2013 года N 10/76. Зарегистрировано Департаментом юстиции Мангистауской области 22 апреля 2013 года N 2241. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 18 апреля 2024 года № 13/75
title:
  rus: Об определении размера и порядка оказания жилищной помощив Тупкараганском районе
  kaz: Түпқараған ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-20
approved_by:
- '163006000002'
version_date:
  kaz: 2018-12-04
  rus: 2018-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/72172/kaz/04.12.2018
  rus: https://zan.gov.kz/client/#!/doc/72172/rus/04.12.2018
caused_by:
  code: '127244'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 4 декабря 2018 года № 24/202. Зарегистрировано Департаментом юстиции Мангистауской области 14 декабря 2018 года № 3731. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 18 апреля 2024 года № 13/75
  title:
    rus: О внесении изменений и дополнений в решение Тупкараганского  районного маслихата от 20 марта 2013 года № 10/76 «Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам)»
    kaz: Түпқараған аудандық мәслихатының 2013 жылғы 20 наурыздағы № 10/76 «Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Қағидасын бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127244/rus
