act_code: '72172'
requisite: Решение маслихата Тупкараганского района Мангистауской области от 20 марта 2013 года N 10/76. Зарегистрировано Департаментом юстиции Мангистауской области 22 апреля 2013 года N 2241. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 18 апреля 2024 года № 13/75
title:
  rus: Об определении размера и порядка оказания жилищной помощив Тупкараганском районе
  kaz: Түпқараған ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-20
approved_by:
- '163006000002'
version_date:
  kaz: 2022-04-27
  rus: 2022-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/72172/kaz/27.04.2022
  rus: https://zan.gov.kz/client/#!/doc/72172/rus/27.04.2022
caused_by:
  code: '167832'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 27 апреля 2022 года № 13/76. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 мая 2022 года № 28101. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 18 апреля 2024 года № 13/75
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 20 марта 2013 года №10/76 «Об определении размера и порядка оказания жилищной помощи в Тупкараганском районе»
    kaz: Түпқараған аудандық мәслихатының «Түпқараған ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» 2013 жылғы 20 наурыздағы №10/76 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167832/rus
