act_code: '85721'
requisite: Решение Жанаозенского городского маслихата от 24 декабря 2014 года № 35/283. Зарегестрировано Департаментом юстиции Мангистауской области от 08 января 2014 года № 2576
title:
  rus: О городском бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '163003000002'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/85721/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85721/rus/14.12.2015
caused_by:
  code: '96436'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 14 декабря 2015 года № 45/373. Зарегистрировано Департаментом юстиции Мангистауской области от 15 декабря 2015 года № 2912
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 24 декабря 2014 года № 35/283 «О городском бюджете на 2015-2017 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2014 жылғы 24 желтоқсандағы № 35/283 «2015-2017 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96436/rus
