act_code: '3880'
requisite: Маңғыстау облысы Бейнеу ауданы Бейнеу ауылы әкімінің 1999 жылғы 27 сәуірдегі № 1513 шешімі. Маңғыстау облысы Әділет басқармасында 1999 жылғы 5 шілдеде № 93 болып тіркелді
title:
  rus: Аудан аумағында жұқпалы ауруларды таратпау мақсатында базарларда және көтерме саудада сатылатын тамақ өнімдерін сатуды тәртіпке келтіру туралы
  kaz: Аудан аумағында жұқпалы ауруларды таратпау мақсатында базарларда және көтерме саудада сатылатын тамақ өнімдерін сатуды тәртіпке келтіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-26
approved_by:
- '163007000003'
version_date:
  kaz: 1999-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/3880/kaz/26.04.1999
