act_code: '128635'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 11 января 2019 года № 27/344. Зарегистрировано Департаментом юстиции Мангистауской области 18 января 2019 года № 3786
title:
  rus: О бюджете села Тенге на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Теңге ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-11
approved_by:
- '163003000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/128635/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128635/rus/23.12.2019
caused_by:
  code: '137421'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 23 декабря 2019 года № 40/465. Зарегистрировано Департаментом юстиции Мангистауской области 25 декабря 2019 года № 4072
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 11 января 2019 года № 27/344 «О бюджете села Тенге на 2019 - 2021 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2019 жылғы 11 қаңтардағы № 27/344 «2019 - 2021 жылдарға арналған Теңге ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137421/rus
