act_code: '128634'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 11 января 2019 года № 27/345. Зарегистрировано Департаментом юстиции Мангистауской области 18 января 2019 года № 3785
title:
  rus: О бюджете села Рахат на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Рахат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-11
approved_by:
- '163003000002'
version_date:
  kaz: 2019-05-29
  rus: 2019-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128634/kaz/29.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128634/rus/29.05.2019
caused_by:
  code: '132296'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 29 мая 2019 года № 32/388. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2019 года № 3920
  title:
    rus: О внесении изменений и дополнения в решение Жанаозенского городского маслихата от 11 января 2019 года № 27/345 «О бюджете села Рахат на 2019 - 2021 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2019 жылғы 11 қаңтардағы № 27/345 «2019 - 2021 жылдарға арналған Рахат ауылының бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132296/rus
