act_code: '49330'
requisite: Маңғыстау облысы Бейнеу ауданының әкімдігі Сыңғырлау селолық округі әкімінің 2009 жылғы 27 қазандағы № 3 шешімі. Бейнеу ауданының Әділет басқармасында 2009 жылғы 25 қарашада № 11-3-87 тіркелді.
title:
  rus: Орталық көшелерге ат беру туралы
  kaz: Орталық көшелерге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-27
approved_by:
- '163007003001'
version_date:
  kaz: 2017-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/49330/kaz/14.07.2017
caused_by:
  code: '114119'
  requisite: Решение акима села Сынгырлау Бейнеуского района Мангистауской области от 14 июля 2017 года № 4. Зарегистрировано Департаментом юстиции Мангистауской области 16 августа 2017 года № 3409
  title:
    rus: О внесении изменений в решение акима сельского округа Сынгырлау от 27 октября 2009 года № 3 «Орталық көшелерге ат беру туралы»
    kaz: Сыңғырлау селолық округі әкімінің 2009 жылғы 27 қазандағы  № 3 «Орталық көшелерге ат беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114119/rus
