act_code: '87018'
requisite: Решение акима Мунайлинского района от 18 февраля 2015 года № 7-м. Зарегистрировано Департаментом юстиции Мангистауской области от 24 февраля 2015 года № 2620. Утратило силу - решением Акима Мунайлинского района Мангистауской области от 09.06.2015 года № 18-ш.
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-18
approved_by:
- '163008000001'
version_date:
  kaz: 2015-03-26
  rus: 2015-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/87018/kaz/26.03.2015
  rus: https://zan.gov.kz/client/#!/doc/87018/rus/26.03.2015
caused_by:
  code: '88039'
  requisite: Решение акимата Мунайлинского района от 26 марта 2015 года № 9-ш. Зарегистрировано Департаментом юстиции Мангистауской области от 27 марта 2015 года № 2647. Утратило силу - решением Акима Мунайлинского района Мангистауской области от 09.06.2015 года № 18-ш.
  title:
    rus: О внесении изменений в решение акима Мунайлинского района от 18 февраля 2015 года № 7-ш «Об образовании избирательных участков»
    kaz: Мұнайлы ауданы әкімінің 2015 жылғы 18 ақпандағы №7-ш «Сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88039/rus
