act_code: '206233'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 27 декабря 2024 года № 17/134
title:
  rus: О бюджетах сел, сельских округов на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '163004000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206233/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206233/rus/27.12.2024
