act_code: '80518'
requisite: Решение маслихата Мангистауского района Мангистауской области от 24 апреля 2014 года № 17/147. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2014 года № 2439. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 29 ноября 2017 года № 11/126
title:
  rus: Об утверждении pегламента Мангистауского районного маслихата
  kaz: Маңғыстау аудандық мәслихатының pегламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-24
approved_by:
- '163004000002'
version_date:
  kaz: 2014-04-24
  rus: 2014-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/80518/kaz/24.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80518/rus/24.04.2014
