act_code: '85682'
requisite: Решение Бейнеуского районного маслихата от 24 декабря 2014 года № 29/208. Зарегестрировано Департаментом юстиции Мангистауской области от 08 января 2014 года № 2575
title:
  rus: О районном бюджете на 2015 - 2017 годы
  kaz: 2015-2017  жылдарға  арналған аудандық  бюджет  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '163007000002'
version_date:
  kaz: 2015-09-29
  rus: 2015-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/85682/kaz/29.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85682/rus/29.09.2015
caused_by:
  code: '94569'
  requisite: Решение от 29.09.2015 №35/247, Маслихат Бейнеуского района
  title:
    rus: О внесении изменений в решение районного маслихата от 24 декабря 2014 года №29/208 «О районном бюджете на 2015-2017 годы»
    kaz: Аудандық мәслихаттың 2014 жылғы 24 желтоқсандағы №29/208 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94569/rus
