act_code: '13298'
requisite: Решение акима  Мангистауской области от 20 сентября 2002 года № 116. Зарегистрировано Управлением юстиции Мангистауской области 28 сентября 2002 года № 1099. Утратило силу постановлением акима Мангистауской области от 31 марта 2003 года № 42
title:
  rus: О проведении призыва граждан на срочную военную службу в октябре-декабре 2002 года
  kaz: 2002 жылдың қараша-желтоқсан айларында азаматтарды мерзiмдi әскери қызметке шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-09-19
approved_by:
- '163000000003'
version_date:
  kaz: 2002-09-19
  rus: 2002-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/13298/kaz/19.09.2002
  rus: https://zan.gov.kz/client/#!/doc/13298/rus/19.09.2002
