act_code: '221137'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 26 декабря 2025 года № 40/225
title:
  rus: О бюджетах сел, сельских округов на 2026 - 2028 годы
  kaz: 2026 - 2028 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '163008000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/221137/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221137/rus/26.12.2025
