act_code: '221137'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 26 декабря 2025 года № 40/225
title:
  rus: О бюджетах сел, сельских округов на 2026 - 2028 годы
  kaz: 2026 - 2028 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '163008000002'
version_date:
  kaz: 2026-09-04
  rus: 2026-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/221137/kaz/04.09.2026
  rus: https://zan.gov.kz/client/#!/doc/221137/rus/04.09.2026
caused_by:
  code: '230008'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 4 сентября 2026 года № 45/262
  title:
    rus: О внесении изменений в решение Мунайлинского района от 26 декабря 2025 года № 40/225 «О бюджетах сел, сельских округов на 2026-2028 годы»
    kaz: Мұнайлы аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 40/225 «2026-2028 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/230008/rus
