act_code: '114579'
requisite: Решение акима села Таушык Тупкараганского района Мангистауской области от 23 августа 2017 года № 54. Зарегистрировано Департаментом юстиции Мангистауской области 8 сентября 2017 года № 3420
title:
  rus: О присвоении  наименования безымянной улице села Таушык
  kaz: Таушық  ауылының атаусыз  көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-08-23
approved_by:
- '163006002001'
version_date:
  kaz: 2017-08-23
  rus: 2017-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/114579/kaz/23.08.2017
  rus: https://zan.gov.kz/client/#!/doc/114579/rus/23.08.2017
