act_code: '161755'
requisite: Решение Мангистауского областного маслихата от 3 декабря 2021 года № 8/82. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 декабря 2021 года № 25798
title:
  rus: Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Мангистауской области
  kaz: Маңғыстау облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілетін ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-03
approved_by:
- '163000000002'
version_date:
  kaz: 2024-04-05
  rus: 2024-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/161755/kaz/05.04.2024
  rus: https://zan.gov.kz/client/#!/doc/161755/rus/05.04.2024
caused_by:
  code: '195527'
  requisite: Решение Мангистауского областного маслихата от 5 апреля 2024 года № 10/106. Утратило силу решением Мангистауского областного маслихата от 13 декабря 2024 года № 17/192 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 3 декабря 2021 года № 8/82 «Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2021 жылғы 3 желтоқсандағы № 8/82 «Маңғыстау облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілетін ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195527/rus
