act_code: '97634'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 24 декабря 2015 года № 36/246. Зарегистрировано Департаментом юстиции Мангистауской области от 11 января 2016 года № 2934
title:
  rus: 'О районном бюджете на 2016 - 2018    годы '
  kaz: '2016-2018 жылдарға арналған аудандық бюджет туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '163006000002'
version_date:
  kaz: 2016-10-21
  rus: 2016-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/97634/kaz/21.10.2016
  rus: https://zan.gov.kz/client/#!/doc/97634/rus/21.10.2016
caused_by:
  code: '107340'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 21 октября 2016 года № 6/45. Зарегистрировано Департаментом юстиции Мангистауской области от 4 ноября 2016 года № 3169
  title:
    rus: О внесении изменений в решение Тупкараганского  районного маслихата от 24 декабря 2015 года № 36/246 «О районном бюджете на 2016-2018 годы»
    kaz: Түпқарағана аудандық мәслихатының 2015 жылғы 24 желтоқсандағы №36/246 «2016-2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107340/rus
