act_code: '49737'
requisite: Решение Мангистауского областного маслихата от 27 ноября 2009 года № 21/234. Зарегистрировано Департаментом юстиции Мангистауской области 30 декабря 2009 года № 2063
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2010 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша қоршаған ортаға эмиссиялар үшін 2010 жылға арналған төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-27
approved_by:
- '163000000002'
version_date:
  kaz: 2009-11-27
  rus: 2009-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/49737/kaz/27.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49737/rus/27.11.2009
