act_code: '171206'
requisite: Решение Мангистауского областного маслихата от 24 августа 2022 года № 13/155. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 сентября 2022 года № 29391
title:
  rus: Об определении перечня социально значимых сообщений Бейнеуского района
  kaz: Бейнеу ауданының әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-24
approved_by:
- '163000000002'
version_date:
  kaz: 2022-08-24
  rus: 2022-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/171206/kaz/24.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171206/rus/24.08.2022
