act_code: '171206'
requisite: Решение Мангистауского областного маслихата от 24 августа 2022 года № 13/155. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 сентября 2022 года № 29391
title:
  rus: Об определении перечня социально значимых сообщений Бейнеуского района
  kaz: Бейнеу ауданының әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-24
approved_by:
- '163000000002'
version_date:
  kaz: 2025-01-30
  rus: 2025-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/171206/kaz/30.01.2025
  rus: https://zan.gov.kz/client/#!/doc/171206/rus/30.01.2025
caused_by:
  code: '207021'
  requisite: Решение Мангистауского областного маслихата от 30 января 2025 года № 18/202. Зарегистрировано Департаментом юстиции Мангистауской области 4 февраля 2025 года № 4764-12
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 24 августа 2022 года № 13/155 «Об определении перечня социально значимых автомобильных сообщений по селу Бейнеу»
    kaz: Маңғыстау облыстық мәслихатының 2022 жылғы 24 тамыздағы № 13/155 «Бейнеу ауылы бойынша әлеуметтік маңызы бар автомобиль қатынастарының тізбесін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207021/rus
