act_code: '118251'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 30 декабря 2017 года № 20/164. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2018 года № 3517
title:
  rus: О бюджете села Акжигит на 2018 - 2020 годы
  kaz: 2018-2020 жылдарға арналған Ақжігіт ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-30
approved_by:
- '163007000002'
version_date:
  kaz: 2018-06-04
  rus: 2018-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/118251/kaz/04.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118251/rus/04.06.2018
caused_by:
  code: '122920'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 4 июня 2018 года № 23/200. Зарегистрировано Департаментом юстиции Мангистауской области 27 июня 2018 года № 3672
  title:
    rus: О внесении изменений в решение районного маслихата от 30 декабря 2017 года № 20/164 «О бюджете села Акжигит на 2018 - 2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 30 желтоқсандағы № 20/164 «2018 – 2020 жылдарға арналған Ақжігіт ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122920/rus
