act_code: '123983'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 20 июля 2018 года № 22/188. Зарегистрировано Департаментом юстиции Мангистауской области 3 августа 2018 года № 3699
title:
  rus: Об утверждении Регламента собрания местного сообщества сел и сельского округа Тупкараганского района
  kaz: Түпқараған ауданының ауылдарының және ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-20
approved_by:
- '163006000002'
version_date:
  kaz: 2020-08-27
  rus: 2020-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123983/kaz/27.08.2020
  rus: https://zan.gov.kz/client/#!/doc/123983/rus/27.08.2020
caused_by:
  code: '146053'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 27 августа 2020 года № 46/346. Зарегистрировано Департаментом юстиции Мангистауской области 4 сентября 2020 года № 4277
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 20 июля 2018 года № 22/188 «Об утверждении Регламента собрания местного сообщества сел и сельского округа Тупкараганского района»
    kaz: Түпқараған аудандық маслихатының 2018 жылғы 20 шілдедегі № 22/188 «Түпқараған ауданының ауылдарының және ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146053/rus
