act_code: '162882'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 28 декабря 2021 года № 10/67. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26361
title:
  rus: О районном бюджете на 2022 – 2024 годы
  kaz: 2022 - 2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '163006000002'
version_date:
  kaz: 2022-09-13
  rus: 2022-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/162882/kaz/13.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162882/rus/13.09.2022
caused_by:
  code: '171601'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 13 сентября 2022 года № 16/97
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 28 декабря 2021 года № 10/67 «О районном бюджете на  2022– 2024 годы»
    kaz: Түпқараған аудандық мәслихатының 2021 жылғы 28 желтоқсандағы № 10/67 «2022 - 2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171601/rus
