act_code: '30879'
requisite: Маңғыстау облысы Маңғыстау ауданы мәслихатының 2006 жылғы 20 желтоқсандағы № 22/175 шешімі. Маңғыстау облысы Әділет департаменті Маңғыстау  ауданының әділет басқармасында 2006 жылғы 27 желтоқсанда  № 11-5-33 болып тіркелді
title:
  rus: «2007 жылға арналған аудандық бюджет туралы
  kaz: «2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-20
approved_by:
- '163004000002'
version_date:
  kaz: 2006-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/30879/kaz/20.12.2006
