act_code: '13788'
requisite: Решение акима  Мангистауской области от 29 августа 2002 года № 110. Зарегистрировано Управлением юстиции Мангистауской области 18 сентября 2002 года № 1083
title:
  rus: Об организации и проведении начальной военной подготовки с учащимися допризывного возрастов в организациях образования Мангистауской области в 2002-2003 учебном году
  kaz: Маңғыстау облысының білім беру ұйымдастыру әскерге шақырылғанға дейінгі және әскерге шақыру жасындағы оқушыларды 2002-2003 оқу жылындағы бастапқы әскери даярлығын ұйымдастыру және оны өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-08-28
approved_by:
- '163000000003'
version_date:
  kaz: 2002-08-28
  rus: 2002-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/13788/kaz/28.08.2002
  rus: https://zan.gov.kz/client/#!/doc/13788/rus/28.08.2002
