act_code: '41140'
requisite: Маңғыстау облысы Қарақия ауданы Мұнайшы кенті әкімінің 2008 жылғы 14 шілдедегі № 135 шешімі. Маңғыстау облысы Қарақия ауданының Әділет басқармасында 2008 жылғы 7 тамызда № 11-4-63 болып тіркелді
title:
  rus: Мұнайшы кентіндегі жаңа тұрғын үй салу үшін дайындалған шағын аудандарға атау беру туралы
  kaz: Мұнайшы кентіндегі жаңа тұрғын үй салу үшін дайындалған шағын аудандарға атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-14
approved_by:
- '163005002000'
version_date:
  kaz: 2008-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/41140/kaz/14.07.2008
