act_code: '42979'
requisite: 'ИМПОРТ: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2008 жылғы 15 қарашадағы  № 12/83 шешімі. Маңғыстау облысы Әділет департаментінде 2008 жылғы 19 желтоқсанда № 11-2-93 болыптіркелді'
title:
  rus: Жаңаөзен қаласы аумағында құрылыс салу Қағидасы туралы
  kaz: Жаңаөзен қаласы аумағында құрылыс салу Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-15
approved_by:
- '163003000002'
version_date:
  kaz: 2008-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/42979/kaz/15.11.2008
