act_code: '137152'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 12 декабря 2019 года № 39/444. Зарегистрировано Департаментом юстиции Мангистауской области 19 декабря 2019 года № 4062. Утратило силу решением маслихата города Жанаозен Мангистауской области от 25 июня 2020 года № 46/515
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в городе Жанаозен
  kaz: Жаңаөзен қаласында бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '163003000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137152/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137152/rus/12.12.2019
