act_code: '25397'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2005 жылғы 9 желтоқсандағы № 22/139 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2006 жылғы 14 қантарда № 11-6-18 болып тіркелді
title:
  rus: «2006 жылға арналған аудандық бюджет» туралы
  kaz: «2006 жылға арналған аудандық бюджет» туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-09
approved_by:
- '163006000002'
version_date:
  kaz: 2005-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/25397/kaz/09.12.2005
