act_code: '44411'
requisite: Решение от 02.02.2009 №13/130, Акимат Мунайлинского района
title:
  rus: Баянды, Маңғыстау селоларының әкімшілік-аумақтық шекараларын өзгерту туралы
  kaz: Баянды, Маңғыстау селоларының әкімшілік-аумақтық шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-02
approved_by:
- '163008000001'
version_date:
  kaz: 2015-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/44411/kaz/23.07.2015
caused_by:
  code: '92924'
  requisite: 'Решение от 23.07.2015 №35/373, Маслихат Мунайлинского района и постановление от 17.07.2015 №196-қ, Акимат Мунайлинского района '
  title:
    rus: О внесении изменений в постановление акимата Мунайлинского района от 22 января 2009 года №16-қ и в решение Мунайлинского районного маслихата от 3 февраля 2009 года № 13/130 «Об изменении административно-территориальных границ сел Баянды, Мангистау»
    kaz: «Баянды, Маңғыстау селоларының әкімшілік-аумақтық шекараларын өзгерту туралы» Мұнайлы ауданы әкімдігінің 2009 жылғы 22 қаңтардағы №16-қ қаулысына және Мұнайлы аудандық мәслихатының 2009 жылғы 3 ақпандағы № 13/130 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92924/rus
