act_code: '44411'
requisite: Решение от 02.02.2009 №13/130, Акимат Мунайлинского района
title:
  rus: Баянды, Маңғыстау селоларының әкімшілік-аумақтық шекараларын өзгерту туралы
  kaz: Баянды, Маңғыстау селоларының әкімшілік-аумақтық шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-02
approved_by:
- '163008000001'
version_date:
  kaz: 2009-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/44411/kaz/03.02.2009
