act_code: '4759'
requisite: Решение акима  Мангистауской области от 2 декабря 1999 года № 274. Зарегистрировано Управлением юстиции Мангистауской области 7 декабря 1999 года № 155. Утратило силу заключением начальника департамента  юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: Об утверждении графика приватизации объектов коммунальной собственности.
  kaz: Коммуналдық меншіктегі объектілерді жекешелендіру кестесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-02
approved_by:
- '163000000003'
version_date:
  kaz: 1999-12-02
  rus: 1999-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/4759/kaz/02.12.1999
  rus: https://zan.gov.kz/client/#!/doc/4759/rus/02.12.1999
