act_code: '94997'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 29 сентября 2015 года № 35/248. Зарегистрировано Департаментом юстиции Мангистауской области от 03 ноября 2015 года № 2854. Утратило силу решением Бейнеуского районнго маслихата Мангистауской области от 2 мая 2018 года № 22/188
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық   мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-29
approved_by:
- '163007000002'
version_date:
  kaz: 2015-09-29
  rus: 2015-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/94997/kaz/29.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94997/rus/29.09.2015
