act_code: '78608'
requisite: Решение от 27.02.2014 №15/228, Маслихат Мангистауской области Сноска.Утратило силу решением  маслихата  Мангистауского  области от 23 июня  2015 года № 26/405
title:
  rus: О Правилах содержания и выгула собак и кошек в населенных пунктах Мунайлинского района
  kaz: Мұнайлы ауданының елді мекендерінің аумағында иттер мен мысықтарды ұстау және серуендету Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2014-02-27
  rus: 2014-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78608/kaz/27.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78608/rus/27.02.2014
