act_code: '43637'
requisite: Маңғыстау облысы Мұнайлы аудандық мәслихатының 2008 жылғы 12 желтоқсандағы № 11/114 шешімі. Маңғыстау облысының Әділет департаменті Мұнайлы ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 11-7-30 болып енгізілді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-12
approved_by:
- '163008000002'
version_date:
  kaz: 2009-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/43637/kaz/08.05.2009
caused_by:
  code: '46192'
  requisite: Маңғыстау облысы Мұнайлы аудандық мәслихатының 2009 жылғы 8 мамырдағы № 15/158 шешемі. Мұнайлы ауданының Әділет басқармасында 2009 жылғы 18 мамырда № 11-7-39 тіркелді.
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 12 желтоқсандағы № 11/114 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 12 желтоқсандағы № 11/114 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46192/rus
