act_code: '146125'
requisite: Решение Мангистауского областного маслихата от 28 августа 2020 года № 37/446. Зарегистрировано Департаментом юстиции Мангистауской области 8 сентября 2020 года № 4278
title:
  rus: О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Республики Казахстан постоянно проживающих на территории Мангистауской области при амбулаторном лечении бесплатно
  kaz: Маңғыстау облысының аумағында тұрақты тұратын Қазақстан Республикасы азаматтарының жекелеген санаттарына тегін амбулаториялық емдеу кезінде тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде дәрілік заттарды, бейімделген емдік өнімдерді, медициналық бұйымдарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-28
approved_by:
- '163000000002'
version_date:
  kaz: 2023-12-08
  rus: 2023-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/146125/kaz/08.12.2023
  rus: https://zan.gov.kz/client/#!/doc/146125/rus/08.12.2023
caused_by:
  code: '189973'
  requisite: Решение Мангистауского областного маслихата от 8 декабря 2023 года № 7/79
  title:
    rus: О внесении изменения в решение Мангистауского областного маслихата от 28 августа 2020 года № 37/446 «О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Республики Казахстан постоянно проживающих на территории Мангистауской области при амбулаторном лечении бесплатно»
    kaz: Маңғыстау облыстық мәслихатының 2020 жылғы 28 тамыздағы № 37/446 «Маңғыстау облысының аумағында тұрақты тұратын Қазақстан Республикасы азаматтарының жекелеген санаттарына тегін амбулаториялық емдеу кезінде тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде дәрілік заттарды, бейімделген емдік өнімдерді, медициналық бұйымдарды қосымша беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189973/rus
