act_code: '201829'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 14 октября 2024 года № 21/120
title:
  rus: О признании утратившим силу решения Мунайлинского районного маслихата от 1 ноября 2023 года № 6/45 «Об утверждении Плана по управлению пастбищами и их использованию по сельским округам Батыр, Даулет, Кызылтобе и села Баянды Мунайлинского района на 2023 - 2024»
  kaz: Мұнайлы аудандық мәслихатының 2023 жылғы 1 қарашадағы № 6/45 «Мұнайлы ауданының Баянды ауылы және Батыр, Дәулет, Қызылтөбе ауылдық округтері бойынша 2023 - 2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-14
approved_by:
- '163008000002'
version_date:
  kaz: 2024-10-14
  rus: 2024-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/201829/kaz/14.10.2024
  rus: https://zan.gov.kz/client/#!/doc/201829/rus/14.10.2024
