act_code: '40509'
requisite: Маңғыстау облысы Түпқараған ауданы Қызылөзен селосы әкімінің 2008 жылғы 16 маусымдағы № 11 шешімі. Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2008 жылғы 30 маусымда № 11-6-60 болып тіркелді. Күші жойылды-Маңғыстау облысы Түпқараған ауданы Қызылөзен ауылы әкімінің 2017 жылғы 14 ақпандағы № 3 шешімімен
title:
  rus: Қызылөзен селосынан жаңадан пайда болған көшелерге есімдер беру туралы
  kaz: Қызылөзен селосынан жаңадан пайда болған көшелерге есімдер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-16
approved_by:
- '163006004001'
version_date:
  kaz: 2008-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/40509/kaz/16.06.2008
