act_code: '50193'
requisite: Маңғыстау облысы Мұнайлы ауданы әкімдігі Басқұдық селосы округі әкімі аппаратының 2009 жылғы 20 желтоқсандағы № 291 шешімі. Маңғыстау облысы Мұнайлы ауданының Әділет басқармасында 2010 жылғы 19 қаңтарда № 11-7-66 тіркелді
title:
  rus: Басқұдық ауылдық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне және көшелеріне аталар қою туралы
  kaz: Басқұдық ауылдық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне және көшелеріне аталар қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-20
approved_by:
- '163008003001'
version_date:
  kaz: 2014-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/50193/kaz/22.07.2014
