act_code: '61783'
requisite: Решение акима города Актау от 25 ноября 2011 года № 173. Зарегистрировано Департаментом юстиции Мангистауской области 7 декабря 2011 года № 11-1-166
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-25
approved_by:
- '163002000003'
version_date:
  rus: 2011-11-25
source:
  rus: https://zan.gov.kz/client/#!/doc/61783/rus/25.11.2011
