act_code: '224051'
requisite: Решение акима села Рахат города Жанаозен Мангистауской области от 14 апреля 2026 года № 149
title:
  rus: О присвоение наименований безымянным улицам села Рахат
  kaz: Рахат ауылының атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-14
approved_by:
- '163003003001'
version_date:
  kaz: 2026-04-14
  rus: 2026-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/224051/kaz/14.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224051/rus/14.04.2026
