act_code: '77774'
requisite: Решение маслихата Мангистауской области от 5 февраля 2014 года № 14/218. Зарегистрировано Департаментом юстиции Мангистауской области 5 марта 2014 года № 2365
title:
  rus: Об утвержденииПоложении о награждении Почетной грамотой Мангистауской области
  kaz: Маңғыстау облысының Құрмет грамотасымен наградтау жөніндегі Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-05
approved_by:
- '163000000002'
version_date:
  kaz: 2021-12-03
  rus: 2021-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/77774/kaz/03.12.2021
  rus: https://zan.gov.kz/client/#!/doc/77774/rus/03.12.2021
caused_by:
  code: '161377'
  requisite: Решение Мангистауского областного маслихата от 3 декабря 2021 года № 8/83. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 декабря 2021 года № 25649
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 5 февраля 2014 года № 14/218 «О Положении о награждении Почетной грамотой Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2014 жылғы 5 ақпандағы № 14/218 «Маңғыстау облысының Құрмет грамотасымен марапаттаудың Ережесі туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161377/rus
