act_code: '177987'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 30 декабря 2022 года № 28/216
title:
  rus: О бюджете села Рахат на 2023 - 2025 годы
  kaz: 2023 - 2025 жылдарға арналған Рахат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '163003000002'
version_date:
  kaz: 2023-08-21
  rus: 2023-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/177987/kaz/21.08.2023
  rus: https://zan.gov.kz/client/#!/doc/177987/rus/21.08.2023
caused_by:
  code: '185370'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 21 августа 2023 года № 6/50
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 30 декабря 2022 года № 28/216«О бюджете села Рахат на 2023 - 2025 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2022 жылғы 30 желтоқсандағы № 28/216 «2023 - 2025 жылдарға арналған Рахат ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185370/rus
