act_code: '128353'
requisite: Решение Актауского городского маслихата Мангистауской области от 29 декабря 2018 года № 21/237. Зарегистрировано Департаментом юстиции Мангистауской области 11 января 2019 года № 3773
title:
  rus: О бюджете города Актау на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '163002000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/128353/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128353/rus/12.12.2019
caused_by:
  code: '137280'
  requisite: Решение Актауского городского маслихата Мангистауской области от 12 декабря 2019 года № 29/310. Зарегистрировано Департаментом юстиции Мангистауской области 23 декабря 2019 года № 4066
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 29 декабря 2018 года № 21/237 «О бюджете города Актау на 2019-2021 годы»
    kaz: Ақтау қалалық мәслихатының 2018 жылғы 29 желтоқсандағы № 21/237 «2019-2021 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137280/rus
