act_code: '128353'
requisite: Решение Актауского городского маслихата Мангистауской области от 29 декабря 2018 года № 21/237. Зарегистрировано Департаментом юстиции Мангистауской области 11 января 2019 года № 3773
title:
  rus: О бюджете города Актау на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '163002000002'
version_date:
  kaz: 2019-10-28
  rus: 2019-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128353/kaz/28.10.2019
  rus: https://zan.gov.kz/client/#!/doc/128353/rus/28.10.2019
caused_by:
  code: '135849'
  requisite: Решение Актауского городского маслихата Мангистауской области от 28 октября 2019 года № 28/294. Зарегистрировано Департаментом юстиции Мангистауской области 7 ноября 2019 года № 4013
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 29 декабря 2018 года № 21/237 «О бюджете города Актау на 2019-2021 годы»
    kaz: Ақтау қалалық мәслихатының 2018 жылғы 29 желтоқсандағы № 21/237 «2019-2021 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135849/rus
