act_code: '117803'
requisite: Решение Каракиянского  районного маслихата Мангистауской области от 26 декабря 2017 года № 13/167. Зарегистрировано Департаментом юстиции Мангистауской области 16 января 2018 года № 3510
title:
  rus: «О районном бюджете на 2018-2020 годы»
  kaz: «2018-2020 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '163005000002'
version_date:
  kaz: 2018-12-10
  rus: 2018-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/117803/kaz/10.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117803/rus/10.12.2018
caused_by:
  code: '126899'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 10 декабря 2018 года № 22/254. Зарегистрировано Департаментом юстиции Мангистауской области 13 декабря 2018 года № 3730
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 26 декабря 2017 года № 13/167 «О районном бюджете на 2018 - 2020 годы»
    kaz: Қарақия аудандық мәслихатының 2017 жылғы 26 желтоқсандағы № 13/167 «2018 – 2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126899/rus
