act_code: '44081'
requisite: Маңғыстау облысы Маңғыстау аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 13 шешімі. Маңғыстау облысының Әділет департаменті Маңғыстау ауданының Әділет басқармасында 2009 жылғы 15 қаңтарда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 11-5-68 болып енгізілді
title:
  rus: 2009 жылдың қаңтар-наурыз айларында 1992 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 2009 жылдың қаңтар-наурыз айларында 1992 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '163004000001'
version_date:
  kaz: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/44081/kaz/22.12.2008
