act_code: '221128'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 26 декабря 2025 года № 35/321
title:
  rus: О бюджете села Кызылсай на 2026 - 2028 годы
  kaz: 2026 - 2028 жылдарға арналған Қызылсай ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '163003000002'
version_date:
  kaz: 2026-09-02
  rus: 2026-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/221128/kaz/02.09.2026
  rus: https://zan.gov.kz/client/#!/doc/221128/rus/02.09.2026
caused_by:
  code: '229924'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 2 сентября 2026 года № 45/403
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 26 декабря 2025 года № 35/321 «О бюджете села Кызылсай на 2026-2028 годы»
    kaz: «2026-2028 жылдарға арналған Қызылсай ауылының бюджеті туралы» Жаңаөзен қалалық мәслихатының 2025 жылғы 26 желтоқсандағы № 35/321 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229924/rus
