act_code: '76876'
requisite: Утратило силу - решением маслихата Мангистауской области  от 21 мая 2015 года № 25/388.
title:
  rus: О Правилах содержания сельскохозяйственных животных на территории города Актау и села Умирзак
  kaz: Ақтау қаласы және Өмірзақ ауылы аумағында ауыл шаруашылығы жануарларын ұстау Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2013-12-10
  rus: 2013-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/76876/kaz/10.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76876/rus/10.12.2013
