act_code: '115802'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 11 октября 2017 года № 14/160. Зарегистрировано Департаментом юстиции Мангистауской области 2 ноября 2017 года № 3449. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 25 марта 2022 года № 15/123
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность
  kaz: Сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-10-11
approved_by:
- '163003000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/115802/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/115802/rus/23.12.2019
caused_by:
  code: '137807'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 23 декабря 2019 года № 40/469. Зарегистрировано Департаментом юстиции Мангистауской области 31 декабря 2019 года № 4091. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 25 марта 2022 года № 15/123
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 11 октября 2017 года № 14/160 «Об утверждении Правил управления безхозяйными отходами, признанными решением суда поступившими в коммунальную собственность»
    kaz: Жаңаөзен қалалық мәслихатының 2017 жылғы 11 қазандағы № 14/160 «Сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137807/rus
