act_code: '76323'
requisite: Решение Актауского городского маслихата Мангистауской области от 12 декабря 2013 года № 16/152. Зарегистрировано Департаментом юстиции Мангистауской области 27 декабря 2013 года № 2327
title:
  rus: О городском бюджете на 2014 - 2016 годы
  kaz: 2014 - 2016 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-12
approved_by:
- '163002000002'
version_date:
  kaz: 2014-06-24
  rus: 2014-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/76323/kaz/24.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76323/rus/24.06.2014
caused_by:
  code: '81350'
  requisite: Решение маслихата города Актау Мангистауской области от 24 июня 2014 года № 22/207. Зарегистрировано Департаментом юстиции Мангистауской области 4 июля 2014 года № 2474
  title:
    rus: О внесении изменений в решение городского маслихата от 12 декабря 2013 года № 16/152 "О городском бюджете на 2014-2016 годы"
    kaz: Қалалық мәслихаттың 2013 жылғы 12 желтоқсандағы № 16/152 "2014-2016 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81350/rus
