act_code: '73910'
requisite: Решение маслихата Каракиянского района Мангистауской области от 11 июля 2013 года № 11/120. Зарегистрировано Департаментом юстиции Мангистауской области 09 августа 2013 года № 2286. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Каракиянским районе
  kaz: Қарақия ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-11
approved_by:
- '163005000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/73910/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/73910/rus/25.12.2019
caused_by:
  code: '137997'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 25 декабря 2019 года № 37/381. Зарегистрировано Департаментом юстиции Мангистауской области 8 января 2020 года № 4096. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 11 июля 2013 года № 11/120 «Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в Каракиянском районе»
    kaz: Қарақия аудандық мәслихатының 2013 жылғы 11 шілдедегі № 11/120 «Қарақия ауданында аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137997/rus
