act_code: '73910'
requisite: Решение маслихата Каракиянского района Мангистауской области от 11 июля 2013 года № 11/120. Зарегистрировано Департаментом юстиции Мангистауской области 09 августа 2013 года № 2286. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Каракиянским районе
  kaz: Қарақия ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-11
approved_by:
- '163005000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/73910/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/73910/rus/27.11.2020
caused_by:
  code: '149535'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 27 ноября 2020 года № 45/453. Зарегистрировано Департаментом юстиции Мангистауской области 9 декабря 2020 года № 4362. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105
  title:
    rus: О внесении изменений в некоторые решение Каракиянского районного маслихата от 11 июня 2013 года № 11/120 «Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам)»
    kaz: Қарақия аудандық мәслихатының 2013 жылғы 11 шілдедегі № 11/120 «Қарақия ауданында аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149535/rus
