act_code: '43384'
requisite: Маңғыстау облысы Түпқараған ауданы әкімдігінің 2008 жылғы 19 желтоқсандағы № 98 шешімі.Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2008 жылғы 26 желтоқсанда № 11-6-76 тіркелді
title:
  rus: Түпқараған аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1992 жылы туған азаматтарды тіркеуге алуды дайындау және өткізу туралы
  kaz: Түпқараған аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1992 жылы туған азаматтарды тіркеуге алуды дайындау және өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '163006000001'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43384/kaz/19.12.2008
