act_code: '18228'
requisite: Решение Мангистауского областного акима от 23 декабря 2003 года № 155. Зарегистрировано Департаментом юстиции Мангистауской области 15 января 2004 года № 1591
title:
  rus: О проведении приписки граждан 1987 года рождения к призывным участкам в городских и районных военных комиссариатах Мангистауской области
  kaz: Маңғыстау облысының қалалық және аудандық әскери комиссариаттарындағы шақыру учаскелеріне 1987 жылы туылған азаматтарды тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-23
approved_by:
- '163000000001'
version_date:
  kaz: 2003-12-23
  rus: 2003-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/18228/kaz/23.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18228/rus/23.12.2003
