act_code: '30952'
requisite: Решение маслихата  города Актау Мангистауской области от 15 декабря 2006 года № 32/284. Зарегистрировано Управлением юстиции города Актау 28 декабря 2006 года № 11-1-46
title:
  rus: О городском бюджете на 2007 год
  kaz: 2007 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '163002000002'
version_date:
  kaz: 2006-12-15
  rus: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/30952/kaz/15.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30952/rus/15.12.2006
