act_code: '97882'
requisite: Постановление акимата Мангистауской области от 10 декабря 2015 года № 383 и решение Мангистауского областного маслихата от 10 декабря 2015 года № 29/438. Зарегистрировано Департаментом юстиции Мангистауской области от 15 января 2016 года № 2938
title:
  rus: 'Об установлении границ сельского округа Саина Шапагатова Тупкараганского района '
  kaz: 'Түпқараған ауданының Сайын Шапағатов ауылдық округінің шекараларын белгілеу туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2015-12-10
  rus: 2015-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/97882/kaz/10.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97882/rus/10.12.2015
