act_code: '191627'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 28 декабря 2023 года № 11/92
title:
  rus: О бюджете села Боранкул на 2024 – 2026 годы
  kaz: 2024 - 2026 жылдарға арналған Боранқұл ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '163007000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/191627/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191627/rus/28.12.2023
