act_code: '12425'
requisite: Решение Мангистауского областного маслихата от 14 мая 2002 года № 19/195. Зарегистрировано Управлением юстиции Мангистауской области 24 мая 2002 года № 887
title:
  rus: О правилах оказания жилищной помощи малообеспеченным семьям (гражданам) на оплату содержание жилья и потребления коммунальных услуг
  kaz: Аз қамтамасыз етiлген отбасыларына (азаматтарға) тұрғын үйді ұстау және коммуналдық қызметтердi тұтыну ақысын төлеуге тұрғын үй көмегiн көрсету Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-13
approved_by:
- '163000000002'
version_date:
  kaz: 2002-05-13
  rus: 2002-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/12425/kaz/13.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12425/rus/13.05.2002
