act_code: '12425'
requisite: Решение Мангистауского областного маслихата от 14 мая 2002 года № 19/195. Зарегистрировано Управлением юстиции Мангистауской области 24 мая 2002 года № 887
title:
  rus: О правилах оказания жилищной помощи малообеспеченным семьям (гражданам) на оплату содержание жилья и потребления коммунальных услуг
  kaz: Аз қамтамасыз етiлген отбасыларына (азаматтарға) тұрғын үйді ұстау және коммуналдық қызметтердi тұтыну ақысын төлеуге тұрғын үй көмегiн көрсету Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-13
approved_by:
- '163000000002'
version_date:
  kaz: 2003-12-10
  rus: 2003-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/12425/kaz/10.12.2003
  rus: https://zan.gov.kz/client/#!/doc/12425/rus/10.12.2003
caused_by:
  code: '17880'
  requisite: Решение Мангистауского областного маслихата от 10 декабря 2003 года № 2/28. Зарегистрировано Управлением юстиции Мангистауской области 22 декабря 2003 года № 1562
  title:
    rus: О внесении изменения в решение областного маслихата от 14 мая 2002 года № 19/195 "О Правилах оказания жилищной помощи малообеспеченным семьям (гражданам) на оплату содержания жилья и потребления коммунальных услуг"
    kaz: '"Аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын үйді ұстау және коммуналдық қызметтерді тұтыну ақысын төлеуге тұрғын үй көмегін көрсету көлемі мен тәртібін бекіту туралы" облыстық мәслихаттың 2002 жылғы 14 мамырдағы № 19/195 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/17880/rus
