act_code: '177033'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 22 декабря 2022 года № 27/206
title:
  rus: О бюджете города Жанаозен на 2023 - 2025 годы
  kaz: 2023 - 2025 жылдарға арналған Жаңаөзен қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '163003000002'
version_date:
  kaz: 2023-07-31
  rus: 2023-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/177033/kaz/31.07.2023
  rus: https://zan.gov.kz/client/#!/doc/177033/rus/31.07.2023
caused_by:
  code: '184670'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 31 июля 2023 года № 5/36
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 22 декабря 2022 года № 27/206 «О бюджете города Жанаозен на 2023 - 2025 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2022 жылғы 22 желтоқсандағы № 27/206 «2023 - 2025 жылдарға арналған Жаңаөзен қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184670/rus
