act_code: '2723'
requisite: Решение акима Мангистауской области от 24 февраля 1999 года № 3. Зарегистрировано Управлением юстиции Мангистауской области 12 марта 1999 года № 37. Утратило силу заключением начальника управление юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: О реорганизации структуры культуры области
  kaz: Облыстық мәдениет мекемелерінің кұрылымдарын қайта құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-02-24
approved_by:
- '163000000003'
version_date:
  kaz: 1999-02-24
  rus: 1999-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/2723/kaz/24.02.1999
  rus: https://zan.gov.kz/client/#!/doc/2723/rus/24.02.1999
