act_code: '128767'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 января 2019 года № 31/256. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2019 года № 3796
title:
  rus: О бюджете села Бейнеу на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Бейнеу ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163007000002'
version_date:
  kaz: 2019-08-02
  rus: 2019-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/128767/kaz/02.08.2019
  rus: https://zan.gov.kz/client/#!/doc/128767/rus/02.08.2019
caused_by:
  code: '133897'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 2 августа 2019 года № 39/315. Зарегистрировано Департаментом юстиции Мангистауской области 9 августа 2019 года № 3971
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 23 января 2019 года № 31/256 «О бюджете села Бейнеу на 2019 – 2021 годы»
    kaz: Бейнеу аудандық мәслихатының 2019 жылғы 23 қаңтардағы № 31/256 «2019 - 2021 жылдарға арналған Бейнеу ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133897/rus
