act_code: '14855'
requisite: Решение Актауского городского маслихата от 15 октября 2002 года № 26/239. Зарегистрировано Управлением юстиции Мангистауской области 9 января 2003 года № 1246. Утратило силу решением маслихата города Актау Мангистауской области от 12 апреля 2012 года № 2/25
title:
  rus: О правилах содержания, благоустройства территории, объектов городской   инфраструктуры и соблюдения чистоты города Актау и пригородных посeлках
  kaz: Қала инфрақұрылымы объектілерін, аумағын кемелге келтіру, ұстау, Ақтау қаласы және қала жанындағы поселкелердегі тазалықты сақтау ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-10-14
approved_by:
- '163002000002'
version_date:
  kaz: 2002-10-14
  rus: 2002-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/14855/kaz/14.10.2002
  rus: https://zan.gov.kz/client/#!/doc/14855/rus/14.10.2002
