act_code: '86220'
requisite: Решение маслихата Каракиянского района от 15 декабря 2014 года № 24/236. Зарегистрировано Департаментом юстиции Мангистауской области от 22 января 2015 года № 2598.
title:
  rus: 'Об утверждении проекта (схемы)зонирования земель и поправочных коэффициентов к базовым ставкам платы за земельные участки по селу Курык '
  kaz: Құрық ауылы бойынша аймақтарға бөлу жобасын (схемасын) және жер учаскелері үшін төлемақының базалық мөлшерлемесіне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-15
approved_by:
- '163005000002'
version_date:
  kaz: 2018-06-19
  rus: 2018-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/86220/kaz/19.06.2018
  rus: https://zan.gov.kz/client/#!/doc/86220/rus/19.06.2018
caused_by:
  code: '123317'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 19 июня 2018 года № 18/207. Зарегистрировано Департаментом юстиции Мангистауской области 5 июля 2018 года № 3678
  title:
    rus: О внесении изменения в решение Каракиянского районного маслихата от 15 декабря 2014 года № 24/236 «Об утверждении проекта (схемы) зонирования земель и поправочных коэффициентов к базовым ставкам платы за земельные участки по селу Курык»
    kaz: Қарақия аудандық мәслихатының 2014 жылғы 15 желтоқсандағы № 24/236 «Құрық ауылы бойынша аймақтарға бөлу жобасын (схемасын) және жер учаскелері үшін төлемақының базалық мөлшерлемесіне түзету коэффициенттерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123317/rus
