act_code: '4141'
requisite: Решение акима Мангистауской области от 7 сентября 1999 года № 216. Зарегистрировано Управлением юстиции Мангистауской области 17 сентября 1999 года № 135.  Утратило силу заключением начальника департамента юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: Об организации государственных закупок работ по технической рекультивации огаркохранилища № 2 сернокислотного завода в г.Актау
  kaz: Ақтау қаласындағы күкiрт қышқылы зауытының 2-шi шырақ тұқылын сақтау орнын техникалық өңдеу бойынша жұмыстарды мемлекеттiк сатып алуды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-09-06
approved_by:
- '163000000003'
version_date:
  kaz: 1999-09-06
  rus: 1999-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/4141/kaz/06.09.1999
  rus: https://zan.gov.kz/client/#!/doc/4141/rus/06.09.1999
