act_code: '120543'
requisite: Решение маслихата Мангистауского района Мангистауской области от 27 марта 2018 года № 15/165. Зарегистрировано Департаментом юстиции Мангистауской области 9 апреля 2018 года № 3559
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Мангистауского районного маслихата»
  kaz: «Маңғыстау аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-27
approved_by:
- '163004000002'
version_date:
  kaz: 2024-10-18
  rus: 2024-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/120543/kaz/18.10.2024
  rus: https://zan.gov.kz/client/#!/doc/120543/rus/18.10.2024
caused_by:
  code: '201828'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 18 октября 2024 года № 15/115
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 27 марта 2018 года № 15/165 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения» Аппарат Мангистауского районного маслихата»
    kaz: Маңғыстау аудандық мәслихатының 2018 жылғы 27 наурыздағы № 15/165 «Маңғыстау аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201828/rus
