act_code: '166784'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 15 апреля 2022 года № 18/171. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 апреля 2022 года № 27643
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Бейнеуском районе
  kaz: Бейнеу ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-15
approved_by:
- '163007000002'
version_date:
  kaz: 2023-10-13
  rus: 2023-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/166784/kaz/13.10.2023
  rus: https://zan.gov.kz/client/#!/doc/166784/rus/13.10.2023
caused_by:
  code: '187394'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 октября 2023 года № 6/59. Зарегистрировано Департаментом юстиции Мангистауской области 20 октября 2023 года № 4613-12
  title:
    rus: О внесении изменения в решение Бейнеуского районного маслихата от 15 апреля 2022 года № 18/171 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Бейнеуском районе»
    kaz: Бейнеу аудандық мәслихатының 2022 жылғы 15 сәуірдегі № 18/171 «Бейнеу ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187394/rus
