act_code: '53017'
requisite: Маңғыстау облысы Түпқараған ауданы Баутин поселкесін әкімінің 2010 жылғы 05 мамырдағы шешімі.Түпқараған ауданының Әділет басқармасында 2010 жылғы 09 маусымда № 11-6-119 тіркелді. Күші жойылды – Маңғыстау облысы Түпқараған ауданы әкімдігі Баутин ауылы әкімінің 2016 жылғы 02 маусымдағы № 35 шешімімен
title:
  rus: Көшелер атауларын өзгерту туралы
  kaz: Көшелер атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-05
approved_by:
- '163006001001'
version_date:
  kaz: 2010-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/53017/kaz/05.05.2010
