act_code: '132193'
requisite: Решение Мангистауского областного маслихата от 30 мая 2019 года № 27/327. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2019 года № 3923
title:
  rus: О ставках платы за лесные пользования на участках государственного лесного фонда по Мангистауской области
  kaz: Маңғыстау облысы бойынша мемлекеттік орман қоры учаскелеріндегі орманды пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-30
approved_by:
- '163000000002'
version_date:
  kaz: 2021-03-31
  rus: 2021-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/132193/kaz/31.03.2021
  rus: https://zan.gov.kz/client/#!/doc/132193/rus/31.03.2021
caused_by:
  code: '154411'
  requisite: Решение Мангистауского областного маслихата от 31 марта 2021 года № 2/20. Зарегистрировано Департаментом юстиции Мангистауской области 8 апреля 2021 года № 4473
  title:
    rus: О внесении изменений в решение маслихата Мангистауской области от 30 мая 2019 года № 27/327 «О ставках платы за лесные пользования на участках государственного лесного фонда по Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2019 жылғы 30 мамырдағы № 27/327 «Маңғыстау облысы бойынша мемлекеттік орман қоры учаскелеріндегі орманды пайдаланғаны үшін төлемақы мөлшерлемелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154411/rus
