act_code: '132193'
requisite: Решение Мангистауского областного маслихата от 30 мая 2019 года № 27/327. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2019 года № 3923
title:
  rus: О ставках платы за лесные пользования на участках государственного лесного фонда по Мангистауской области
  kaz: Маңғыстау облысы бойынша мемлекеттік орман қоры учаскелеріндегі орманды пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-30
approved_by:
- '163000000002'
version_date:
  kaz: 2022-08-24
  rus: 2022-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/132193/kaz/24.08.2022
  rus: https://zan.gov.kz/client/#!/doc/132193/rus/24.08.2022
caused_by:
  code: '171201'
  requisite: Решение Мангистауского областного маслихата от 24 августа 2022 года № 13/159. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 сентября 2022 года № 29411
  title:
    rus: О внесении изменения в решение маслихата Мангистауской области от 30 мая 2019 года № 27/327 «О ставках платы за лесные пользования на участках государственного лесного фонда по Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының «Маңғыстау облысы бойынша мемлекеттік орман қоры учаскелеріндегі орманды пайдаланғаны үшін төлемақы мөлшерлемелері туралы» 2019 жылғы 30 мамырдағы № 27/327 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171201/rus
