act_code: '122700'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 25 мая 2018 года № 23/281. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2018 года № 3660
title:
  rus: Об утверждении регламента собрания местного сообщества сельского округа Кызылтобе
  kaz: Қызылтөбе ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-25
approved_by:
- '163008000002'
version_date:
  kaz: 2018-05-25
  rus: 2018-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/122700/kaz/25.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122700/rus/25.05.2018
