act_code: '122700'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 25 мая 2018 года № 23/281. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2018 года № 3660
title:
  rus: Об утверждении регламента собрания местного сообщества сельского округа Кызылтобе
  kaz: Қызылтөбе ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-25
approved_by:
- '163008000002'
version_date:
  kaz: 2019-06-07
  rus: 2019-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/122700/kaz/07.06.2019
  rus: https://zan.gov.kz/client/#!/doc/122700/rus/07.06.2019
caused_by:
  code: '132679'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 7 июня 2019 года № 42/409. Зарегистрировано Департаментом юстиции Мангистауской области 17 июня 2019 года № 3929
  title:
    rus: О внесении изменения в решение Мунайлинского районного маслихата от 25 мая 2018 года № 23/281 «Об утверждении регламента собрания местного сообщества сельского округа Кызылтобе»
    kaz: Мұнайлы аудандық мәслихатының 2018 жылғы 25 мамырдағы № 23/281 «Қызылтөбе ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132679/rus
