act_code: '120815'
requisite: Решение Мангистауского областного маслихата от 20 марта 2018 года № 17/211. Зарегистрировано Департаментом юстиции Мангистауской области 13 апреля 2018 года № 3570. Утратило силу решением Мангистауского областного маслихата от 24 апреля 2026 года № 27/322 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О повышении ставок платы за негативное воздействие на окружающую среду по Мангистауской области
  kaz: Маңғыстау облысы бойынша қоршаған ортаға жағымсыз әсер еткені үшін төлемақы мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-20
approved_by:
- '163000000002'
version_date:
  kaz: 2018-03-20
  rus: 2018-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/120815/kaz/20.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120815/rus/20.03.2018
