act_code: '120815'
requisite: Решение Мангистауского областного маслихата от 20 марта 2018 года № 17/211. Зарегистрировано Департаментом юстиции Мангистауской области 13 апреля 2018 года № 3570. Утратило силу решением Мангистауского областного маслихата от 24 апреля 2026 года № 27/322 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О повышении ставок платы за негативное воздействие на окружающую среду по Мангистауской области
  kaz: Маңғыстау облысы бойынша қоршаған ортаға жағымсыз әсер еткені үшін төлемақы мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-20
approved_by:
- '163000000002'
version_date:
  kaz: 2022-12-09
  rus: 2022-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/120815/kaz/09.12.2022
  rus: https://zan.gov.kz/client/#!/doc/120815/rus/09.12.2022
caused_by:
  code: '175851'
  requisite: Решение Мангистауского областного маслихата от 9 декабря 2022 года № 16/182. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2022 года № 31209. Утратило силу решением Мангистауского областного маслихата от 24 апреля 2026 года № 27/322 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 20 марта 2018 года № 17/211 «О ставках платы за эмиссии в окружающую среду по Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2018 жылғы 20 наурыздағы № 17/211 «Маңғыстау облысы бойынша қоршаған ортаға эмиссиялар үшін төлемақы мөлшерлемелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175851/rus
