act_code: '117819'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 21 декабря 2017 года № 17/220. Зарегистрировано Департаментом юстиции Мангистауской области 12 января 2018 года № 3508
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '163008000002'
version_date:
  kaz: 2018-05-25
  rus: 2018-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117819/kaz/25.05.2018
  rus: https://zan.gov.kz/client/#!/doc/117819/rus/25.05.2018
caused_by:
  code: '122203'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 25 мая 2018 года № 23/278. Зарегистрировано Департаментом юстиции Мангистауской области 6 июня 2018 года № 3624
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2017 года № 17/220 «О районном бюджете на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 21 желтоқсандағы № 17/220 «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122203/rus
