act_code: '117819'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 21 декабря 2017 года № 17/220. Зарегистрировано Департаментом юстиции Мангистауской области 12 января 2018 года № 3508
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '163008000002'
version_date:
  kaz: 2018-11-02
  rus: 2018-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/117819/kaz/02.11.2018
  rus: https://zan.gov.kz/client/#!/doc/117819/rus/02.11.2018
caused_by:
  code: '125789'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 2 ноября 2018 года № 30/331. Зарегистрировано Департаментом юстиции Мангистауской области 13 ноября 2018 года № 3716
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2017 года №17/220 «О районном бюджете на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 21 желтоқсандағы №17/220 «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125789/rus
