act_code: '207211'
requisite: Решение акима села Сенек Каракиянского района Мангистауской области от 18 февраля 2025 года № 07
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-18
approved_by:
- '163005003001'
version_date:
  kaz: 2025-02-18
  rus: 2025-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/207211/kaz/18.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207211/rus/18.02.2025
