act_code: '101226'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 15 марта 2016 года № 39/267 и Постановление акимата Тупкараганского района Мангистауской области от 15 марта 2016 года № 46. Зарегистрировано Департаментом юстиции Мангистауской области от 13 апреля 2016 года № 3010
title:
  rus: О присвоении наименования безымянным улицам города Форт-Шевченко
  kaz: Форт-Шевченко қаласындағы атаусыз  көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-15
approved_by:
- '163006000002'
version_date:
  kaz: 2016-03-15
  rus: 2016-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/101226/kaz/15.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101226/rus/15.03.2016
