act_code: '108998'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 9 декабря 2016 года № 6/75. Зарегистрировано Департаментом юстиции Мангистауской области 13 января 2017 года № 3252
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Каракиянского района
  kaz: Қарақия ауданының Құрмет грамотасымен марапаттау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163005000002'
version_date:
  kaz: 2023-07-04
  rus: 2023-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/108998/kaz/04.07.2023
  rus: https://zan.gov.kz/client/#!/doc/108998/rus/04.07.2023
caused_by:
  code: '184019'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 4 июля 2023 года № 5/35. Зарегистрировано Департаментом юстиции Мангистауской области 17 июля 2023 года № 4586-12
  title:
    rus: О внесении изменения в решение Каракиянского районного маслихата от 9 декабря 2016 года № 6/75 «Об утверждении Положения о награждении Почетной грамотой Каракиянского района»
    kaz: Қарақия аудандық мәслихатының 2016 жылғы 9 желтоқсандағы № 6/75 «Қарақия ауданының Құрмет грамотасымен марапаттау туралы Ережені бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184019/rus
