act_code: '107836'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 12 октября 2016 года № 6/65. Зарегистрировано Департаментом юстиции Мангистауской области от 24 ноября 2016 года № 3192. Утратило силу решением маслихата города Жанаозен Мангистауской области от 10 июня 2020 года № 45/511
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения «Аппарат Жанаозенского городского маслихата» и его описание
  kaz: «Жаңаөзен қалалық мәслихатының аппараты» мемлекеттік мекемесінің қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-12
approved_by:
- '163003000002'
version_date:
  kaz: 2016-10-12
  rus: 2016-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/107836/kaz/12.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107836/rus/12.10.2016
