act_code: '118268'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 27 декабря 2017 года № 18/208. Зарегистрировано Департаментом юстиции Мангистауской области 18 января 2018 года № 3513
title:
  rus: О бюджете села Тенге на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған Теңге ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '163003000002'
version_date:
  kaz: 2018-06-14
  rus: 2018-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/118268/kaz/14.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118268/rus/14.06.2018
caused_by:
  code: '122913'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 14 июня 2018 года № 21/268. Зарегистрировано Департаментом юстиции Мангистауской области 25 июня 2018 года № 3667
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 27 декабря 2017 года № 18/208 «О бюджете села Тенге на 2018 - 2020 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2017 жылғы 27 желтоқсандағы № 18/208 «2018 - 2020 жылдарға арналған Теңге ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122913/rus
