act_code: '144555'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 26 июня 2020 года № 45/338. Зарегистрировано Департаментом юстиции Мангистауской области 8 июля 2020 года № 4253
title:
  rus: О некоторых вопросах проведения мирных собраний в Тупкараганском районе
  kaz: Түпқараған ауданында бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-26
approved_by:
- '163006000002'
version_date:
  kaz: 2022-09-13
  rus: 2022-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/144555/kaz/13.09.2022
  rus: https://zan.gov.kz/client/#!/doc/144555/rus/13.09.2022
caused_by:
  code: '171701'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 13 сентября 2022 года № 16/99. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 сентября 2022 года № 29617
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 26 июня 2020 года № 45/338 «О некоторых вопросах проведения мирных собраний в Тупкараганском районе»
    kaz: Түпқараған аудандық мәслихатының 2020 жылғы 26 маусымдағы № 45/338 «Түпқараған ауданында бейбіт жиналыстар өткізудің кейбір мәселелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171701/rus
