act_code: '187841'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 октября 2023 года № 7/71. Зарегистрировано Департаментом юстиции Мангистауской области 31 октября 2023 года № 4626-12
title:
  rus: Об утверждении Правил оказания социальной помощи, установления её размеров и определения перечня отдельных категорий нуждающихся граждан в Бейнеуском районе
  kaz: Бейнеу ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-23
approved_by:
- '163007000002'
version_date:
  kaz: 2025-04-15
  rus: 2025-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/187841/kaz/15.04.2025
  rus: https://zan.gov.kz/client/#!/doc/187841/rus/15.04.2025
caused_by:
  code: '209236'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 15 апреля 2025 года № 28/218. Зарегистрировано Департаментом юстиции Мангистауской области 17 апреля 2025 года № 4785-12
  title:
    rus: О внесении изменения в решение Бейнеуского районного маслихата от 23 октября 2023 года № 7/71 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Бейнеуском районе»
    kaz: Бейнеу аудандық мәслихатының 2023 жылғы 23 қазандағы № 7/71 «Бейнеу ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгеріс  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209236/rus
