act_code: '124407'
requisite: Решение акима села Акшукур Тупкараганского района Мангистауской области от 13 августа 2018 года № 223. Зарегистрировано Департаментом юстиции Мангистауской области 5 сентября 2018 года № 3705
title:
  rus: О присвоении наименования безмянных улиц села Акшукур
  kaz: Ақшұқыр ауылының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-13
approved_by:
- '163006003001'
version_date:
  kaz: 2018-08-13
  rus: 2018-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/124407/kaz/13.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124407/rus/13.08.2018
