act_code: '81183'
requisite: Решение маслихата Мангистауской области от 27 мая 2014 года № 17/256. Зарегистрировано Департаментом юстиции Мангистауской области 03 июля 2014 года № 2468. Утратило силу - решением маслихата Мангистауской области от 27 февраля 2015 года № 22/353
title:
  rus: О Правилах содержания сельскохозяйственных животных на территории города Жанаозен, поселка Рахат и сел Кызылсай, Тенге
  kaz: Жаңаөзен қаласы, Рахат кентінде және қызылсай, Теңге ауылдары аумағында ауылшаруашылығы жануарларын ұстау қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-27
approved_by:
- '163000000002'
version_date:
  kaz: 2014-05-27
  rus: 2014-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/81183/kaz/27.05.2014
  rus: https://zan.gov.kz/client/#!/doc/81183/rus/27.05.2014
