act_code: '108996'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 9 декабря 2016 года № 6/63. Зарегистрировано Департаментом юстиции Мангистауской области 11 января 2017 года № 3246. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 ноября 2022 года № 20/196
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Каракиянскому району
  kaz: Қарақия ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163005000002'
version_date:
  kaz: 2019-06-06
  rus: 2019-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/108996/kaz/06.06.2019
  rus: https://zan.gov.kz/client/#!/doc/108996/rus/06.06.2019
caused_by:
  code: '132617'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 6 июня 2019 года № 31/315. Зарегистрировано Департаментом юстиции Мангистауской области 18 июня 2019 года № 3930. . Утратило силу решением Каракиянского районного маслихата Мангистауской области от 28 ноября 2022 года № 20/196
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 9 декабря 2016 года № 6/63 «Об утверждении норм образования и накопления коммунальных отходов по Каракиянскому району»
    kaz: Қарақия аудандық мәслихатының 2016 жылғы 9 желтоқсандағы № 6/63 «Қарақия ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132617/rus
