act_code: '49469'
requisite: Решение Мангистауского областного маслихата от 27 ноября 2009 года № 21/233. Зарегистрировано Департаментом юстиции Мангистауской области 28 декабря 2009 года № 2062. Утратило силу решением Мангистауского областного маслихата от 27 апреля 2010 года № 24/289
title:
  rus: О Правилах общего водопользования на водных объектах Мангистауской области
  kaz: Маңғыстау облысының су нысандарында суды ортақ пайдаланудың Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-27
approved_by:
- '163000000002'
version_date:
  kaz: 2009-11-27
  rus: 2009-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/49469/kaz/27.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49469/rus/27.11.2009
