act_code: '64233'
requisite: Решение Мангистауского областного маслихата от 21 февраля 2012 года № 2/15. Зарегистрировано Департаментом юстиции Мангистауской области от 27 марта 2012 года № 2120
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2012 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша қоршаған ортаға эмиссиялар үшін 2011 жылға арналған төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-21
approved_by:
- '163000000002'
version_date:
  kaz: 2012-02-21
  rus: 2012-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/64233/kaz/21.02.2012
  rus: https://zan.gov.kz/client/#!/doc/64233/rus/21.02.2012
