act_code: '162684'
requisite: Решение Актауского городского маслихата Мангистауской области от 27 декабря 2021 года № 10/84. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2021 года № 26233
title:
  rus: О бюджете города Актау на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '163002000002'
version_date:
  kaz: 2022-04-15
  rus: 2022-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/162684/kaz/15.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162684/rus/15.04.2022
caused_by:
  code: '166825'
  requisite: Решение Актауского городского маслихата Мангистауской области от 15 апреля 2022 года № 12/107
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 27 декабря 2021 года №10/84 «О бюджете города Актау на 2022-2024 годы
    kaz: Ақтау қалалық мәслихатының 2021 жылғы 27 желтоқсандағы №10/84 «2022-2024 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166825/rus
