act_code: '42071'
requisite: Решение маслихата города Актау Мангистауской области от 15 октября 2008 года № 13/127. Зарегистрировано Управлением юстиции города Актау 31 октября 2008 года № 11-1-97. Утратило силу решением Актауского городского маслихата Мангистауской области от 12 апреля 2012 года № 2/26
title:
  rus: Об утверждении Инструкции по назначению и выплате по льготному проезду на городском общественном транспорте (кроме такси) обучающимся и воспитанникам организации образования очной формы обучения города Актау
  kaz: Ақтау қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-15
approved_by:
- '163002000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/42071/kaz/24.12.2010
caused_by:
  code: '56696'
  requisite: Решение Актауского городского маслихата Мангистауской области от 24 декабря 2010 года № 38/347. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2011 года № 11-1-144. Утратило силу решением Актауского городского маслихата Мангистауской области от 12 апреля 2012 года № 2/26
  title:
    rus: О внесении изменений в решение городского маслихата от 15 октября 2008 года № 13/127 "Об утверждении Инструкции по назначению и выплате по льготному проезду на городском общественном транспорте (кроме такси) обучающимся и воспитанникам организаций образования очной формы обучения города Актау"
    kaz: Қалалық мәслихаттың 2008 жылғы 15 қазандағы № 13/127 "Ақтау қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56696/rus
