act_code: '16714'
requisite: Решение Мангистауского областного маслихата от 30 июля 2003 года № 27/282. Зарегистрировано Департаментом юстиции Мангистауской области 23 августа 2003 года № 1505
title:
  rus: О Плане мероприятий Мангистауской области по реализации Послания Президента страны народу Казахстана "Основные направления внутренней и внешней политики на 2004 год"
  kaz: Елбасының Қазақстан халқына "Ішкі және сыртқы саясаттың 2004 жылға арналған негізгі бағыттары "Жолдауын іске асыру жөніндегі Маңғыстау облысының іс-шаралар Жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-07-29
approved_by:
- '163000000002'
version_date:
  kaz: 2003-07-29
  rus: 2003-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/16714/kaz/29.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16714/rus/29.07.2003
