act_code: '78539'
requisite: Решение маслихата Мангистауской области от 27 февраля 2014 года № 15/229. Зарегистрировано Департаментом юстиции Мангистауской области 3 апреля 2014 года № 2379. Утратило силу решением маслихата Мангистауской области от 11 декабря 2020 года № 39/481
title:
  rus: О Регламенте Мангистауского областного маслихата
  kaz: Маңғыстау облыстық мәслихатының Регламенті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2014-02-27
  rus: 2014-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78539/kaz/27.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78539/rus/27.02.2014
