act_code: '128809'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 25 января 2019 года № 25/279. Зарегистрировано Департаментом юстиции Мангистауской области 28 января 2019 года № 3801
title:
  rus: О бюджетах сел на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған ауылдардың бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-25
approved_by:
- '163005000002'
version_date:
  kaz: 2019-11-22
  rus: 2019-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/128809/kaz/22.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128809/rus/22.11.2019
caused_by:
  code: '136390'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 22 ноября 2019 года № 35/365. Зарегистрировано Департаментом юстиции Мангистауской области 27 ноября 2019 года № 4039
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 25 января 2019 года № 25/279 «О бюджетах сел на 2019 - 2021 годы»
    kaz: Қарақия аудандық мәслихатының 2019 жылғы 25 қаңтардағы № 25/279 «2019 - 2021 жылдарға арналған ауылдардың бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136390/rus
