act_code: '128809'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 25 января 2019 года № 25/279. Зарегистрировано Департаментом юстиции Мангистауской области 28 января 2019 года № 3801
title:
  rus: О бюджетах сел на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған ауылдардың бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-25
approved_by:
- '163005000002'
version_date:
  kaz: 2019-01-25
  rus: 2019-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128809/kaz/25.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128809/rus/25.01.2019
