act_code: '128630'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 14 января 2019 года № 35/371. Зарегистрировано Департаментом юстиции Мангистауской области 21 января 2019 года № 3794
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-14
approved_by:
- '163008000002'
version_date:
  kaz: 2019-07-25
  rus: 2019-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128630/kaz/25.07.2019
  rus: https://zan.gov.kz/client/#!/doc/128630/rus/25.07.2019
caused_by:
  code: '133777'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 25 июля 2019 года № 43/415. Зарегистрировано Департаментом юстиции Мангистауской области 6 августа 2019 года № 3965
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 14 января 2019 года № 35/371 «О районном бюджете на 2019-2021 годы»
    kaz: Мұнайлы аудандық мәслихатының 2019 жылғы 14 қаңтардағы № 35/371 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133777/rus
