act_code: '117194'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2017 года № 15/173. Зарегистрировано Департаментом юстиции Мангистауской области 29 декабря 2017 года № 3497
title:
  rus: Об областном бюджете на 2018 - 2020 годы
  kaz: 2018-2020  жылдарға арналған облыстық  бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2018-05-16
  rus: 2018-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/117194/kaz/16.05.2018
  rus: https://zan.gov.kz/client/#!/doc/117194/rus/16.05.2018
caused_by:
  code: '122010'
  requisite: Решение Мангистауского обласного маслихата от 16 мая 2018 года № 18/217. Зарегистрировано Департаментом юстиции Мангистауской области 29 мая 2018 года № 3613
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 13 декабря 2017 года № 15/173 «Об областном бюджете на 2018-2020 годы»
    kaz: Облыстық мәслихаттың 2017 жылғы 13 желтоқсандағы № 15/173 «2018-2020 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122010/rus
