act_code: '117194'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2017 года № 15/173. Зарегистрировано Департаментом юстиции Мангистауской области 29 декабря 2017 года № 3497
title:
  rus: Об областном бюджете на 2018 - 2020 годы
  kaz: 2018-2020  жылдарға арналған облыстық  бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2017-12-13
  rus: 2017-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117194/kaz/13.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117194/rus/13.12.2017
