act_code: '154548'
requisite: Решение Мангистауского областного маслихата от 31 марта 2021 года № 2/18. Зарегистрировано Департаментом юстиции Мангистауской области 12 апреля 2021 года № 4478
title:
  rus: Об утверждении Правил выпаса сельскохозяйственных животных на территории Мангистауской области
  kaz: Маңғыстау облысының аумағында ауыл шаруашылығы жануарларын жаю қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-31
approved_by:
- '163000000002'
version_date:
  kaz: 2024-09-30
  rus: 2024-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/154548/kaz/30.09.2024
  rus: https://zan.gov.kz/client/#!/doc/154548/rus/30.09.2024
caused_by:
  code: '201396'
  requisite: Решение Мангистауского областного маслихата от 30 сентября 2024 года № 15/159
  title:
    rus: О внесении изменений и дополнения в решение Мангистауского областного маслихата от 31 марта 2021 года № 2/18 «Об утверждении Правил выпаса сельскохозяйственных животных на территории Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2021 жылғы 31 наурыздағы № 2/18 «Маңғыстау облысының аумағында ауыл шаруашылығы жануарларын жаю қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201396/rus
