act_code: '2200'
requisite: Решение акима  Мангистауской области от 18 января 1999 года № 320. Зарегистрировано Управлением юстиции Мангистауской области  15 февраля 1999 года № 29. Утратило силу решением акима  Мангистауской области от 11  ноября 1999 года № 320
title:
  rus: О ставках платежей за загрязнение окружающей среды на 1999 г.
  kaz: 1999 жылы Қоршаған ортаны» ластануына төлем мөлшерін белгілеу туралы.
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-18
approved_by:
- '163000000003'
version_date:
  kaz: 1999-01-18
  rus: 1999-01-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2200/kaz/18.01.1999
  rus: https://zan.gov.kz/client/#!/doc/2200/rus/18.01.1999
