act_code: '151886'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 24 декабря 2020 года № 46/463. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2021 года № 4428
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Каракиянскому району на 2021 - 2022 годы
  kaz: Қарақия ауданы бойынша 2021 - 2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '163005000002'
version_date:
  kaz: 2021-08-24
  rus: 2021-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/151886/kaz/24.08.2021
  rus: https://zan.gov.kz/client/#!/doc/151886/rus/24.08.2021
caused_by:
  code: '158300'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 24 августа 2021 года № 7/51
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 24.12.2020 года № 46/463 «Об утверждении плана по управлению пастбищами и их использованию по Каракиянскому району на 2021-2022 годы»
    kaz: Қарақия аудандық мәслихатының 2020 жылғы 24 желтоқсандағы № 46/463 «Қарақия ауданы бойынша 2021-2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158300/rus
