act_code: '74999'
requisite: Решение маслихата города Жанаозен Мангистауской области от 30 сентября 2013 года № 21/171. Зарегистрировано Департаментом юстиции Мангистауской области 28 октября 2013 года № 2305. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 16 апреля 2021 года № 3/27
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-09-30
approved_by:
- '163003000002'
version_date:
  kaz: 2019-05-17
  rus: 2019-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/74999/kaz/17.05.2019
  rus: https://zan.gov.kz/client/#!/doc/74999/rus/17.05.2019
caused_by:
  code: '131664'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 17 мая 2019 года № 31/375. Зарегистрировано Департаментом юстиции Мангистауской области 22 мая 2019 года № 3895. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 16 апреля 2021 года № 3/27
  title:
    rus: О внесении изменения и дополнения в решение Жанаозенского городского маслихата от 30 сентября 2013 года № 21/171 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Жаңаөзен қалалық мәслихатының 2013 жылғы 30 қыркүйектегі № 21/171 «Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131664/rus
