act_code: '146595'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 15 сентября 2020 года № 57/518. Зарегистрировано Департаментом юстиции Мангистауской области 23 сентября 2020 года № 4293
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-15
approved_by:
- '163008000002'
version_date:
  kaz: 2020-09-15
  rus: 2020-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/146595/kaz/15.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146595/rus/15.09.2020
