act_code: '18101'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2003 года № 2/23. Зарегистрировано Управлением юстиции Мангистауской области 25 декабря 2003 года № 1570
title:
  rus: О Региональной программе правового информирования и правового обучения  населения на 2004-2005 годы
  kaz: Тұрғындарды құқықтық ақпараттандыру мен құқықтық оқытудың 2004-2005 жылдарға арналған Аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2003-12-10
  rus: 2003-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/18101/kaz/10.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18101/rus/10.12.2003
