act_code: '220153'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 26 декабря 2025 года № 38/296
title:
  rus: О бюджете Самского сельского округа на 2026 – 2028 годы
  kaz: 2026-2028 жылдарға арналған Сам ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '163007000002'
version_date:
  kaz: 2026-09-18
  rus: 2026-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/220153/kaz/18.09.2026
  rus: https://zan.gov.kz/client/#!/doc/220153/rus/18.09.2026
caused_by:
  code: '230193'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 18 сентября 2026 года № 46/362
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 26 декабря 2025 года № 38/296 «О бюджете села Сам на 2026–2028 годы»
    kaz: Бейнеу аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 38/296 «2026-2028 жылдарға арналған Сам ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/230193/rus
