act_code: '92739'
requisite: Решение акима Мангистауского района Мангистауской области от 29 июня 2015 года № 12. Зарегистрировано Департаментом юстиции Мангистауской области от 27 июля 2015 года № 2787
title:
  rus: Об образовании избирательных участков в Мангистауском районе
  kaz: Маңғыстау ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-29
approved_by:
- '163004000001'
version_date:
  kaz: 2023-10-04
  rus: 2023-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/92739/kaz/04.10.2023
  rus: https://zan.gov.kz/client/#!/doc/92739/rus/04.10.2023
caused_by:
  code: '187012'
  requisite: Решение акима Мангистауского района Мангистауской области от 4 октября 2023 года № 5. Зарегистрировано Департаментом юстиции Мангистауской области 10 октября 2023 года № 4609-12
  title:
    rus: О внесении изменений в решение акима Мангистауского района от 29 июня 2015 года № 12 «Об образовании избирательных участков в Мангистауском районе»
    kaz: Маңғыстау ауданы әкімінің 2015 жылғы 29 маусымдағы № 12 «Маңғыстау ауданында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187012/rus
