act_code: '92739'
requisite: Решение акима Мангистауского района Мангистауской области от 29 июня 2015 года № 12. Зарегистрировано Департаментом юстиции Мангистауской области от 27 июля 2015 года № 2787
title:
  rus: Об образовании избирательных участков в Мангистауском районе
  kaz: Маңғыстау ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-29
approved_by:
- '163004000001'
version_date:
  kaz: 2021-03-17
  rus: 2021-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/92739/kaz/17.03.2021
  rus: https://zan.gov.kz/client/#!/doc/92739/rus/17.03.2021
caused_by:
  code: '153595'
  requisite: Решение акима Мангистауского района Мангистауской области от 17 марта 2021 года № 3. Зарегистрировано Департаментом юстиции Мангистауской области 18 марта 2021 года № 4467
  title:
    rus: О внесении изменения в решение акима Мангистауского района от 29 июня 2015 года № 12 «Об образовании избирательных участков в Мангистауском районе»
    kaz: Маңғыстау ауданы әкімінің 2015 жылғы 29 маусымдағы № 12 «Маңғыстау ауданында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153595/rus
