act_code: '195156'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/104. Зарегистрировано Департаментом юстиции Мангистауской области 3 апреля 2024 года № 4689-12
title:
  rus: Об утверждении ставок туристского взноса для иностранцев по Каракиянскому району
  kaz: Қарақия ауданы бойынша шетелдіктер үшін туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '163005000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195156/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195156/rus/28.03.2024
