act_code: '117583'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 27 декабря 2017 года № 15/131. Зарегистрировано Департаментом юстиции Мангистауской области 10 января 2018 года № 3505
title:
  rus: О районном бюджете на 2018 - 2020 годы
  kaz: 2018- 2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '163006000002'
version_date:
  kaz: 2018-12-26
  rus: 2018-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/117583/kaz/26.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117583/rus/26.12.2018
caused_by:
  code: '127420'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 26 декабря 2018 года № 27/218. Зарегистрировано Департаментом юстиции Мангистауской области 27 декабря 2018 года № 3760
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 27 декабря 2017 года № 15/131 «О районном бюджете на 2018 - 2020 годы»
    kaz: Түпқараған аудандық мәслихатының 2017 жылғы 27 желтоқсандағы № 15/131 «2018 - 2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127420/rus
