act_code: '117583'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 27 декабря 2017 года № 15/131. Зарегистрировано Департаментом юстиции Мангистауской области 10 января 2018 года № 3505
title:
  rus: О районном бюджете на 2018 - 2020 годы
  kaz: 2018- 2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '163006000002'
version_date:
  kaz: 2018-12-12
  rus: 2018-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/117583/kaz/12.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117583/rus/12.12.2018
caused_by:
  code: '127112'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 12 декабря 2018 года № 25/207. Зарегистрировано Департаментом юстиции Мангистауской области 14 декабря 2018 года № 3732
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 27 декабря 2017 года № 15/131 «О районном бюджете на 2018 - 2020 годы»
    kaz: Түпқараған аудандық мәслихатының 2017 жылғы 27 желтоқсандағы № 15/131 «2018 - 2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127112/rus
