act_code: '138995'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 января 2020 года № 45/361. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2020 года № 4118
title:
  rus: О бюджете села Боранкул на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Боранқұл ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163007000002'
version_date:
  kaz: 2020-01-13
  rus: 2020-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/138995/kaz/13.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138995/rus/13.01.2020
