act_code: '151701'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 24 декабря 2020 года года № 62/544. Зарегистрировано Департаментом юстиции Мангистауской области 12 января 2021 года № 4421
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '163008000002'
version_date:
  kaz: 2021-09-07
  rus: 2021-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/151701/kaz/07.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151701/rus/07.09.2021
caused_by:
  code: '158733'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 7 сентября 2021 года № 8/50. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 сентября 2021 года № 24411
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 24 декабря 2020 года № 62/544 «О районном бюджете на 2021-2023 годы»
    kaz: Мұнайлы аудандық мәслихатының 2020 жылғы 24 желтоқсандағы № 62/544 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158733/rus
