act_code: '205899'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 30 декабря 2024 года № 25/190
title:
  rus: О бюджете Самского сельского округа на 2025 – 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Сам ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '163007000002'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205899/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/205899/rus/28.11.2025
caused_by:
  code: '218192'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 28 ноября 2025 года № 36/275
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 30 декабря 2024 года № 25/190 «О бюджете Самского сельского округа на 2025 – 2027 годы»
    kaz: Бейнеу аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 25/190 «2025-2027 жылдарға арналған Сам ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218192/rus
