act_code: '22628'
requisite: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2004 жылғы 14 желтоқсандағы  № 12/72 шешімі. Маңғыстау облысы Әділет департаментінде 2005 жылғы 18 қаңтарда № 1831 болып тіркелді
title:
  rus: '"Жаңаөзен қаласының Құрметті азаматы" атағы жөнінде ереже туралы'
  kaz: '"Жаңаөзен қаласының Құрметті азаматы" атағы жөнінде ереже туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-14
approved_by:
- '163003000002'
version_date:
  kaz: 2004-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/22628/kaz/14.12.2004
