act_code: '172574'
requisite: Решение акима села Есет Бейнеуского района Мангистауской области от 28 сентября 2022 года № 16
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-28
approved_by:
- '163007002002'
version_date:
  kaz: 2022-09-28
  rus: 2022-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/172574/kaz/28.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172574/rus/28.09.2022
