act_code: '195337'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 28 марта 2024 года № 14/112. Зарегистрировано Департаментом юстиции Мангистауской области 5 апреля 2024 года № 4692-12
title:
  rus: Об определении размера и Правила оказания жилищной помощи в городе Жанаозен
  kaz: Жаңаөзен қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '163003000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195337/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195337/rus/28.03.2024
