act_code: '195337'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 28 марта 2024 года № 14/112. Зарегистрировано Департаментом юстиции Мангистауской области 5 апреля 2024 года № 4692-12
title:
  rus: Об определении размера и Правила оказания жилищной помощи в городе Жанаозен
  kaz: Жаңаөзен қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '163003000002'
version_date:
  kaz: 2026-04-29
  rus: 2026-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195337/kaz/29.04.2026
  rus: https://zan.gov.kz/client/#!/doc/195337/rus/29.04.2026
caused_by:
  code: '225023'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 29 апреля 2026 года № 39/353. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 мая 2026 года № 38634
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 28 марта 2024 года № 14/112 «Об определении размера и порядка оказания жилищной помощи в городе Жанаозен»
    kaz: Жаңаөзен қалалық мәслихатының 2024 жылғы 28 наурыздағы № 14/112 «Жаңаөзен қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225023/rus
