act_code: '42380'
requisite: Маңғыстау облысы Мұнайлы ауданы Маңғыстау ауылы әкімінің 2008 жылғы 16 маусымдағы № 226 шешімі. Маңғыстау облысы Мұнайлы ауданының Әділет басқармасында 2008 жылғы 30 маусымда № 11-7-11 болып тіркелді
title:
  rus: Маңғыстау ауылының әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктерінің атауларын өзгерту туралы
  kaz: Маңғыстау ауылының әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-16
approved_by:
- '163008007001'
version_date:
  kaz: 2019-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/42380/kaz/13.03.2019
caused_by:
  code: '129631'
  requisite: Решение акима села Мангистау Мунайлинского района Мангистауской области от 13 марта 2019 года № 73. Зарегистрировано Департаментом юстиции Мангистауской области 13 марта 2019 года № 3839
  title:
    rus: О внесении изменений в решение акима села Мангистау от 16 июня 2008 года № 226 «Маңғыстау ауылының әкімшілік - аумақтық құрылысына қарасты құрамдас бөліктерінің атауларын өзгерту туралы»
    kaz: Маңғыстау ауылы әкімінің 2008 жылғы 16 маусымдағы № 226 «Маңғыстау ауылының әкімшілік - аумақтық құрылысына қарасты құрамдас бөліктерінің атауларын өзгерту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129631/rus
