act_code: '138999'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 января 2020 года № 45/359. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2020 года № 4115
title:
  rus: О бюджете села Акжигит на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақжігіт ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163007000002'
version_date:
  kaz: 2020-01-13
  rus: 2020-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/138999/kaz/13.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138999/rus/13.01.2020
