act_code: '115387'
requisite: Решение Мангистауского областного маслихата от 29 сентября 2017 года № 13/158. Зарегистрировано Департаментом юстиции Мангистауской области 17 октября 2017 года № 3439. Утратило силу решением Мангистауского областного маслихата от 8 декабря 2023 года № 7/86
title:
  rus: Об утверждении Правил регулирования миграционных процессов в Мангистауской области
  kaz: Маңғыстау облысындағы көші-қон процестерін реттеу Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-09-29
approved_by:
- '163000000002'
version_date:
  kaz: 2021-08-27
  rus: 2021-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/115387/kaz/27.08.2021
  rus: https://zan.gov.kz/client/#!/doc/115387/rus/27.08.2021
caused_by:
  code: '158335'
  requisite: Решение Мангистауского областного маслихата от 27 августа 2021 года № 5/65. Утратило силу решением Мангистауского областного маслихата от 8 декабря 2023 года № 7/86
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 29 сентября 2017 года № 13/158 «Об утверждении Правил регулирования миграционных процессов в Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2017 жылғы 29 қыркүйектегі № 13/158 «Маңғыстау облысындағы көші-қон процестерін реттеу Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158335/rus
