act_code: '115387'
requisite: Решение Мангистауского областного маслихата от 29 сентября 2017 года № 13/158. Зарегистрировано Департаментом юстиции Мангистауской области 17 октября 2017 года № 3439. Утратило силу решением Мангистауского областного маслихата от 8 декабря 2023 года № 7/86
title:
  rus: Об утверждении Правил регулирования миграционных процессов в Мангистауской области
  kaz: Маңғыстау облысындағы көші-қон процестерін реттеу Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-09-29
approved_by:
- '163000000002'
version_date:
  kaz: 2019-04-26
  rus: 2019-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/115387/kaz/26.04.2019
  rus: https://zan.gov.kz/client/#!/doc/115387/rus/26.04.2019
caused_by:
  code: '131108'
  requisite: Решение Мангистауского областного маслихата от 26 апреля 2019 года № 26/316. Зарегистрировано Департаментом юстиции Мангистауской области 4 мая 2019 года № 3881. Утратило силу решением Мангистауского областного маслихата от 8 декабря 2023 года № 7/86
  title:
    rus: О внесении изменения и дополнения в решение Мангистауского областного маслихата от 29 сентября 2017 года № 13/158 «Об утверждении Правил регулирования миграционных процессов в Мангистауской области»
    kaz: Маңғыстау облыстық мәслихатының 2017 жылғы 29 қыркүйектегі № 13/158 «Маңғыстау облысындағы көші-қон процестерін реттеу Қағидаларын бекіту туралы» шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131108/rus
