act_code: '97517'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2015 года № 29/441.  Зарегистрировано Департаментом юстиции Мангистауской области от 13 января 2016 года № 2936. Утратило силу решением Мангистауского областного маслихата от 28 мая 2021 года № 3/53
title:
  rus: О Правилах содержания животных на территории населенных пунктов Каракиянского района
  kaz: Қарақия ауданының елді мекендерінің аумағында жануарларды асырау  Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2015-12-10
  rus: 2015-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/97517/kaz/10.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97517/rus/10.12.2015
