act_code: '46376'
requisite: Мұнайлы ауданы мәслихатының 2009 жылғы 8 мамырдағы № 15/161 шешімі. Мұнайлы ауданы Әділет басқармасында 2009 жылғы 9 маусымда № 11-7-45 тіркелді. Күші жойылды – Маңғыстау облысы Мұнайлы аудандық мәслихатының 2016 жылғы 11 шілдедегі № 3/38 шешімімен
title:
  rus: Маңғыстау селосы бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
  kaz: Маңғыстау селосы бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-07
approved_by:
- '163008000002'
version_date:
  kaz: 2015-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/46376/kaz/23.07.2015
caused_by:
  code: '92916'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 23 июля 2015 года № 35/374. Зарегистрировано Департаментом юстиции Мангистауской области от 14 августа 2015 года № 2804. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 21 июля 2021 года № 6/42
  title:
    rus: О внесении изменений в некоторые решения Мунайлинского районного маслихата
    kaz: Кейбір Мұнайлы аудандық мәслихатының шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92916/rus
