act_code: '9070'
requisite: Решение Мангистауского областного маслихата от 19 декабря 2000 года № 9/69. Зарегистрировано в Управлении юстиции Мангистауской области 4 января 2001 года № 323
title:
  rus: Об областном бюджете на 2001 год
  kaz: 2001 жылғы арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-19
approved_by:
- '163000000002'
version_date:
  rus: 2001-01-26
source:
  rus: https://zan.gov.kz/client/#!/doc/9070/rus/26.01.2001
caused_by:
  code: '9281'
  requisite: Решение Мангистауского областного маслихата от 26 января 2001 года № 10/78. Зарегистрировано управлении юстиции Мангистауской области 30 января 2001 года № 357
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 19 декабря 2000 года N 9/69 "Об областном бюджете на 2001 год"
    kaz: Облыстық мәслихаттың "2001 жылға арналған облыстық бюджет туралы" 2000 жылғы 19 желтоқсандағы N 9/69 шешiмiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/9281/rus
