act_code: '9070'
requisite: Решение Мангистауского областного маслихата от 19 декабря 2000 года № 9/69. Зарегистрировано в Управлении юстиции Мангистауской области 4 января 2001 года № 323
title:
  rus: Об областном бюджете на 2001 год
  kaz: 2001 жылғы арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-19
approved_by:
- '163000000002'
version_date:
  kaz: 2001-03-27
  rus: 2001-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/9070/kaz/27.03.2001
  rus: https://zan.gov.kz/client/#!/doc/9070/rus/27.03.2001
caused_by:
  code: '9358'
  requisite: Решение Мангистауского областного маслихата от 28 марта 2001 года № 11/85. Зарегистрировано Управлением юстиции Мангистауской области 10 апреля № 394
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 19 декабря 2000 года № 9/69 "Об областном бюджете на 2001 год"
    kaz: Облыстық мәслихаттың 2000 жылғы 19 желтоқсандағы N 9/69 "2001 жылға арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/9358/rus
