act_code: '171305'
requisite: Решение Мангистауского областного маслихата от 24 августа 2022 года № 13/152
title:
  rus: Об утверждении Правил содержания и выгула домашних животных по Мангистауской области
  kaz: Маңғыстау облысы бойынша үй жануарларын ұстаудың және серуендетудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-24
approved_by:
- '163000000002'
version_date:
  kaz: 2022-08-24
  rus: 2022-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/171305/kaz/24.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171305/rus/24.08.2022
