act_code: '107859'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 21 октября 2016 года № 4/73. Зарегистрировано Департаментом юстиции Мангистауской области от 30 ноября 2016 года № 3198.  Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 27 апреля 2018 года № 22/273
title:
  rus: Об установлении единой ставки фиксированного налога (бильярдный стол) для всех налогоплательщиков
  kaz: Барлық салық төлеушілер үшін біріңғай тіркелген салық мөлшерлемесін (бильярд үстелі) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '163008000002'
version_date:
  kaz: 2016-10-21
  rus: 2016-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/107859/kaz/21.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107859/rus/21.10.2016
