act_code: '44706'
requisite: Қарақия аудандық мәслихатының 2009 жылғы 6 ақпандағы № 13/106 шешімі. Қарақия ауданының Әділет басқармасында 2009 жылғы 4 наурызда № 11-4-76 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2012 жылғы 2 ақпандағы № 1/13 шешімімен
title:
  rus: Азаматтардың жекелеген санаттарына (жеке тұрғын үйді ұстаудан басқа) тұрғын үйді ұстауға және пайдаланылған коммуналдық қызмет төлемдерін өтеуге әлеуметтік көмек көрсету Тәртібі туралы
  kaz: Азаматтардың жекелеген санаттарына (жеке тұрғын үйді ұстаудан басқа) тұрғын үйді ұстауға және пайдаланылған коммуналдық қызмет төлемдерін өтеуге әлеуметтік көмек көрсету Тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '163005000002'
version_date:
  kaz: 2009-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/44706/kaz/06.02.2009
