act_code: '195154'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105. Зарегистрировано Департаментом юстиции Мангистауской области 3 апреля 2024 года № 4690-12
title:
  rus: Об определении размера и Правил оказания жилищной помощи в Каракиянском районе
  kaz: Қарақия ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '163005000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195154/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195154/rus/28.03.2024
