act_code: '195154'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 марта 2024 года № 13/105. Зарегистрировано Департаментом юстиции Мангистауской области 3 апреля 2024 года № 4690-12
title:
  rus: Об определении размера и Правил оказания жилищной помощи в Каракиянском районе
  kaz: Қарақия ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '163005000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/195154/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/195154/rus/26.12.2025
caused_by:
  code: '220288'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 26 декабря 2025 года № 35/288. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2025 года № 37780
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 28 марта 2024 года № 13/105 «Об определении размера и порядка оказания жилищной помощи в Каракиянском районе
    kaz: «Қарақия ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» Қарақия аудандық мәслихатының 2024 жылғы 28 наурыздағы № 13/105 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/220288/rus
