act_code: '203769'
requisite: Решение акима села Курык Каракиянского района Мангистауской области от 22 августа 2024 года № 170.
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-22
approved_by:
- '163005006002'
version_date:
  kaz: 2024-08-22
  rus: 2024-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/203769/kaz/22.08.2024
  rus: https://zan.gov.kz/client/#!/doc/203769/rus/22.08.2024
