act_code: '80454'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 6 мая 2014 года № 21/244. Зарегистрировано Департаментом юстиции Мангистауской области 26 мая 2014 года № 2431. Утратило силу решением Мунайлинского  районного маслихата Мангистауской области от 31 мая 2024 года № 16/97
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в Мунайлинском районе
  kaz: Мұнайлы ауданында аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-06
approved_by:
- '163008000002'
version_date:
  kaz: 2023-05-18
  rus: 2023-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/80454/kaz/18.05.2023
  rus: https://zan.gov.kz/client/#!/doc/80454/rus/18.05.2023
caused_by:
  code: '182091'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 18 мая 2023 года № 3/20. Зарегистрировано Департаментом юстиции Мангистауской области 26 мая 2023 года № 4567-12. Утратило силу решением Мунайлинского  районного маслихата Мангистауской области от 31 мая 2024 года № 16/97
  title:
    rus: О внесении изменения в решение Мунайлинского районного маслихата от 6 мая 2014 года № 21/244 «Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в Мунайлинском районе»
    kaz: Мұнайлы аудандық мәслихатының 2014 жылғы 6 мамырдағы № 21/244 «Мұнайлы ауданында аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182091/rus
