act_code: '76805'
requisite: Решение Актауского городского маслихата Мангистауской области от 12 декабря 2013 года № 16/155. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2014 года № 2339.Утратило силу-решением Актауского городского маслихата Мангистауской области от 21 октября 2016 года № 5/58
title:
  rus: Об утверждении перечня памятных дат, праздничных дней и кратности оказания социальной помощи для отдельных категорий нуждающихся граждан, а также установления размеров социальной помощи
  kaz: Мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау және әлеуметтік көмектің мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-12
approved_by:
- '163002000002'
version_date:
  kaz: 2014-06-06
  rus: 2014-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/76805/kaz/06.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76805/rus/06.06.2014
caused_by:
  code: '81368'
  requisite: Решение маслихата города Актау Мангистауской области от 6 июня 2014 года № 21/198. Зарегистрировано Департаментом юстиции Мангистауской области 8 июля 2014 года № 2475.Утратило силу-решением Актауского городского маслихата Мангистауской области от 21 октября 2016 года № 5/58
  title:
    rus: О внесении изменений  и  дополнений в решение городского маслихата от 12 декабря 2013 года № 16/155 "Об утверждении перечня памятных дат, праздничных дней и кратности оказания социальной помощи для отдельных категорий нуждающихся граждан, а также установления размеров социальной помощи"
    kaz: '"Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету үшін атаулы және мереке күндерінің тізбесін, оны көрсету еселігін бекіту, сондай-ақ әлеуметтік көмектің мөлшерін белгілеу туралы" 2013 жылғы 12 желтоқсандағы № 16/155 қалалық мәслихаттың шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/81368/rus
