act_code: '76805'
requisite: Решение Актауского городского маслихата Мангистауской области от 12 декабря 2013 года № 16/155. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2014 года № 2339.Утратило силу-решением Актауского городского маслихата Мангистауской области от 21 октября 2016 года № 5/58
title:
  rus: Об утверждении перечня памятных дат, праздничных дней и кратности оказания социальной помощи для отдельных категорий нуждающихся граждан, а также установления размеров социальной помощи
  kaz: Мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау және әлеуметтік көмектің мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-12
approved_by:
- '163002000002'
version_date:
  kaz: 2013-12-12
  rus: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/76805/kaz/12.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76805/rus/12.12.2013
