act_code: '52519'
requisite: Қарақия ауданы әкімдігі Құрық селосы әкімінің 2010 жылғы 7 мамырдағы № 356 шешімі. Қарақия ауданының Әділет басқармасында 2010 жылғы 7 мамырда № 11-4-106 тіркелді. Күші жойылды – Маңғыстау облысы Қарақия ауданы әкімдігі Құрық ауылы әкімінің 2016 жылғы 01 маусымдағы № 207 шешімімен
title:
  rus: Құрық селосының теңіз жағалауындағы "Саңырауқұлақ" демалыс орнына Жолболдин Муханмеди Мергенбаевичтің атын беру туралы
  kaz: Құрық селосының теңіз жағалауындағы "Саңырауқұлақ" демалыс орнына Жолболдин Муханмеди Мергенбаевичтің атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-07
approved_by:
- '163005000001'
version_date:
  kaz: 2010-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/52519/kaz/07.05.2010
