act_code: '88379'
requisite: Решение маслихата Мангистауской области от 27 февраля 2015 года № 22/352. Зарегистрировано Департаментом юстиции Мангистауской области от 03 апреля 2015 года № 2660. Утратило силу решением Мангистауского областного маслихата от 28 мая 2021 года № 3/49
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек на территории города Жанаозен и аулов Рахат, Кызылсай, Тенге
  kaz: Жаңаөзен қаласы және Рахат, Қызылсай, Теңге ауылдарының аумағында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2019-05-30
  rus: 2019-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/88379/kaz/30.05.2019
  rus: https://zan.gov.kz/client/#!/doc/88379/rus/30.05.2019
caused_by:
  code: '132366'
  requisite: Решение Мангистауского областного маслихата от 30 мая 2019 года № 27/332. Зарегистрировано Департаментом юстиции Мангистауской области 11 июня 2019 года № 3926. Утратило силу решением Мангистауского областного маслихата от 28 мая 2021 года № 3/49
  title:
    rus: О внесении изменения в решение Мангистауского областного маслихата от 27 февраля 2015 года № 22/352 «Об утверждении Правил содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек на территории города Жанаозен и аулов Рахат, Кызылсай, Тенге»
    kaz: Маңғыстау облыстық мәслихатының 2015 жылғы 27 ақпандағы № 22/352 «Жаңаөзен қаласы және Рахат, Қызылсай, Теңге ауылдарының аумағында иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132366/rus
