act_code: '190429'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 15 декабря 2023 года № 7/63
title:
  rus: О районном бюджете на 2024 - 2026 годы
  kaz: 2024 - 2026 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '163004000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190429/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190429/rus/15.12.2023
