act_code: '60723'
requisite: Решение Актауского городского маслихата Мангистауской области от 24 августа 2011 года № 46/412. Зарегистрировано Департаментом юстиции Мангистауской области 07 октября 2011 года № 11-1-163. Утратило силу решением Актауского городского маслихата Мангистауской области от 19.07.2012 № 4/47.
title:
  rus: Об утверждении Правил застройки территории города Актау
  kaz: Ақтау қаласы аумағында құрылыс салу Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-24
approved_by:
- '163002000002'
version_date:
  kaz: 2011-08-23
  rus: 2011-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/60723/kaz/23.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60723/rus/23.08.2011
