act_code: '128434'
requisite: Решение акима города Жанаозен Мангистауской области от 10 января 2019 года № 1. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2019 года № 3774
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '163003000003'
version_date:
  kaz: 2023-11-07
  rus: 2023-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/128434/kaz/07.11.2023
  rus: https://zan.gov.kz/client/#!/doc/128434/rus/07.11.2023
caused_by:
  code: '188301'
  requisite: Решение акима города Жанаозен Мангистауской области от 7 ноября 2023 года № 15. Зарегистрировано Департаментом юстиции Мангистауской области 14 ноября 2023 года № 4634-12
  title:
    rus: О внесении изменений в решение акима города Жанаозен от 10 января 2019 года № 1 «Об образовании избирательных участков»
    kaz: Жаңаөзен қаласы әкімінің 2019 жылғы 10 қаңтардағы № 1 «Сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188301/rus
