act_code: '128434'
requisite: Решение акима города Жанаозен Мангистауской области от 10 января 2019 года № 1. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2019 года № 3774
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '163003000003'
version_date:
  kaz: 2025-04-10
  rus: 2025-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/128434/kaz/10.04.2025
  rus: https://zan.gov.kz/client/#!/doc/128434/rus/10.04.2025
caused_by:
  code: '209113'
  requisite: Решение акима города Жанаозен Мангистауской области от 10 апреля 2025 года № 89. Зарегистрировано Департаментом юстиции Мангистауской области 14 апреля 2025 года № 4783-12
  title:
    rus: О внесении изменения в решение акима города Жанаозен от 10 января 2019 года № 1 «Об образовании избирательных участков»
    kaz: Жаңаөзен қаласы әкімінің 2019 жылғы 10 қаңтардағы № 1 «Сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209113/rus
