act_code: '23427'
requisite: Маңғыстау облысы Маңғыстау ауданы әкімдігінің 2005 жылғы 24 ақпандағы № 49 қаулысы. Маңғыстау облысы Әділет департаментінде 2005 жылғы 31 наурызда  № 1882 болып тіркелді
title:
  rus: Облыстық дәрежедегі дербес зейнеткерлерді әлеуметтік қолдау туралы
  kaz: Облыстық дәрежедегі дербес зейнеткерлерді әлеуметтік қолдау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-02-24
approved_by:
- '163004000001'
version_date:
  kaz: 2005-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/23427/kaz/24.02.2005
