act_code: '175948'
requisite: Решение Мангистауского областного маслихата от 9 декабря 2022 года № 16/175
title:
  rus: Об областном бюджете на 2023 - 2025 годы
  kaz: 2023-2025 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-09
approved_by:
- '163000000002'
version_date:
  kaz: 2023-09-27
  rus: 2023-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/175948/kaz/27.09.2023
  rus: https://zan.gov.kz/client/#!/doc/175948/rus/27.09.2023
caused_by:
  code: '186755'
  requisite: Решение Мангистауского областного маслихата от 27 сентября 2023 года № 5/42
  title:
    rus: О внесении изменений и дополнения в решение Мангистауского областного маслихата от 9 декабря 2022 года № 16/175 «Об областном бюджете на 2023 - 2025 годы»
    kaz: Маңғыстау облыстық мәслихатының 2022 жылғы 9 желтоқсандағы № 16/175 «2023 - 2025 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186755/rus
