act_code: '41478'
requisite: Маңғыстау облысы Қарақия ауданы Құрық ауылы әкімінің 2008 жылғы 20 тамыздағы № 91 шешімі. Маңғыстау облысы Әділет департаментінде 2008 жылғы 08 қыркүйекте № 11-4-65 болып тіркелді
title:
  rus: Құрық ауылы аумағынан жаңа тұрғын үй құрылысын салу үшін дайындалған жерге атау беру туралы
  kaz: Құрық ауылы аумағынан жаңа тұрғын үй құрылысын салу үшін дайындалған жерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-20
approved_by:
- '163005006002'
version_date:
  kaz: 2016-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/41478/kaz/05.12.2016
caused_by:
  code: '109146'
  requisite: Решение акима села Курык Каракиянского района Мангистауской области от 5 декабря 2016 года № 541. Зарегистрировано Департаментом юстиции Мангистауской области 10 января 2017 года № 3241
  title:
    rus: О внесении изменений и дополнений в решение акима села Курык от 20 августа 2008 года № 91 "О присвоении наименования территории подготовленные для строительства нового жилья села Курык"
    kaz: '"Құрық селосы әкімінің 2008 жылғы 20 тамыздағы № 91 "Құрық селосы аумағынан жаңа тұрғын үй құрылысын салу үшін дайындалған жерге атау беру туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/109146/rus
