act_code: '41467'
requisite: Түпқараған ауданы Ақшұқыр селосы әкімінің 2008 жылғы 30 маусымдағы № 887 а шешімі. Түпқараған ауданының әділет басқармасында 2008 жылғы 13 тамызда № 11-6-65 тіркелді
title:
  rus: Ақшұқыр ауылынан жаңадан пайда болған көшелерге есімдер беру туралы
  kaz: Ақшұқыр ауылынан жаңадан пайда болған көшелерге есімдер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-30
approved_by:
- '163006003001'
version_date:
  kaz: 2008-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/41467/kaz/30.06.2008
