act_code: '94014'
requisite: Решение Актауского городского маслихата Мангистауской области от 25 августа 2015 года № 33/308. Зарегистрировано Департаментом юстиции Мангистауской области от 30 сентября 2015 года № 2838. Утратило силу - решением Актауского городского маслихата Мангистауской области от 05 февраля 2016 года № 37/365
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-08-25
approved_by:
- '163002000002'
version_date:
  kaz: 2015-08-25
  rus: 2015-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/94014/kaz/25.08.2015
  rus: https://zan.gov.kz/client/#!/doc/94014/rus/25.08.2015
