act_code: '194881'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 26 марта 2024 года № 14/120. Зарегистрировано Департаментом юстиции Мангистауской области 28 марта 2024 года № 4679-12. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 11 октября 2024 года № 20/151
title:
  rus: Об установлении размера дополнительной социальной помощи отдельным категориям граждан Бейнеуского района к 35-летию вывода ограниченного контингента советских войск из Демократической Республики Афганистан
  kaz: Ауғанстан Демократиялық Республикасынан Кеңес әскерлерінің шектеулі контингентін шығаруының 35-жылдығына Бейнеу ауданы азаматтарының жекелеген санаттарына қосымша әлеуметтік көмектің мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-26
approved_by:
- '163007000002'
version_date:
  kaz: 2024-03-26
  rus: 2024-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/194881/kaz/26.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194881/rus/26.03.2024
