act_code: '196157'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 25 апреля 2024 года № 16/137. Зарегистрировано Департаментом юстиции Мангистауской области 29 апреля 2024 года № 4705-12
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Жанаозен
  kaz: Жаңаөзен қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алудың тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-25
approved_by:
- '163003000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/196157/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196157/rus/25.04.2024
