act_code: '56697'
requisite: Решение Мангистауского областного маслихата № 29/336 от 13 декабря 2010 года. Зарегистрировано Департаментом юстиции Мангистауской области № 2092 от 13 января 2011 года
title:
  rus: О схеме зонирования земель пригородной зоны города Актау Мангистауской области
  kaz: Маңғыстау облысы Ақтау қаласының қаламаңы аймағының жерлерін аймақтарға бөлу схемасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/56697/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56697/rus/13.12.2010
