act_code: '203550'
requisite: Решение Мангистауского областного маслихата от 28 ноября 2024 года № 16/172. Зарегистрировано Департаментом юстиции Мангистауской области 3 декабря 2024 года № 4748-12.
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами из поверхностных источников на 2024 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша 2024 жылға арналған жер үстi көздерiндегі су ресурстарын пайдаланғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-28
approved_by:
- '163000000002'
version_date:
  kaz: 2024-11-28
  rus: 2024-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/203550/kaz/28.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203550/rus/28.11.2024
