act_code: '97894'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2015 года № 29/435. Зарегистрировано Департаментом юстиции Мангистауской области от 21 января 2016 года № 2955. Утратило силу решением Мангистауского областного маслихата от 16 февраля 2026 года № 25/298 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах общего водопользования в Мангистауской области
  kaz: Маңғыстау облысында ортақ су пайдаланудың Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2018-05-30
  rus: 2018-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/97894/kaz/30.05.2018
  rus: https://zan.gov.kz/client/#!/doc/97894/rus/30.05.2018
caused_by:
  code: '122846'
  requisite: Решение Мангистауского областного маслихата от 30 мая 2018 года № 19/236. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2018 года № 3653. Утратило силу решением Мангистауского областного маслихата от 16 февраля 2026 года № 25/298 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения и дополнения в решение областного маслихата от 10 декабря 2015 года № 29/435 «О Правилах общего водопользования в Мангистауской области»
    kaz: Облыстық мәслихаттың 2015 жылғы 10 желтоқсандағы № 29/435 «Маңғыстау облысында ортақ су пайдаланудың Қағидалары туралы» шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122846/rus
