act_code: '22911'
requisite: Маңғыстау облысы Ақтау қалалық мәслихатының 2004 жылғы 23 желтоқсандағы № 12/92 шешімі. Маңғыстау облыстық Әділет Департаментінде 2005 жылғы 4 ақпанда № 1849 тіркелді. Күші жойылды - Ақтау қалалық мәслихатының 2009 жылғы 20 шілдедегі № 21/203 шешімімен.
title:
  rus: Бiр жолғы материалдық көмек пен ай сайынғы үстеме ақы тағайындау мен көрсету Ережесiн бекiту туралы
  kaz: Бiр жолғы материалдық көмек пен ай сайынғы үстеме ақы тағайындау мен көрсету Ережесiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-23
approved_by:
- '163002000002'
version_date:
  kaz: 2005-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/22911/kaz/24.03.2005
