act_code: '56866'
requisite: Решение Жанаозенского городского маслихата Мангистауской области № 34/257 от 22 декабря 2010 года. Зарегистрировано Департаментом юстиции Мангистауской области Управлением юстиции города  Жанаозен от 18 января 2011 года № 11-2-156. Утратило силу решением маслихата города Жанаозен Мангистауской области от 25 июня 2012 года № 6/59
title:
  rus: Правила о порядке и размере оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібі жөніндегі Қағида туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '163003000002'
version_date:
  kaz: 2010-12-22
  rus: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56866/kaz/22.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56866/rus/22.12.2010
