act_code: '43852'
requisite: Қарақия аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 11/88 шешімі. Қарақия ауданының Әділет басқармасында 2009 жылғы 8 қаңтарда № 11-4-71 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2011 жылғы 1 ақпандағы № 34/242 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '163005000002'
version_date:
  kaz: 2009-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/43852/kaz/21.04.2009
caused_by:
  code: '45603'
  requisite: Маңғыстау облысы Қарақия аудандық мәслихатының 2009 жылғы 21 сәуірдегі № 14/118 шешемі. Қарақия ауданының Әділет басқармасында 2009 жылғы 28 сәуірде № 11-4-84 тіркелді. Күші жойылды-Маңғыстау облысы Қарақия аудандық мәслихатының 2011 жылғы 1 ақпандағы № 34/242 шешімімен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 19 желтоқсандағы N 11/88 "2009 жылға арналаған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 19 желтоқсандағы N 11/88 "2009 жылға арналаған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45603/rus
