act_code: '43852'
requisite: Қарақия аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 11/88 шешімі. Қарақия ауданының Әділет басқармасында 2009 жылғы 8 қаңтарда № 11-4-71 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2011 жылғы 1 ақпандағы № 34/242 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '163005000002'
version_date:
  kaz: 2009-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/43852/kaz/06.02.2009
