act_code: '207924'
requisite: Решение акима села Кызылсай города Жанаозен Мангистауской области от 4 марта 2025 года № 09
title:
  rus: Акционерное общество «QAZAQGAZ AIMAQ» об установлении публичного сервитута
  kaz: «QAZAQGAZ AIMAQ» акционерлік қоғамына қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-04
approved_by:
- '163003002001'
version_date:
  kaz: 2025-03-04
  rus: 2025-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/207924/kaz/04.03.2025
  rus: https://zan.gov.kz/client/#!/doc/207924/rus/04.03.2025
