act_code: '25382'
requisite: Решение акима Мангистауской области от 23 августа 2005 года № 6. Зарегистрировано Департаментом юстиции Мангистауской области 22 сентября 2005 года № 1918
title:
  rus: Об организации и проведении начальной военной подготовки с учащимися допризывного и призывного возрастов в организациях образования Мангистауской области в 2005-2006 учебном году
  kaz: Маңғыстау облысының бiлiм беру ұйымдарында әскерге шақырылғанға дейiнгi және әскерге шақыру жасындағы оқушылардың 2005-2006 оқу жылындағы бастапқы әскери даярлығын ұйымдастыру және оны өткiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-08-23
approved_by:
- '163000000001'
version_date:
  kaz: 2005-08-23
  rus: 2005-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/25382/kaz/23.08.2005
  rus: https://zan.gov.kz/client/#!/doc/25382/rus/23.08.2005
