act_code: '221221'
requisite: Решение акима села Есет Бейнеуского района Мангистауской области от 12 января 2026 года № 1
title:
  rus: О присвоение наименований безымянным улицам села Есет
  kaz: Есет ауылының атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-12
approved_by:
- '163007002002'
version_date:
  kaz: 2026-01-12
  rus: 2026-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/221221/kaz/12.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221221/rus/12.01.2026
