act_code: '206053'
requisite: Решение Актауского городского маслихата Мангистауской области от 5 января 2025 года № 18/120
title:
  rus: О бюджете села Умирзак на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Өмірзақ ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '163002000002'
version_date:
  kaz: 2025-01-05
  rus: 2025-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/206053/kaz/05.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206053/rus/05.01.2025
