act_code: '107462'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/52. Зарегистрировано Департаментом юстиции Мангистауской области от 11 ноября 2016 года № 3176. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 16 апреля 2024 года № 11/84
title:
  rus: Об утверждении Правил оказания социальной  помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском  районе
  kaz: Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін  белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '163004000002'
version_date:
  kaz: 2022-10-03
  rus: 2022-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/107462/kaz/03.10.2022
  rus: https://zan.gov.kz/client/#!/doc/107462/rus/03.10.2022
caused_by:
  code: '173068'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 3 октября 2022 года № 16/160. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 октября 2022 года № 30217. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 16 апреля 2024 года № 11/84
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 21 октября 2016 года № 5/52 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2016 жылғы 21 қазандағы № 5/52 «Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173068/rus
