act_code: '176652'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 22 декабря 2022 года № 26/161
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '163008000002'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/176652/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176652/rus/06.12.2023
caused_by:
  code: '189856'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 6 декабря 2023 года № 9/56
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 22 декабря 2022 года № 26/161 «О районном бюджете на 2023 - 2025 годы»
    kaz: Мұнайлы аудандық мәслихатының 2022 жылғы 22 желтоқсандағы № 26/161 «2023 - 2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189856/rus
