act_code: '30931'
requisite: Решение Мангистауского областного Маслихата от 12 декабря 2006 года № 19/347. Зарегистрировано Департаментом юстиции Мангистауской области 28 декабря 2006 года № 1962
title:
  rus: Об областном бюджете на 2007 год
  kaz: 2007 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '163000000002'
version_date:
  kaz: 2007-10-08
  rus: 2007-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/30931/kaz/08.10.2007
  rus: https://zan.gov.kz/client/#!/doc/30931/rus/08.10.2007
caused_by:
  code: '35502'
  requisite: Решение маслихата Мангистауской области от 8 октября 2007 года № 2/15. Зарегистрировано Департаментом юстиции Мангистауской области 24 октября 2007 года № 1979
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 12 декабря 2006 года № 19/347 "Об областном бюджете на 2007 год"
    kaz: '"2007 жылға арналған облыстық бюджет туралы" облыстық мәслихаттың 2006 жылғы 12 желтоқсандағы № 19/347 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/35502/rus
