act_code: '30931'
requisite: Решение Мангистауского областного Маслихата от 12 декабря 2006 года № 19/347. Зарегистрировано Департаментом юстиции Мангистауской области 28 декабря 2006 года № 1962
title:
  rus: Об областном бюджете на 2007 год
  kaz: 2007 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '163000000002'
version_date:
  kaz: 2007-07-21
  rus: 2007-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/30931/kaz/21.07.2007
  rus: https://zan.gov.kz/client/#!/doc/30931/rus/21.07.2007
