act_code: '105176'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 июня 2016 года № 3/25. Зарегистрировано Департаментом юстиции Мангистауской области от 4 августа 2016 года № 3112. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 5 февраля 2019 года № 32/267
title:
  rus: О  внесении  изменений  в  решение  Бейнеуского  районного  маслихата  от  28  декабря  2015  года  №38/273 «Об  утверждении  тарифов  на  сбор,  вывоз,  захоронение  и  утилизацию    коммунальных  отходов  по  Бейнеускому  району»
  kaz: Бейнеу  аудандық  мәслихатының  2015  жылғы  28  желтоқсандағы  №38/273  «Бейнеу  ауданы  бойынша коммуналдық  қалдықтарды  жинау,  әкету,  көму  және  кәдеге  жарату  тарифтерін  бекіту  туралы»  шешіміне  өзгерістер  енгізу  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-23
approved_by:
- '163007000002'
version_date:
  kaz: 2016-06-23
  rus: 2016-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/105176/kaz/23.06.2016
  rus: https://zan.gov.kz/client/#!/doc/105176/rus/23.06.2016
