act_code: '220297'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 22 декабря 2025 года № 39/218
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '163008000002'
version_date:
  kaz: 2026-08-26
  rus: 2026-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/220297/kaz/26.08.2026
  rus: https://zan.gov.kz/client/#!/doc/220297/rus/26.08.2026
caused_by:
  code: '229749'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 26 августа 2026 года № 44/253
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 22 декабря 2025 года № 39/218 «О районном бюджете на 2026-2028 годы»
    kaz: Мұнайлы аудандық мәслихатының 2025 жылғы 22 желтоқсандағы № 39/218 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229749/rus
