act_code: '76022'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 19 ноября 2013 года № 16/166, зарегистрировано Департаментом юстиции Мангистауской области 13 декабря 2013 года № 2320. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 16 апреля 2021 года № 3/21
title:
  rus: Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мунайлинском районе
  kaz: Мұнайлы ауданында әлеуметтік көмек мөлшерін, мұқтаж азаматтар санаттарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-19
approved_by:
- '163008000002'
version_date:
  kaz: 2017-08-11
  rus: 2017-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/76022/kaz/11.08.2017
  rus: https://zan.gov.kz/client/#!/doc/76022/rus/11.08.2017
caused_by:
  code: '114348'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 11 августа 2017 года № 11/169. Зарегистрировано Департаментом юстиции Мангистауской области 28 августа 2017 года № 3414. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 16 апреля 2021 года № 3/21
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 19 ноября 2013 года № 16/166 "Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мунайлинском районе"
    kaz: Мұнайлы аудандық мәслихатының 2013 жылғы 19 қарашадағы № 16/166 "Мұнайлы ауданында әлеуметтік көмек мөлшерін, мұқтаж азаматтар санаттарының тізімін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114348/rus
