act_code: '174495'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 23 ноября 2022 года № 19/117. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2022 года № 30813
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Тупкараганском районе
  kaz: Түпқараған ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-23
approved_by:
- '163006000002'
version_date:
  kaz: 2022-11-23
  rus: 2022-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/174495/kaz/23.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174495/rus/23.11.2022
