act_code: '24374'
requisite: Решение маслихата Мангистауской области от 30 мая 2005 года № 11/198. Зарегистрировано Департаментом юстиции Мангистауской области 13 июня 2005 года № 1913
title:
  rus: Об организации и проведении призыва граждан на срочную военную службу в апреле-июне и октябре-декабре 2005 года
  kaz: 2005 жылдың сәуір-маусым және қазан-желтоқсан айларында азаматтарды мерзiмдi әскери қызметке шақыруды ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-05-30
approved_by:
- '163000000002'
version_date:
  kaz: 2005-05-30
  rus: 2005-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/24374/kaz/30.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24374/rus/30.05.2005
