act_code: '97949'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2015 года № 29/445. Зарегистрировано Департаментом юстиции Мангистауской области от 19 января 2016 года № 2945. Утратило силу решением Мангистауского областного маслихата от 28 мая 2021 года № 3/51
title:
  rus: О Правилах содержания животных на территории населенных пунктов Мангистауского района
  kaz: Маңғыстау ауданының елді мекендерінің аумағында жануарларды асырау  Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2015-12-10
  rus: 2015-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/97949/kaz/10.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97949/rus/10.12.2015
