act_code: '61147'
requisite: Решение акима села Мангистау акимата Мунайлинского района Мангистауской области от 31 октября 2011 года № 170. Зарегистрировано Управлением юстиции Мунайлинского района Департамента юстиции Мангистауской области 3 ноября 2011 года № 11-7-102
title:
  rus: О присвоении наименования улиц
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-31
approved_by:
- '163008007001'
version_date:
  kaz: 2011-10-31
  rus: 2011-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/61147/kaz/31.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61147/rus/31.10.2011
