act_code: '155349'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 16 апреля 2021 года № 3/21. Зарегистрировано Департаментом юстиции Мангистауской области 27 апреля 2021 года № 4503. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 23 октября 2023 года № 6/41
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мунайлинском районе
  kaz: Мұнайлы ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-16
approved_by:
- '163008000002'
version_date:
  kaz: 2022-10-06
  rus: 2022-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/155349/kaz/06.10.2022
  rus: https://zan.gov.kz/client/#!/doc/155349/rus/06.10.2022
caused_by:
  code: '173110'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 6 октября 2022 года № 23/143. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 октября 2022 года № 30267. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 23 октября 2023 года № 6/41
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 16 апреля 2021 года № 3/21 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мұнайлы аудандық мәслихатының 2021 жылғы 16 сәуірдегі № 3/21 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173110/rus
