act_code: '109142'
requisite: Решение Актауского городского маслихата Мангистауской области от 9 декабря 2016 года № 6/73. Зарегистрировано Департаментом юстиции Мангистауской области 19 января 2017 года № 3258. Утратило силу решением Актауского городского маслихата Мангистауской области от 15 июня 2020 года № 32/372
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственным служащим государственного учреждения "Аппарат Актауского городского маслихата" и его описания
  kaz: '"Ақтау қалалық мәслихатының аппараты" мемлекеттік мекемесінің мемлекеттік қызметшілеріне қызметтік куәлігін беру қағидаларын және оның сипаттамасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163002000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/109142/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109142/rus/09.12.2016
