act_code: '108995'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 9 декабря 2016 года № 6/64. Зарегистрировано Департаментом юстиции Мангистауской области 13 января 2017 года № 3254. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 15 июня 2020 года № 41/413
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственного учреждения "Аппарат Каракиянского районного маслихата" и его описания
  kaz: '"Қарақия аудандық мәслихатының аппараты" мемлекеттік мекемесінің қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163005000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/108995/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108995/rus/09.12.2016
