act_code: '101748'
requisite: Маңғыстау облысы Маңғыстау аудандық мәслихатының 2016 жылғы 28 сәуірдегі № 2/20 шешімі
title:
  rus: Маңғыстау аудандық Мәслихатының 2009 жылғы 10 ақпандағы №11/137 «Ойын бизнесі түрлерінен алынатын  базалық салық ставкаларының мөлшері  туралы» шешімінің күші  жойылды  деп тану туралы
  kaz: Маңғыстау аудандық Мәслихатының 2009 жылғы 10 ақпандағы №11/137 «Ойын бизнесі түрлерінен алынатын  базалық салық ставкаларының мөлшері  туралы» шешімінің күші  жойылды  деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-28
approved_by:
- '163004000002'
version_date:
  kaz: 2016-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/101748/kaz/28.04.2016
