act_code: '138991'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 января 2020 года № 45/364. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2020 года № 4121
title:
  rus: О бюджете села Сарга на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Сарға ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163007000002'
version_date:
  kaz: 2020-10-22
  rus: 2020-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/138991/kaz/22.10.2020
  rus: https://zan.gov.kz/client/#!/doc/138991/rus/22.10.2020
caused_by:
  code: '147834'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 22 октября 2020 года № 55/440. Зарегистрировано Департаментом юстиции Мангистауской области 27 октября 2020 года № 4326
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 13 января  2020 года № 45/364 «О бюджете села Сарга на 2020 – 2022 годы»
    kaz: Бейнеу аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 45/364 «2020 - 2022 жылдарға арналған Сарға ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147834/rus
