act_code: '132194'
requisite: Решение Мангистауского областного маслихата от 30 мая 2019 года № 27/328. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2019 года № 3918
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников на 2019 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша 2019 жылға арналған жер үстi көздерiндегі су ресурстарын пайдаланғаны үшін төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-30
approved_by:
- '163000000002'
version_date:
  kaz: 2019-05-30
  rus: 2019-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/132194/kaz/30.05.2019
  rus: https://zan.gov.kz/client/#!/doc/132194/rus/30.05.2019
