act_code: '138808'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 13 января 2020 года № 38/298. Зарегистрировано Департаментом юстиции Мангистауской области 20 января 2020 года № 4112
title:
  rus: О бюджете города районного значения, сел, сельского округа на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163006000002'
version_date:
  kaz: 2020-05-14
  rus: 2020-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/138808/kaz/14.05.2020
  rus: https://zan.gov.kz/client/#!/doc/138808/rus/14.05.2020
caused_by:
  code: '142884'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 14 мая 2020 года № 43/329. Зарегистрировано Департаментом юстиции Мангистауской области 15 мая 2020 года № 4210
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 13 января 2020 года № 38/298 «О бюджете города районного значения, сел, сельского округа на 2020 - 2022 годы»
    kaz: Түпқараған аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 38/298 «2020 - 2022 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142884/rus
