act_code: '14524'
requisite: Решение акима  Мангистауской области от 29 января 2003 года № 4. Зарегистрировано Управлением юстиции Мангистауской области 12 февраля 2003 года № 1366
title:
  rus: Об утверждении Правил организации санаторно -  курортного лечения участников и инвалидов Великой Отечественной войны
  kaz: Ұлы Отан соғысының қатысушылары мен мүгедектерін санаториялық-курорттық емдеуді ұйымдастыру Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-01-29
approved_by:
- '163000000003'
version_date:
  kaz: 2003-01-29
  rus: 2003-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/14524/kaz/29.01.2003
  rus: https://zan.gov.kz/client/#!/doc/14524/rus/29.01.2003
