act_code: '41904'
requisite: Маңғыстау облысы Маңғыстау ауданы мәслихатының 2008 жылғы 3 қыркүйектегі № 7/74 шешімі. Маңғыстау облысы Әділет департаменті Маңғыстау  ауданының әділет басқармасында 2008 жылғы 7 қазанда № 11-5-59 болып тіркелді
title:
  rus: Ойын бизнесі саласындағы субьектілер үшін салық ставкаларының мөлшері туралы
  kaz: Ойын бизнесі саласындағы субьектілер үшін салық ставкаларының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-03
approved_by:
- '163004000002'
version_date:
  kaz: 2008-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/41904/kaz/03.09.2008
