act_code: '95965'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 3 ноября 2015 года № 36/259. Зарегистрировано Департаментом юстиции Мангистауской области от 3 декабря 2015 года № 2896. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 18 января 2016 года № 40/281
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Бейнеуского районного маслихата»
  kaz: «Бейнеу  аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-03
approved_by:
- '163007000002'
version_date:
  kaz: 2015-11-03
  rus: 2015-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/95965/kaz/03.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95965/rus/03.11.2015
