act_code: '52059'
requisite: Маңғыстау облысы Бейнеу ауданы әкімдігі Бейнеу селосы әкімінің 2010 жылғы 18 қаңтардағы № 13 шешімі. Маңғыстау облысы Бейнеу ауданының Әділет басқармасында 2010 жылғы 11 ақпанда № 11-3-96 тіркелді
title:
  rus: Көше атын өзгерту туралы
  kaz: Көше атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-18
approved_by:
- '163007011001'
version_date:
  kaz: 2009-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52059/kaz/14.12.2009
