act_code: '138993'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 января 2020 года № 45/363. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2020 года № 4119
title:
  rus: О бюджете Самского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Сам ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163007000002'
version_date:
  kaz: 2020-12-14
  rus: 2020-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/138993/kaz/14.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138993/rus/14.12.2020
caused_by:
  code: '150288'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 14 декабря 2020 года № 57/463. Зарегистрировано Департаментом юстиции Мангистауской области 22 декабря 2020 года № 4393
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 13 января 2020 года № 45/363 «О бюджете Самского сельского округа на 2020 – 2022 годы»
    kaz: Бейнеу аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 45/363 «2020 – 2022 жылдарға арналған Сам ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150288/rus
