act_code: '49752'
requisite: Маңғыстау облысы Жаңаөзен қаласы әкімдігінің 2009 жылғы 21 желтоқсандағы № 25/163 шешімі. Жаңаөзен қаласының Әділет басқармасында 2009 жылғы 5 қаңтарда № 11-2-129 тіркелді
title:
  rus: 2010-2012 жылдарға арналған қалалық бюджет туралы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '163003000001'
version_date:
  kaz: 2010-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49752/kaz/30.11.2010
caused_by:
  code: '55854'
  requisite: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2010 жылғы 30 қарашадағы № 33/245 шешімі. Маңғыстау облысының Жаңаөзен қаласының Әділет басқармасында 2010 жылғы 8 желтоқсанда № 11-2-148 тіркелді
  title:
    rus: Жаңаөзен қалалық мәслихатының 2009 жылғы 21 желтоқсандағы "2010-2012 жылдарға арналған қалалық бюджет туралы" № 25/163 шешіміне өзгерістер енгізу туралы
    kaz: Жаңаөзен қалалық мәслихатының 2009 жылғы 21 желтоқсандағы "2010-2012 жылдарға арналған қалалық бюджет туралы" № 25/163 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55854/rus
