act_code: '224905'
requisite: Решение Мангистауского областного маслихата от 24 апреля 2026 года № 27/322. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 апреля 2026 года № 38593
title:
  rus: Об признании утратившими силу некоторых решений Мангистауского областного маслихата
  kaz: Маңғыстау облыстық маслихатының кейбір шешімдерінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-24
approved_by:
- '163000000002'
version_date:
  kaz: 2026-04-24
  rus: 2026-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/224905/kaz/24.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224905/rus/24.04.2026
