act_code: '17114'
requisite: Решение Мангистауского областного Маслихата от 12 сентября 2003 года № 28/309. Зарегистрировано Управлением юстиции Мангистауской области 22 сентября 2003 года № 1518
title:
  rus: О Региональной программе демографического развития Мангистауской области на 2003-2005 годы
  kaz: Маңғыстау облысының 2003-2005 жылдарға арналған Аймақтық демографиялық даму бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-11
approved_by:
- '163000000002'
version_date:
  kaz: 2003-09-11
  rus: 2003-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/17114/kaz/11.09.2003
  rus: https://zan.gov.kz/client/#!/doc/17114/rus/11.09.2003
