act_code: '46380'
requisite: Решение №15/165 от 07.05.2009, Маслихат Мунайлинского района
title:
  rus: Қызылтөбе селолық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
  kaz: Қызылтөбе селолық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-07
approved_by:
- '163008000002'
version_date:
  kaz: 2009-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/46380/kaz/08.05.2009
