act_code: '14985'
requisite: Решение маслихата Мангистауской области от 20 декабря 2002 года № 23/241. Зарегистрировано Управлением юстиции Мангистауской области 21 января 2002 года № 1308
title:
  rus: О региональной программе по снижению бедности в Мангистауской области на 2002-2005 годы
  kaz: Маңғыстау облысының кедейшілікті азайту жөніндегі 2003-2005 жылдарға арналған Аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-20
approved_by:
- '163000000002'
version_date:
  kaz: 2003-07-29
  rus: 2003-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/14985/kaz/29.07.2003
  rus: https://zan.gov.kz/client/#!/doc/14985/rus/29.07.2003
caused_by:
  code: '16830'
  requisite: Решение Мангистауского областного маслихата от 30 июля 2003 года № 27/294. Зарегистрировано в Управлении юстиции Мангистауской области от 23 августа 2003 года № 1506
  title:
    rus: О внесении изменений в решение областного маслихата от 20 декабря 2002 года № 23/241 "О Региональной программе по снижению бедности в Мангистауской области на 2003-2005 годы"
    kaz: '"Маңғыстау облысының кедейшілікті азайту жөніндегі 2003-2005 жылдарға арналған Аймақтық бағдарламасы туралы" облыстық мәслихаттың 2002 жылғы 20 желтоқсандағы № 23/241 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/16830/rus
