act_code: '155038'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 14 апреля 2021 года № 4/37. Зарегистрировано Департаментом юстиции Мангистауской области 22 апреля 2021 года № 4492
title:
  rus: Об утверждении проектов (схем) зонирования земель, границы оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Бейнеуского района
  kaz: Бейнеу ауданының елді мекендерінде жерді аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-14
approved_by:
- '163007000002'
version_date:
  kaz: 2021-04-14
  rus: 2021-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/155038/kaz/14.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155038/rus/14.04.2021
