act_code: '216926'
requisite: Решение акима села Жармыш Мангистауского района Мангистауской области от 7 ноября 2025 года № 16
title:
  rus: О писвоении наименований безымянным улицам села Жармыш
  kaz: Жармыш ауылының атауы жоқ көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-07
approved_by:
- '163004002001'
version_date:
  kaz: 2025-11-07
  rus: 2025-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/216926/kaz/07.11.2025
  rus: https://zan.gov.kz/client/#!/doc/216926/rus/07.11.2025
