act_code: '205504'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 23 декабря 2024 года № 17/126
title:
  rus: О районном бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '163004000002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205504/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205504/rus/23.12.2024
