act_code: '79659'
requisite: Решение маслихата Каракиянского района Мангистауской области от 24 апреля 2014 года № 18/196. Зарегистрировано Департаментом юстиции Мангистауской области 30 мая 2014 года № 2437. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 27 ноября 2020 года № 45/452
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества в Каракиянском районе
  kaz: Қарақия ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-24
approved_by:
- '163005000002'
version_date:
  kaz: 2014-04-24
  rus: 2014-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/79659/kaz/24.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79659/rus/24.04.2014
