act_code: '25398'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2005 жылғы 8 маусыдағы № 18/113 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2005 жылғы 5 тамызда № 11-6-12 болып тіркелді
title:
  rus: Түпқарған ауданында ара-тұра сипаттағы кәсіпкерлік қызметпен шұғылданатын жеке тұлғаларға берілетін біржолғы талондардың құны туралы
  kaz: Түпқарған ауданында ара-тұра сипаттағы кәсіпкерлік қызметпен шұғылданатын жеке тұлғаларға берілетін біржолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-06-08
approved_by:
- '163006000002'
version_date:
  kaz: 2005-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/25398/kaz/08.06.2005
