act_code: '139150'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 27 января 2020 года № 50/468. Зарегистрировано Департаментом юстиции Мангистауской области 29 января 2020 года № 4125
title:
  rus: О бюджетах сел, сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-27
approved_by:
- '163008000002'
version_date:
  kaz: 2020-04-08
  rus: 2020-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/139150/kaz/08.04.2020
  rus: https://zan.gov.kz/client/#!/doc/139150/rus/08.04.2020
caused_by:
  code: '141692'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 8 апреля 2020 года № 52/494. Зарегистрировано Департаментом юстиции Мангистауской области 15 апреля 2020 года № 4191
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 27 января 2020 года № 50/468 «О бюджете сел, сельских округов на 2020-2022 годы»
    kaz: Мұнайлы аудандық мәслихатының 2020 жылғы 27 қаңтардағы № 50/468 «2020-2022 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141692/rus
