act_code: '144504'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 25 июня 2020 года № 46/515. Зарегистрировано Департаментом юстиции Мангистауской области 7 июля 2020 года № 4251
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '163003000002'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/144504/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144504/rus/25.06.2020
