act_code: '206043'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 30 декабря 2024 года № 24/196
title:
  rus: О бюджете села Кызылсай на 2025 - 2027 годы
  kaz: 2025 – 2027 жылдарға арналған Қызылсай ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '163003000002'
version_date:
  kaz: 2025-03-26
  rus: 2025-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/206043/kaz/26.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206043/rus/26.03.2025
caused_by:
  code: '208841'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 26 марта 2025 года № 26/219
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 30 декабря 2024 года № 24/196 «О бюджете села Кызылсай на 2025 - 2027 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2024 жылғы 30 желтоқсандағы № 24/196 «2025 - 2027 жылдарға арналған Қызылсай ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208841/rus
