act_code: '18595'
requisite: Решение Мангистауского областного маслихата от 30 января 2004 года № 3/39. Зарегистрировано Департаментом юстиции Мангистауской области 13 февраля 2004 года № 1614
title:
  rus: О переводе делопроизводства на государственный язык в Мангистауской области
  kaz: Маңғыстау облысында іс жүргізуді мемлекеттік тілге көшіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-01-30
approved_by:
- '163000000002'
version_date:
  kaz: 2004-01-30
  rus: 2004-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/18595/kaz/30.01.2004
  rus: https://zan.gov.kz/client/#!/doc/18595/rus/30.01.2004
