act_code: '123984'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 20 июля 2018 года № 22/189. Зарегистрировано Департаментом юстиции Мангистауской области 3 августа 2018 года № 3698
title:
  rus: Об утверждении Регламента собрания местного сообщества города Форт-Шевченко
  kaz: Форт-Шевченко қаласының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-20
approved_by:
- '163006000002'
version_date:
  kaz: 2021-11-15
  rus: 2021-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/123984/kaz/15.11.2021
  rus: https://zan.gov.kz/client/#!/doc/123984/rus/15.11.2021
caused_by:
  code: '160313'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 15 ноября 2021 года № 8/53
  title:
    rus: О внесений изменений в решение Тупкараганского районного маслихата от 20 июля 2018 года № 22/189 «Об утверждении Регламента собрания местного сообщества города Форт-Шевченко»
    kaz: Түпқараған аудандық мәслихатының 2018 жылғы 20 шілдедегі № 22/189 «Форт-Шевченко қаласының жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160313/rus
