act_code: '53166'
requisite: Маңғыстау облысы Бейнеу ауданы әкімінің 2009 жылғы 24 желтоқсандағы № 6 шешімі. Маңғыстау облысы Бейнеу ауданының Әділет басқармасында 2010 жылғы 10 қаңтарда № 11-3-95 тіркелді
title:
  rus: 2010 жылдың қаңтар-наурызында Азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 2010 жылдың қаңтар-наурызында Азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '163007000001'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53166/kaz/24.12.2009
