act_code: '121883'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 2 мая 2018 года № 22/191. Зарегистрировано Департаментом юстиции Мангистауской области 21 мая 2018 года № 3609
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Бейнеускому району на 2018-2019 годы
  kaz: Бейнеу ауданы бойынша 2018-2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-02
approved_by:
- '163007000002'
version_date:
  kaz: 2018-05-02
  rus: 2018-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/121883/kaz/02.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121883/rus/02.05.2018
