act_code: '44180'
requisite: Маңғыстау облысы Мұнайлы ауданы әкімдігінің 2008 жылғы 25 желтоқсандағы № 61 шешімі. Маңғыстау облысының Әділет департаменті Мұнайлы ауданының Әділет басқармасында 2009 жылғы 23 қаңтарда № 11-7-31 тіркелді
title:
  rus: Ақтау қаласы қорғаныс істері жөніндегі басқармасының шақыру учаскесіне тіркеуге алуды ұйымдастыру жөніндегі шаралар туралы
  kaz: Ақтау қаласы қорғаныс істері жөніндегі басқармасының шақыру учаскесіне тіркеуге алуды ұйымдастыру жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '163008000001'
version_date:
  kaz: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/44180/kaz/25.12.2008
