act_code: '43538'
requisite: Маңғыстау облысы Маңғыстау аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 10/121 шешімі. Маңғыстау облысының Әділет департаменті Маңғыстау ауданының Әділет басқармасында 2009 жылғы 8 қаңтарда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 11-5-64 болып енгізілді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '163004000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43538/kaz/19.12.2008
