act_code: '21791'
requisite: Решение Мангистауского областного маслихата от 27 октября 2004 года № 7/113. Зарегистрировано Департаментом юстиции Мангистауской области 8 ноября 2004 года № 1773
title:
  rus: О ставках платы за побочные лесные пользования
  kaz: Орманды жанама пайдаланғаны үшін төленетін төлем мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-10-26
approved_by:
- '163000000002'
version_date:
  kaz: 2004-10-26
  rus: 2004-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/21791/kaz/26.10.2004
  rus: https://zan.gov.kz/client/#!/doc/21791/rus/26.10.2004
