act_code: '53502'
requisite: Решение маслихата города Актау Мангистауской области от 4 июня 2010 года № 33/295. Зарегистрировано Управлением юстиции города Актау Мангистауской области 14 июля 2010 года № 11-1-137. Утратило силу решением маслихата города Актау Мангистауской области от 12 сентября 2012 года № 6/62
title:
  rus: О размере и порядке оказания жилищной помощи малообеспеченным семьям (гражданам)
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға)тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-04
approved_by:
- '163002000002'
version_date:
  rus: 2012-04-24
source:
  rus: https://zan.gov.kz/client/#!/doc/53502/rus/24.04.2012
caused_by:
  code: '65743'
  requisite: Решение маслихата города Актау Мангистауской области от 24 апреля 2012 года № 3/35. Зарегистрировано Департаментом юстиции Мангистауской области 29 мая 2012 года № 11-1-179. Утратило силу решением маслихата города Актау Мангистауской области от 12 сентября 2012 года № 6/62
  title:
    rus: О внесении изменений в решение городского маслихата от 4 июня 2010 года № 33/295 "О размере и порядке оказания жилищной помощи малообеспеченным семьям (гражданам)"
    kaz: Қалалық мәслихаттың 2010 жылғы 4 маусымдағы № 33/295 "Аз қамтамасыз етілген отбасыларға (азаматтарға)тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65743/rus
