act_code: '161829'
requisite: Решение Мангистауского областного маслихата от 3 декабря 2021 года № 8/81. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25851
title:
  rus: Об определении перечня социально значимых автомобильных сообщений, подлежащих субсидированию в 2022 - 2024 годах по городу Жанаозен
  kaz: Жаңаөзен қаласы бойынша 2022 - 2024 жылдарда субсидиялауға жататын әлеуметтік маңызы бар автомобиль қатынастарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-03
approved_by:
- '163000000002'
version_date:
  kaz: 2021-12-03
  rus: 2021-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/161829/kaz/03.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161829/rus/03.12.2021
