act_code: '53172'
requisite: Маңғыстау облысы Бейнеу ауданы әкімдігі Бейнеу селосы әкімінің 2010 жылғы 18 қаңтардағы № 13 шешімі. Маңғыстау облысы Бейнеу ауданының Әділет басқармасында 2010 жылғы 11 ақпанда № 11-3-96 тіркелді
title:
  rus: Көше атын өзгерту туралы
  kaz: Көше атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-18
approved_by:
- '163007011001'
version_date:
  kaz: 2018-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/53172/kaz/06.03.2018
caused_by:
  code: '119594'
  requisite: Решение акима села Бейнеу Бейнеуского района Мангистауской области от 6 марта 2018 года № 245. Зарегистрировано Департаментом юстиции Мангистауской области 16 марта 2018 года № 3542
  title:
    rus: О внесении изменений в некоторые решения акима села Бейнеу
    kaz: Бейнеу ауылы әкімінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119594/rus
