act_code: '23637'
requisite: Постановление акимата Мангистауской области от 30 марта  2005 года № 115. Зарегистрировано Департаментом юстиции Мангистауской области 15 апреля 2005 года № 1901. Утратило силу по истечению срока действия - письмом руководителя аппарата акима  Мангистауской области от 25 июня 2008 года № 08-12-985
title:
  rus: Введении смотра готовности объектов снабжения, канализации, пищевых объектов, рынков к работе в весенне - летний период и санитарной очистке и благоустройству территорий ценных мест Мангистауской области
  kaz: Сумен жабдықтау, канализация, сауда, қоғамдық тамақтандыру және тамақ өнеркәсібі объектілерінің базарлардың көктемгі-жазғы сына әзірлігі мен Маңғыстау облысының елді мекендерінің санитарлық тазартылуы мен абаттандырылуы бойынша байқау өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-30
approved_by:
- '163000000001'
version_date:
  kaz: 2005-03-30
  rus: 2005-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/23637/kaz/30.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23637/rus/30.03.2005
