act_code: '62486'
requisite: Решение акима Тупкараганского района Мангистауской области от 27 декабря 2011 года № 18. Зарегистрировано Департаментом юстиции Мангистауской области 05 января 2012 года № 11-6-144. Утратило силу решением акима Тупкараганского района Мангистауской области от 08 июля 2015 года № 17
title:
  rus: Об образовании избирательных участков по Тупкараганскому району
  kaz: Түпқараған ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-26
approved_by:
- '163006000001'
version_date:
  rus: 2011-12-27
source:
  rus: https://zan.gov.kz/client/#!/doc/62486/rus/27.12.2011
