act_code: '144507'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 26 июня 2020 года № 45/336. Зарегистрировано Департаментом юстиции Мангистауской области 7 июля 2020 года № 4252. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 26 сентября 2022 года № 17/104
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения в Тупкараганском районе
  kaz: Түпқараған ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-26
approved_by:
- '163006000002'
version_date:
  kaz: 2020-06-26
  rus: 2020-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/144507/kaz/26.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144507/rus/26.06.2020
