act_code: '3282'
requisite: Решение акима  Мангистауской области от 31 мая 1999 года № 125. Зарегистрировано Управлением юстиции Мангистауской области 14 июня 1999 года № 78. Утратило силу решением акима  Мангистауской области от 27 августа 2003 года № 107
title:
  rus: Об утверждении «Временной методики по определению платы за загрязнение природной среды природопользователями Мангистауской области»
  kaz: '"Маңғыстау облысы табиғатты пайдаланушыларының қоршаған ортаны ластағаны үшін төлейтін төлемдерін анықтаудың уақытша әдістемесін" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-30
approved_by:
- '163000000003'
version_date:
  kaz: 1999-05-30
  rus: 1999-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/3282/kaz/30.05.1999
  rus: https://zan.gov.kz/client/#!/doc/3282/rus/30.05.1999
