act_code: '122698'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 25 мая 2018 года № 23/279. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2018 года № 3657
title:
  rus: Об утверждении регламента собрания местного сообщества села Мангистау
  kaz: Маңғыстау ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-25
approved_by:
- '163008000002'
version_date:
  kaz: 2021-11-03
  rus: 2021-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/122698/kaz/03.11.2021
  rus: https://zan.gov.kz/client/#!/doc/122698/rus/03.11.2021
caused_by:
  code: '160232'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 3 ноября 2021 года № 11/68
  title:
    rus: О внесении изменения в решение Мунайлинского районного маслихата от 25 мая 2018 года № 23/279 «Об утверждении регламента собрания местного сообщества села Мангистау»
    kaz: Мұнайлы аудандық мәслихатының 2018 жылғы 25 мамырдағы № 23/279 «Маңғыстау ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160232/rus
