act_code: '636'
requisite: Решение акима Мангистауской области от 2 февраля 1998 года № 60. Зарегистрировано Управлением юстиции Мангистауской области 6 апреля 1998 года № 6. Утратило силу решением акима Мангистауской области от 18 января 1999 года № 320
title:
  rus: Об утверждении ставок нормативных экологических платежей в Фонд охраны природы областного бюджета на 1998 год
  kaz: 1998 жылға арналған облыстық бюджеттің табиғат қорғау қорына нормативтік экологиятық төлемдер ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-02
approved_by:
- '163000000003'
version_date:
  kaz: 1998-02-02
  rus: 1998-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/636/kaz/02.02.1998
  rus: https://zan.gov.kz/client/#!/doc/636/rus/02.02.1998
