act_code: '67089'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 24 июля 2012 года № 5/44. Зарегистрировано Департаментом юстиции Мангистауской области 15 августа 2012 года № 11-5-135.  Утратило силу решением Мангистауского районного маслихата Мангистауской области от 1 августа 2018 года № 18/192
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам)
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегiн көрсету Қағидасын бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-24
approved_by:
- '163004000002'
version_date:
  kaz: 2013-04-29
  rus: 2013-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/67089/kaz/29.04.2013
  rus: https://zan.gov.kz/client/#!/doc/67089/rus/29.04.2013
caused_by:
  code: '72716'
  requisite: Решение маслихата Мангистауского района Мангистауской области от 29 апреля 2013 года № 9/81. Зарегистрировано Департаментом юстиции Мангистауской области 23 мая 2013 года № 2245. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 1 августа 2018 года № 18/192
  title:
    rus: О внесении изменений и дополнения в решение Мангистауского районного маслихата от 24 июля 2012 года № 5/44 "Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам)"
    kaz: Маңғыстау аудандық мәслихатының 2012 жылғы 24 шілдедегі № 5/44 "Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72716/rus
