act_code: '174485'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 ноября 2022 года № 17/174. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2022 года № 30818
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Мангистаускому району
  kaz: Маңғыстау ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-21
approved_by:
- '163004000002'
version_date:
  kaz: 2022-11-21
  rus: 2022-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/174485/kaz/21.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174485/rus/21.11.2022
