act_code: '104096'
requisite: Маңғыстау облысы Шебір селолық округі әкімінің  2016 жылғы 19  мамырдағы  № 26 қаулысы
title:
  rus: Шебір ауылдық  округі әкімінің 2010 жылғы 18 мамырдағы  №9 «Шебір селолық  округінің  құрамдас бөліктеріне атау беру туралы» шешімінің  күші  жойылды  деп тану туралы
  kaz: Шебір ауылдық  округі әкімінің 2010 жылғы 18 мамырдағы  №9 «Шебір селолық  округінің  құрамдас бөліктеріне атау беру туралы» шешімінің  күші  жойылды  дептану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-19
approved_by:
- '163004005001'
version_date:
  kaz: 2016-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/104096/kaz/19.05.2016
