act_code: '32060'
requisite: Решение Маслихата Мангистауской области 30 января 2007 года N 20/355. Зарегистрировано Департаментом юстиции Мангистауской области 23 февраля 2007 года N 1966. Утратило силу - решением Мангистауского областного маслихата от 10 апреля 2009 года N 13/162
title:
  rus: О поправочных коэффициентах к базовой ставке платы за земельные участки и границах зон города Актау
  kaz: Ақтау қаласы аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффиценттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-30
approved_by:
- '163000000002'
version_date:
  kaz: 2007-01-30
  rus: 2007-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/32060/kaz/30.01.2007
  rus: https://zan.gov.kz/client/#!/doc/32060/rus/30.01.2007
