act_code: '1969'
requisite: Решение акима Мангистауской области от 12 октября 1998 года № 257. Зарегистрировано Управлением юстиции Мангистауской области 19 октября 1998 года № 18
title:
  rus: О мерах по ликвидации задолженности по выплате заработной платы
  kaz: Жалақыны төлеу жөніндегі берешекті жою жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-11
approved_by:
- '163000000003'
version_date:
  kaz: 1998-10-11
  rus: 1998-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/1969/kaz/11.10.1998
  rus: https://zan.gov.kz/client/#!/doc/1969/rus/11.10.1998
