act_code: '217768'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 25 ноября 2025 года № 35/166
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Тупкараганскому району
  kaz: Түпқараған ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-25
approved_by:
- '163006000002'
version_date:
  kaz: 2025-11-25
  rus: 2025-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/217768/kaz/25.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217768/rus/25.11.2025
