act_code: '49332'
requisite: Маңғыстау облысы Бейнеу ауданы Ақжігіт селолық округі әкімінің 2009 жылғы 30 қазандағы № 7 шешімі. Маңғыстау облысының Бейнеу ауданының Әділет басқармасында 2009 жылғы 25 қарашада № 11-3-89 болып тіркелді
title:
  rus: Көшелерге ат қою туралы
  kaz: Көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-30
approved_by:
- '163007008002'
version_date:
  kaz: 2022-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/49332/kaz/04.04.2022
caused_by:
  code: '166316'
  requisite: Маңғыстау облысы Бейнеу ауданы Ақжігіт ауылы әкімінің 2022 жылғы 4 сәуірдегі № 4 шешімі. Қазақстан Республикасының Әділет министрлігінде 2022 жылғы 11 сәуірде № 27517 болып тіркелді
  title:
    rus: Маңғыстау облысы Бейнеу ауданы Ақжігіт ауылы әкімінің «Көшелерге ат қою туралы» 2009 жылғы 30 қазандағы № 7 шешіміне өзгеріс енгізу туралы
    kaz: Маңғыстау облысы Бейнеу ауданы Ақжігіт ауылы әкімінің «Көшелерге ат қою туралы» 2009 жылғы 30 қазандағы № 7 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166316/rus
