act_code: '45601'
requisite: Маңғыстау облысы Маңғыстау ауданы  Шетпе селосы әкімі аппаратының 2009 жылғы 28 сәуірдегі № 277 шешімі. Маңғыстау ауданының Әділет басқармасында 2009 жылғы 29 сәуірде № 11-5-76 тіркелді
title:
  rus: Орталық паркке Қ. Жүсіповтің атағын беру туралы
  kaz: Орталық паркке Қ. Жүсіповтің атағын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-28
approved_by:
- '163008008001'
version_date:
  kaz: 2017-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/45601/kaz/06.11.2017
caused_by:
  code: '116043'
  requisite: Решение акима села Шетпе Мангистауского района Мангистауской области от 6 ноября 2017 года № 487. Зарегистрировано Департаментом юстиции Мангистауской области 17 ноября 2017 года № 3461
  title:
    rus: О внесении изменений в решение акима села Шетпе от 28 апреля 2009 года № 277 «Орталық паркке Қ.Жүсіповтің атағын беру туралы»
    kaz: Шетпе ауылы әкімінің 2009 жылғы 28 сәуірдегі № 277 «Орталық паркке Қ.Жүсіповтің атағын беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/116043/rus
