act_code: '14836'
requisite: Бейнеу аудандық мәлихатының 2003 жылғы 14 ақпандағы № 32/244 шешімі. Маңғыстау облыстық Әділет басқармасында 2003 жылғы 7 наурызда № 1405 тіркелді. Күші жойылды-Маңғыстау облысы Бейнеу аудандық мәслихатының 2012 жылғы 11 маусымдағы № 5/32 шешімімен
title:
  rus: Бейнеу ауданы ауылдарының инфрақұрылымы объектілерін, аумағын кемелге келтіру, ұстау, және тазалығын сақтау ережелері туралы
  kaz: Бейнеу ауданы ауылдарының инфрақұрылымы объектілерін, аумағын кемелге келтіру, ұстау, және тазалығын сақтау ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-02-14
approved_by:
- '163007000002'
version_date:
  kaz: 2003-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/14836/kaz/12.02.2003
