act_code: '217091'
requisite: Решение акима села Кызылозен Тупкараганского района Мангистауской области от 10 ноября 2025 года № 19
title:
  rus: О присвоении названия улице
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-10
approved_by:
- '163006004001'
version_date:
  kaz: 2025-11-10
  rus: 2025-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/217091/kaz/10.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217091/rus/10.11.2025
