act_code: '31420'
requisite: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2006 жылғы 21 желтоқсандағы № 34/204 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының әділет басқармасында 2007 жылғы 5 қаңтарда № 11-2-50 болып тіркелді
title:
  rus: 2007 жылға арналған қалалық бюджет туралы
  kaz: 2007 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '163003000002'
version_date:
  kaz: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31420/kaz/21.12.2006
