act_code: '76277'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 25 ноября 2013 года № 18/118. Зарегистрировано Департаментом юстиции Мангистауской области 27 декабря 2013 года № 2326. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 18 августа 2023 года № 5/52
title:
  rus: Об утверждений Правил проведения раздельных сходов местного сообщества села Акжигит
  kaz: Ақжігіт ауылының жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-25
approved_by:
- '163007000002'
version_date:
  kaz: 2022-02-14
  rus: 2022-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/76277/kaz/14.02.2022
  rus: https://zan.gov.kz/client/#!/doc/76277/rus/14.02.2022
caused_by:
  code: '164476'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 14 февраля 2022 года № 16/155. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 18 августа 2023 года № 5/52
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 25 ноября 2013 года №18/118 «Об утверждении Правил о порядке проведения раздельных схода местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории села Акжигит»
    kaz: Бейнеу аудандық мәслихатының 2013 жылғы 25 қарашадағы №18/118 «Ақжігіт ауылының аумағында бөлек жергілікті қоғамдастық жиынын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібі туралы қағидаларды бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164476/rus
