act_code: '44052'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2008 жылғы 12 желтоқсандағы № 13/85 шешімі. Маңғыстау облысының Әділет департаменті Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2009 жылғы 24 қаңтарда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 11-6-78 болып енгізілді. Күші жойылды - Маңғыстау облысы Түпқараған аудандық мәслихатының 2011 жылғы 31 қазандағы № 41/244 шешімімен
title:
  rus: Форт-Шевченко қаласы мен Баутин поселкесінің базалық салықтық ставкаларына түзету коэффициенттерін және салық салу мақсатында аймақтарға бөліп бағалау схемасын бекіту туралы
  kaz: Форт-Шевченко қаласы мен Баутин поселкесінің базалық салықтық ставкаларына түзету коэффициенттерін және салық салу мақсатында аймақтарға бөліп бағалау схемасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-12
approved_by:
- '163006000002'
version_date:
  kaz: 2008-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/44052/kaz/12.12.2008
