act_code: '57787'
requisite: Бейнеу аудандық мәслихатының 2010 жылғы 30 қарашадағы № 32/192 шешімі. Бейнеу ауданының Әділет басқармасында 2011 жылғы 12 қаңтарда № 11-3-107 тіркелді. Күші жойылды - Маңғыстау облысы Бейнеу ауданы мәслихатының 2012 жылғы 24 шілдедегі № 6/42 шешімімен
title:
  rus: Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы
  kaz: Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-30
approved_by:
- '163007000002'
version_date:
  kaz: 2011-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/57787/kaz/19.09.2011
caused_by:
  code: '60529'
  requisite: Маңғыстау облысы Бейнеу аудандық мәслихатының 2011 жылғы 19 қыркүйектегі № 46/268 шешімі. Маңғыстау облысының Әділет департаментінде 2011 жылғы 23 қыркүйекте № 11-3-122 тіркелді. Күші жойылды - Маңғыстау облысы Бейнеу аудандық мәслихатының 2014 жылғы 24 қарашада № 28/197 шешімімен.
  title:
    rus: Бейнеу аудандық мәслихатының 2010 жылғы 30 қарашадағы № 32/192 "Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы" шешіміне өзгеріс енгізу туралы
    kaz: Бейнеу аудандық мәслихатының 2010 жылғы 30 қарашадағы № 32/192 "Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60529/rus
