act_code: '57787'
requisite: Бейнеу аудандық мәслихатының 2010 жылғы 30 қарашадағы № 32/192 шешімі. Бейнеу ауданының Әділет басқармасында 2011 жылғы 12 қаңтарда № 11-3-107 тіркелді. Күші жойылды - Маңғыстау облысы Бейнеу ауданы мәслихатының 2012 жылғы 24 шілдедегі № 6/42 шешімімен
title:
  rus: Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы
  kaz: Азаматтардың әлеуметтік қорғалатын санаттарына әлеуметтік көмектер жүйесін ретке келтіру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-30
approved_by:
- '163007000002'
version_date:
  kaz: 2010-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/57787/kaz/30.11.2010
