act_code: '62967'
requisite: Решение акима города Жанаозен от 5 января 2012 года № 01. Зарегистрировано Департаментом юстиции Мангистауской области 30 января 2012 года № 11-2-183
title:
  rus: Об организации приписки к призывному участку в январе-марте 2012 года граждан 1995 года рождения
  kaz: 2012 жылдың қаңтар-наурыз айларында 1995 жылы туған азаматтарды шақыру учаскесіне тіркеуді ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-05
approved_by:
- '163003000003'
version_date:
  kaz: 2012-01-05
  rus: 2012-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62967/kaz/05.01.2012
  rus: https://zan.gov.kz/client/#!/doc/62967/rus/05.01.2012
