act_code: '80521'
requisite: Решение маслихата Мангистауского района Мангистауской области от 24 апреля 2014 года № 17/146. Зарегистрировано Департаментом юстиции Мангистауской области 4 июня 2014 года № 2440. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 13 декабря 2021 года № 9/70
title:
  rus: Об утверждении Правил о порядке проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории Мангистауского района
  kaz: Маңғыстау ауданының аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібі туралы қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-24
approved_by:
- '163004000002'
version_date:
  kaz: 2014-04-24
  rus: 2014-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/80521/kaz/24.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80521/rus/24.04.2014
