act_code: '219071'
requisite: Решение Мангистауского областного маслихата от 12 декабря 2025 года № 24/278
title:
  rus: Об областном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-12
approved_by:
- '163000000002'
version_date:
  kaz: 2026-04-24
  rus: 2026-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/219071/kaz/24.04.2026
  rus: https://zan.gov.kz/client/#!/doc/219071/rus/24.04.2026
caused_by:
  code: '224906'
  requisite: Решение Мангистауского областного маслихата от 24 апреля 2026 года № 27/321
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 12 декабря 2025 года № 24/278 «Об областном бюджете на 2026-2028 годы»
    kaz: «2026-2028 жылдарға арналған облыстық бюджет туралы» Маңғыстау облыстық мәслихатының 2025 жылғы 12 желтоқсандағы № 24/278 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224906/rus
