act_code: '78138'
requisite: Решение маслихата Мангистауского района Мангистауской области от 11 марта 2014 года № 15/128. Зарегистрировано Департаментом юстиции Мангистауской области 18 марта 2014 года № 2368. Утратило силу-решением Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/51
title:
  rus: Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе
  kaz: Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-11
approved_by:
- '163004000002'
version_date:
  kaz: 2015-03-04
  rus: 2015-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/78138/kaz/04.03.2015
  rus: https://zan.gov.kz/client/#!/doc/78138/rus/04.03.2015
caused_by:
  code: '88288'
  requisite: Решение маслихата Мангистауского района от 4 марта 2015 года № 23/193. Зарегистрировано Департаментом юстиции Мангистауской области от 3 апреля 2015 года № 2655. Утратило силу-решением Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/51
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 11 марта 2014 года № 15/128 «Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2014 жылғы 11 наурыздағы №15/128 «Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88288/rus
