act_code: '67567'
requisite: Решение маслихата Мангистауской области N 5/68 от 10 августа 2012 года. Зарегистрировано Департаментом юстиции Мангистауской области N 2147 от 12 сентября 2012 года.
title:
  rus: О Правилах застройки территории Мангистауской области
  kaz: Маңғыстау облысының аумағында құрылыс салу қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-08-10
approved_by:
- '163000000002'
version_date:
  kaz: 2012-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/67567/kaz/10.08.2012
