act_code: '176470'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 декабря 2022 года № 18/184
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '163004000002'
version_date:
  kaz: 2022-12-21
  rus: 2022-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/176470/kaz/21.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176470/rus/21.12.2022
