act_code: '176470'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 декабря 2022 года № 18/184
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '163004000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/176470/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176470/rus/13.12.2023
caused_by:
  code: '190047'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 13 декабря 2023 года № 7/48
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 21 декабря 2022 года № 18/184 «О районном бюджете на 2023-2025 годы»
    kaz: Маңғыстау аудандық мәслихатының 2022 жылғы 21 желтоқсандағы № 18/184 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190047/rus
