act_code: '36668'
requisite: Маңғыстау облысы Қарақия аудандық мәслихатының 2007 жылғы 24 желтоқсандағы № 4/28 шешімі. Маңғыстау облысының Әділет департаменті Қарақия ауданының Әділет басқармасында 2008 жылғы 4 қаңтарда № 11-4-50 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2011 жылғы 1 ақпандағы № 34/242 шешімімен
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '163005000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36668/kaz/24.12.2007
