act_code: '25424'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2005 жылғы 13 сәуірдегі № 17/105 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2005 жылғы 20 мамырда № 11-6-7 болып тіркелді
title:
  rus: Түпқараған ауданы инфрақұрылымы объектілерін, аумағын кемелге келтіру, ұстау және аудандағы елді мекендерде тазалықты сақтау ережелері туралы
  kaz: Түпқараған ауданы инфрақұрылымы объектілерін, аумағын кемелге келтіру, ұстау және аудандағы елді мекендерде тазалықты сақтау ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-13
approved_by:
- '163006000002'
version_date:
  kaz: 2005-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/25424/kaz/13.04.2005
