act_code: '61274'
requisite: Решение акима Мангистауской области от 25 октября 2011 года № 3. Зарегистрировано Департаментом юстиции Мангистауской области 11 ноября 2011 года № 2113. Утратило силу письмом Мангистауского областного акимата от 16 июля 2012 года № 01-30-1050
title:
  rus: Об утверждении формы документов по использованию целевых текущих трансфертов из республиканского бюджета 2011 года на поддержку племенного животноводства
  kaz: Асыл тұқымды мал шаруашылығының қолдауға 2011 жылғы республикалық бюджеттен берілетін ағымдағы нысаналы трансферттерді пайдалану бойынша құжаттардың нысандарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-24
approved_by:
- '163000000001'
version_date:
  kaz: 2011-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/61274/kaz/25.10.2011
