act_code: '146998'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 28 сентября 2020 года № 54/429. Зарегистрировано Департаментом юстиции Мангистауской области 2 октября 2020 года № 4302
title:
  rus: Об утверждении Регламента собрания местного сообщества села Сынгырлау
  kaz: Сыңғырлау ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-28
approved_by:
- '163007000002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/146998/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/146998/rus/13.12.2021
caused_by:
  code: '162168'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 13 декабря 2021 года № 13/131
  title:
    rus: О внесении изменений и дополнений в решение Бейнеуского районного маслихата от 28 сентября 2020 года № 54/429 «Об утверждении Регламента собрания местного сообщества села Сынгырлау»
    kaz: Бейнеу аудандық мәслихатының 2020 жылғы 28 қыркүйектегі № 54/429 «Сыңғырлау ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162168/rus
