act_code: '204575'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2024 года № 17/182. Зарегистрировано Департаментом юстиции Мангистауской области 19 декабря 2024 года № 4756-12
title:
  rus: Об утверждении Правил содержания сельскохозяйственных животных в населенных пунктах Мангистауской области
  kaz: Маңғыстау облысының елді мекендерінде ауыл шаруашылығы жануарларын асырау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2024-12-13
  rus: 2024-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/204575/kaz/13.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204575/rus/13.12.2024
