act_code: '50175'
requisite: Решение Актауского городского маслихата от 22 декабря 2009 года № 27/240. Зарегистрировано Управлением юстиции города Актау 21 января 2010 года № 11-1-123. Утратило силу решением Актауского городского маслихата от 28 февраля 2013 года № 9/101.
title:
  rus: Об установлении стоимости разовых талонов для физических лиц, индивидуальных предпринимателей и юридических лиц, осуществляющих деятельность по реализации товаров, выполнению работ, оказанию услуг на рынках, за исключением реализации в киосках, стационарных помещениях (изолированных блоках) на территории рынка
  kaz: Базар аумағындағы дүңгіршектердегі, стационарлық үй-жайлардағы (оқшауланған блоктардағы) сауданы қоспағанда, базардағы тауарларды, жұмыстар орындауды және қызметтер көрсетуді сату жөніндегі қызметтерді жүзеге асыратын жеке тұлғалар, дара кәсіпкерлер мен заңды тұлғалар үшін бір жолғы талондарының ақысын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '163002000002'
version_date:
  kaz: 2009-12-22
  rus: 2009-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/50175/kaz/22.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50175/rus/22.12.2009
