act_code: '79758'
requisite: Решение акимата Мангистауской области 8 апреля 2014 года № 1. Зарегистрировано Департаментом юстиции Мангистауской области 6 мая 2014 года № 2412. Утратило силу - решением акимата Мангистауской области от 30 октября 2014 года № 4
title:
  rus: Об утверждении перечня опорных сельских населенных пунктов Мангистауской области
  kaz: Маңғыстау облысының тірек ауылдық елді мекендерінің тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-08
approved_by:
- '163000000001'
version_date:
  kaz: 2014-04-08
  rus: 2014-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/79758/kaz/08.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79758/rus/08.04.2014
