act_code: '19768'
requisite: Решение Мангистауского областного Маслихата от 31 марта 2004 года № 4/47. Зарегистрировано Департаментом юстиции Мангистауской области 6 мая 2004 года за № 1687
title:
  rus: О Программе индустриально-инновационного развития Мангистауской области на 2004-2006 годы
  kaz: Маңғыстау облысының индустриалды-инновациялық дамуының 2004-2006 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-03-30
approved_by:
- '163000000002'
version_date:
  kaz: 2004-12-08
  rus: 2004-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/19768/kaz/08.12.2004
  rus: https://zan.gov.kz/client/#!/doc/19768/rus/08.12.2004
caused_by:
  code: '22342'
  requisite: Решение Мангистауского областного маслихата от 8 декабря 2004 года № 8/135. Зарегистрировано Департаментом юстиции Мангистауской области 22 декабря 2004 года № 1805
  title:
    rus: О внесении изменений в решение областного маслихата от 31 декабря 2004 года № 4/47 "О Программе индустриально-инновационного развития Мангистауской области на 2004-2006 годы"
    kaz: '"Маңғыстау облысының индустриалық-инновациялық дамуының 2004-2006 жылдарға арналған Бағдарламасы туралы" облыстық мәслихаттың 2004 жылғы 31 наурыздағы № 4/47 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/22342/rus
