act_code: '19768'
requisite: Решение Мангистауского областного Маслихата от 31 марта 2004 года № 4/47. Зарегистрировано Департаментом юстиции Мангистауской области 6 мая 2004 года за № 1687
title:
  rus: О Программе индустриально-инновационного развития Мангистауской области на 2004-2006 годы
  kaz: Маңғыстау облысының индустриалды-инновациялық дамуының 2004-2006 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-03-30
approved_by:
- '163000000002'
version_date:
  kaz: 2004-03-30
  rus: 2004-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/19768/kaz/30.03.2004
  rus: https://zan.gov.kz/client/#!/doc/19768/rus/30.03.2004
