act_code: '225611'
requisite: Решение акима Каракиянского района Мангистауской области от 21 мая 2026 года № 6
title:
  rus: Об объявлении чрезвычайной ситуации
  kaz: Төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-21
approved_by:
- '163005000003'
version_date:
  kaz: 2026-05-21
  rus: 2026-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/225611/kaz/21.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225611/rus/21.05.2026
