act_code: '3283'
requisite: Решение Акима Мангистауской области от 22 июня 1999 года № 157. Зарегистрировано управленим юстиции Мангистауской области 22 июня 1999 года № 83. Утратило силу - решением акима Мангистауской области от 30 октября 2014 года № 4.
title:
  rus: Об утверждении "Правил (условий) выпуска, размещения, обращения и погашения облигаций местного исполнительного органа Мангистауской области"
  kaz: '"Маңғыстау облысы жергілікті атқару органының облигацияларының шығару, орналастыру , айналым және өтеу Тәртібін (шарттарын)" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-21
approved_by:
- '163000000001'
version_date:
  rus: 1999-06-21
source:
  rus: https://zan.gov.kz/client/#!/doc/3283/rus/21.06.1999
