act_code: '155238'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 16 апреля 2021 года № 3/28. Зарегистрировано Департаментом юстиции Мангистауской области 23 апреля 2021 года № 4499
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций социального обеспечения, образования, культуры, спорта, ветеринарии и здравоохранения проживающим и работающим в сельских населенных пунктах города Жанаозен
  kaz: Жаңаөзен қаласының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария және денсаулық сақтау ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсетудің тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-16
approved_by:
- '163003000002'
version_date:
  kaz: 2021-04-16
  rus: 2021-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/155238/kaz/16.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155238/rus/16.04.2021
