act_code: '149537'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 27 ноября 2020 года № 45/452. Зарегистрировано Департаментом юстиции Мангистауской области 9 декабря 2020 года № 4363. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 6 октября 2023 года № 6/44
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообществана территории сел, сельских округов Каракиянского района
  kaz: Қарақия ауданының ауыл, ауылдық округтерінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-27
approved_by:
- '163005000002'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/149537/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/149537/rus/12.11.2021
caused_by:
  code: '163167'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 12 ноября 2021 года № 9/78. Утратило силу решением Каракиянского районного маслихата Мангистауской области от 6 октября 2023 года № 6/44
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 27 ноября 2020 года № 45/452 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Каракиянского района»
    kaz: «Қарақия ауданының елді мекендерінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы» Қарақия аудандық мәслихатының 2020 жылғы 27 қарашадағы № 45/452 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/163167/rus
