act_code: '223221'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 13 марта 2026 года № 40/189
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Тупкараганскому району на 2026-2031 годы
  kaz: Түпқараған ауданы бойынша 2026-2031 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-13
approved_by:
- '163006000002'
version_date:
  kaz: 2026-03-13
  rus: 2026-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/223221/kaz/13.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223221/rus/13.03.2026
