act_code: '23519'
requisite: Маңғыстау облысы Жаңаөзен қаласы әкімінің 2005 жылғы 21 сәуірдегі № 162 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының Әділет басқармасында 2005 жылғы 25 сәуірде № 11-2-2 болып тіркелді
title:
  rus: Алғаш әскери дайындықтан 6 күдік дала жаттығуларын өткезу туралы
  kaz: Алғаш әскери дайындықтан 6 күдік дала жаттығуларын өткезу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-21
approved_by:
- '163003000003'
version_date:
  kaz: 2005-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/23519/kaz/21.04.2005
