act_code: '196828'
requisite: Решение акима села Курык Каракиянского района Мангистауской области от 30 апреля 2024 года № 93
title:
  rus: Об установлении публичного
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-30
approved_by:
- '163005006002'
version_date:
  kaz: 2024-04-30
  rus: 2024-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/196828/kaz/30.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196828/rus/30.04.2024
