act_code: '30039'
requisite: Маңғыстау облысы Бейнеу ауданы Бейнеу ауылы әкімінің 2008 жылғы 25 шілдедегі № 509 шешімі. Маңғыстау облысы Әділет департаменті Бейнеу ауданының әділет басқармасында 2008 жылғы 11 тамызда № 11-3-60 болып тіркелді
title:
  rus: Жаңа көшелерге есімдер беру туралы
  kaz: Жаңа көшелерге есімдер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-25
approved_by:
- '163007011001'
version_date:
  kaz: 2018-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/30039/kaz/06.03.2018
caused_by:
  code: '119594'
  requisite: Решение акима села Бейнеу Бейнеуского района Мангистауской области от 6 марта 2018 года № 245. Зарегистрировано Департаментом юстиции Мангистауской области 16 марта 2018 года № 3542
  title:
    rus: О внесении изменений в некоторые решения акима села Бейнеу
    kaz: Бейнеу ауылы әкімінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119594/rus
