act_code: '30039'
requisite: Маңғыстау облысы Бейнеу ауданы Бейнеу ауылы әкімінің 2008 жылғы 25 шілдедегі № 509 шешімі. Маңғыстау облысы Әділет департаменті Бейнеу ауданының әділет басқармасында 2008 жылғы 11 тамызда № 11-3-60 болып тіркелді
title:
  rus: Жаңа көшелерге есімдер беру туралы
  kaz: Жаңа көшелерге есімдер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-25
approved_by:
- '163007011001'
version_date:
  kaz: 2008-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/30039/kaz/25.07.2008
