act_code: '56436'
requisite: Решение маслихата города Жанаозен от 22 декабря 2010 года № 34/252. Зарегистрировано Управлением юстиции города Жанаозен 29 декабря 2010 года № 11-2-149
title:
  rus: О городском бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '163003000002'
version_date:
  kaz: 2011-07-28
  rus: 2011-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56436/kaz/28.07.2011
  rus: https://zan.gov.kz/client/#!/doc/56436/rus/28.07.2011
caused_by:
  code: '60070'
  requisite: Решение маслихата города Жанаозен от 28 июля 2011 года № 41/300. Зарегистрировано Департаментом юстиции Мангистауской области 12 августа 2011 года № 11-2-170
  title:
    rus: О внесении изменений и дополнения в решение Жанаозенского городского маслихата от 22 декабря 2010 года № 34/252 "О городском бюджете на 2011 - 2013 годы"
    kaz: Жаңаөзен қалалық мәслихатының 2010 жылғы 22 желтоқсандағы № 34/252 "2011 - 2013 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60070/rus
