act_code: '37212'
requisite: Решение акима города Актау Мангистауской области от 28 декабря 2007 года № 250. Зарегистрировано Управлением юстиции города Актау 25 января 2008 года № 11-1-73
title:
  rus: О мерах по организации приписки граждан к призывному участку управления по делам обороны города Актау
  kaz: Ақтау қаласы қорғаныс істері жөніндегі басқармасының шақыру учаскесіне тіркеуге алуды ұйымдастыру жөнінде шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-28
approved_by:
- '163002000001'
version_date:
  kaz: 2007-12-28
  rus: 2007-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/37212/kaz/28.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37212/rus/28.12.2007
