act_code: '107883'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 21 октября 2016 года № 4/68. Зарегистрировано Департаментом юстиции Мангистауской области от 2 декабря 2016 года № 3204
title:
  rus: О схем зонирования и поправочных коэффициентах к базовой ставке земельного налога для целей налогообложения села Мангистау
  kaz: Маңғыстау ауылын салық салу мақсатында аймақтарға бөлу схемасы және жер салығының базалық мөлшерлемелеріне түзету коэффициенттері  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '163008000002'
version_date:
  kaz: 2018-04-27
  rus: 2018-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/107883/kaz/27.04.2018
  rus: https://zan.gov.kz/client/#!/doc/107883/rus/27.04.2018
caused_by:
  code: '121886'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 27 апреля 2018 года № 22/274. Зарегистрировано Департаментом юстиции Мангистауской области 18 мая 2018 года № 3607
  title:
    rus: О внесении изменений в некоторые решения Мунайлинского районного маслихата
    kaz: Мұнайлы аудандық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121886/rus
