act_code: '124198'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 1 августа 2018 года № 18/192. Зарегистрировано Департаментом юстиции Мангистауской области 16 августа 2018 года № 3700. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 16 апреля 2024 года № 11/83
title:
  rus: Об определении порядка и размера оказания жилищной помощи в Мангистауском районе
  kaz: Маңғыстау ауданында тұрғын үй көмегін көрсетудің тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-01
approved_by:
- '163004000002'
version_date:
  kaz: 2022-05-18
  rus: 2022-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/124198/kaz/18.05.2022
  rus: https://zan.gov.kz/client/#!/doc/124198/rus/18.05.2022
caused_by:
  code: '168005'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 18 мая 2022 года № 13/140. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 мая 2022 года № 28158. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 16 апреля 2024 года № 11/83
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 1 августа 2018 года №18/192 «Об определении порядка и размера оказания жилищной помощи в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2018 жылғы 1 тамыздағы №18/192 «Маңғыстау ауданында тұрғын үй көмегін көрсетудің тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168005/rus
