act_code: '206653'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 8 января 2025 года № 27/148
title:
  rus: О бюджетах сел, сельских округов на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-08
approved_by:
- '163008000002'
version_date:
  kaz: 2025-01-08
  rus: 2025-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/206653/kaz/08.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206653/rus/08.01.2025
