act_code: '205508'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 27 декабря 2024 года № 23/195
title:
  rus: О районном бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '163005000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205508/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205508/rus/27.12.2024
