act_code: '205508'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 27 декабря 2024 года № 23/195
title:
  rus: О районном бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '163005000002'
version_date:
  kaz: 2025-11-21
  rus: 2025-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/205508/kaz/21.11.2025
  rus: https://zan.gov.kz/client/#!/doc/205508/rus/21.11.2025
caused_by:
  code: '217780'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 21 ноября 2025 года № 31/261
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 27 декабря 2024 года № 23/195 «О районном бюджете на 2025 - 2027 годы»
    kaz: Қарақия аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 23/195 «2025 - 2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217780/rus
