act_code: '79754'
requisite: Постановление Тупкараганского районного акимата Мангистауской области от 28 марта 2014 года № 70. Зарегистрировано Департаментом юстиции Мангистауской области 05 мая 2014 года № 2411.Утратило силу постановлением акимата Тупкараганского района Мангистауской области от 11 марта 2016 года № 39
title:
  rus: Об утверждении норматива отчисления части чистого дохода районных государственных коммунальных предприятий
  kaz: Аудандық мемлекеттік коммуналдық кәсіпорындардың таза табысының бір бөлігін аудару нормативін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '163006000001'
version_date:
  kaz: 2014-03-28
  rus: 2014-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/79754/kaz/28.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79754/rus/28.03.2014
