act_code: '94538'
requisite: Решение Тупкарагнского районного маслихата Мангистауской области от 07 сентября 2015 года № 33/226. Зарегистрировано Департаментом юстиции Мангистауской области от 13 октября 2015 года № 2842. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 01 февраля 2016 года № 38/262
title:
  rus: 'Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Тупкараганского районного маслихата» '
  kaz: '«Түпқараған аудандық мәслихатының  аппараты»  мемлекеттік  мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің  қызметін жыл сайынғы бағалаудың  әдістемесін  бекіту туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-07
approved_by:
- '163006000002'
version_date:
  kaz: 2015-09-07
  rus: 2015-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/94538/kaz/07.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94538/rus/07.09.2015
