act_code: '151811'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 31 декабря 2020 года № 54/583. Зарегистрировано Департаментом юстиции Мангистауской области 13 января 2021 года № 4422
title:
  rus: О бюджете села Рахат на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған Рахат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-31
approved_by:
- '163003000002'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151811/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/151811/rus/23.07.2021
caused_by:
  code: '157694'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 23 июля 2021 года № 6/57
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 31 декабря 2020 года № 54/583 «О бюджете села Рахат на 2021 - 2023 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2020 жылғы 31 желтоқсандағы № 54/583 «2021 - 2023 жылдарға арналған Рахат ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157694/rus
