act_code: '162049'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 13 декабря 2021 года № 9/70. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 13 декабря 2023 года № 7/54
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества в населенных пунктах Мангистауского района
  kaz: Маңғыстау ауданының елді мекендерінде жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-13
approved_by:
- '163004000002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/162049/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162049/rus/13.12.2021
