act_code: '74542'
requisite: Решение маслихата Бейнеуского района Мангистауской области от 28 августа 2013 года № 17/113. Зарегистрировано Департаментом юстиции Мангистауской области 26 сентября 2013 года № 2298. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 2 декабря 2020 года № 56/453
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-28
approved_by:
- '163007000002'
version_date:
  kaz: 2015-02-16
  rus: 2015-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/74542/kaz/16.02.2015
  rus: https://zan.gov.kz/client/#!/doc/74542/rus/16.02.2015
caused_by:
  code: '87497'
  requisite: Решение маслихата Бейнеуского района от 16 февраля 2015 года № 30/214. Зарегистрировано Департаментом юстиции Мангистауской обалсти от 11 марта 2015 года № 2631. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 2 декабря 2020 года № 56/453
  title:
    rus: О внесении изменений  в решение Бейнеуского районного маслихата от 28 августа 2013 года №17/113 «О назначении социальной помощи на возмещение расходов на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах»
    kaz: Бейнеу аудандық  мәслихатының 2013 жылғы 28 тамыздағы № 17/113 «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуғ ажұмсалатын шығынды өтеу үшін әлеуметтік көмек тағайындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87497/rus
