act_code: '74542'
requisite: Решение маслихата Бейнеуского района Мангистауской области от 28 августа 2013 года № 17/113. Зарегистрировано Департаментом юстиции Мангистауской области 26 сентября 2013 года № 2298. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 2 декабря 2020 года № 56/453
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-28
approved_by:
- '163007000002'
version_date:
  kaz: 2018-06-26
  rus: 2018-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/74542/kaz/26.06.2018
  rus: https://zan.gov.kz/client/#!/doc/74542/rus/26.06.2018
caused_by:
  code: '123290'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 26 июня 2018 года № 24/204. Зарегистрировано Департаментом юстиции Мангистауской области 10 июля 2018 года № 3681. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 2 декабря 2020 года № 56/453
  title:
    rus: О внесении изменения в решение Бейнеуского районного маслихата от 28 августа 2013 года № 17/113 «О предоставлении социальной помощи на возмещение расходов на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии проживающим и работающим в сельских населенных пунктах»
    kaz: Бейнеу аудандық мәслихатының 2013 жылғы 28 тамыздағы № 17/113 «Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін әлеуметтік көмек беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123290/rus
