act_code: '56746'
requisite: Решение маслихата Тупкараганского района  от 20 декабря 2010 года № 33/198. Зарегистрировано Департаментом юстиции Мангистауской области 13 января 2011 года № 11-6-128
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '163006000002'
version_date:
  kaz: 2010-12-20
  rus: 2010-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56746/kaz/20.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56746/rus/20.12.2010
