act_code: '35797'
requisite: Маңғыстау облысы Мұнайлы ауданы мәслихатының 2007 жылғы 11 қазандағы N 2/25 шешімі. Маңғыстау облысының Әділет департаментінде 2007 жылғы 19 қазанда N 1985 тіркелді. Күші жойылды - Мұнайлы аудандық мәслихатының 2010 жылғы 27 шілдедегі № 27/276 шешімімен
title:
  rus: Азаматтардың жекелеген санаттарына әлеуметтік төлемдерді тағайындау  және көрсету туралы
  kaz: Азаматтардың жекелеген санаттарына әлеуметтік төлемдерді тағайындау  және көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-11
approved_by:
- '163008000002'
version_date:
  kaz: 2007-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/35797/kaz/11.11.2007
