act_code: '205068'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 20 декабря 2024 года № 23/189
title:
  rus: О бюджете города Жанаозен на 2025 – 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Жаңаөзен қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-20
approved_by:
- '163003000002'
version_date:
  kaz: 2025-03-12
  rus: 2025-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/205068/kaz/12.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205068/rus/12.03.2025
caused_by:
  code: '208144'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 12 марта 2025 года № 25/204
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 20 декабря 2024 года № 23/189 «О бюджете города Жанаозен на 2025 - 2027 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2024 жылғы 20 желтоқсандағы № 23/189 «2025 - 2027 жылдарға арналған Жаңаөзен қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208144/rus
