act_code: '50834'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № 25/153 шешімі. Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2010 жылғы 6 қаңтарда № 11-6-107 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '163006000002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/50834/kaz/09.04.2010
caused_by:
  code: '51948'
  requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2010 жылғы 9 сәуірдегі № 28/170 шешімі. Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2010 жылғы 21 сәуірде № 11-6-117 тіркелді
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 21 желтоқсандағы № 25/153 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 21 желтоқсандағы № 25/153 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/51948/rus
