act_code: '101570'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 15 марта 2016 года № 33/351. Зарегистрировано Департаментом юстиции Мангистауской области от 21 апреля 2016 года № 3022.Утратило силу решением Каракиянского районного маслихата Мангистауской области от 10 марта 2017 года № 8/93
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б»  государственного учреждения «Аппарат Каракиянского  районного маслихата»
  kaz: «Қарақия  аудандық мәслихатының аппараты» мемлекеттік мекемесінің  «Б» корпусы мемлекеттік әкімшілік  қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-15
approved_by:
- '163005000002'
version_date:
  kaz: 2016-03-15
  rus: 2016-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/101570/kaz/15.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101570/rus/15.03.2016
