act_code: '137903'
requisite: Решение Актауского городского маслихата Мангистауской области от 24 декабря 2019 года № 29/321. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2020 года № 4093
title:
  rus: О бюджете города Актау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '163002000002'
version_date:
  kaz: 2020-05-05
  rus: 2020-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/137903/kaz/05.05.2020
  rus: https://zan.gov.kz/client/#!/doc/137903/rus/05.05.2020
caused_by:
  code: '142886'
  requisite: Решение Актауского городского маслихата Мангистауской области от 5 мая 2020 года № 31/353. Зарегистрировано Департаментом юстиции Мангистауской области 15 мая 2020 года № 4211
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 24 декабря 2019 года № 29/321 «О бюджете города Актау на 2020-2022 годы»
    kaz: Ақтау қалалық мәслихатының 2019 жылғы 24 желтоқсандағы № 29/321 «2020-2022 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142886/rus
