act_code: '137903'
requisite: Решение Актауского городского маслихата Мангистауской области от 24 декабря 2019 года № 29/321. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2020 года № 4093
title:
  rus: О бюджете города Актау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '163002000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137903/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137903/rus/27.11.2020
caused_by:
  code: '149486'
  requisite: Решение Актауского городского маслихата Мангистауской области от 27 ноября 2020 года № 36/408. Зарегистрировано Департаментом юстиции Мангистауской области 8 декабря 2020 года № 4357
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 24 декабря 2019 года № 29/321 «О бюджете города Актау на 2020-2022 годы»
    kaz: Ақтау қалалық мәслихатының 2019 жылғы 24 желтоқсандағы № 29/321 «2020-2022 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149486/rus
