act_code: '204578'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2024 года № 17/177
title:
  rus: Об областном бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2025-08-04
  rus: 2025-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/204578/kaz/04.08.2025
  rus: https://zan.gov.kz/client/#!/doc/204578/rus/04.08.2025
caused_by:
  code: '213205'
  requisite: Решение Мангистауского областного маслихата от 4 августа 2025 года № 21/250
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 13 декабря 2024 года № 17/177 «Об областном бюджете на 2025-2027 годы»
    kaz: Маңғыстау облыстық мәслихатының 2024 жылғы 13 желтоқсандағы № 17/177 «2025-2027 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213205/rus
