act_code: '204578'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2024 года № 17/177
title:
  rus: Об областном бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2025-12-12
  rus: 2025-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204578/kaz/12.12.2025
  rus: https://zan.gov.kz/client/#!/doc/204578/rus/12.12.2025
caused_by:
  code: '218839'
  requisite: Решение Мангистауского областного маслихата от 12 декабря 2025 года № 24/280
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 13 декабря 2024 года № 17/177 «Об областном бюджете на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған облыстық бюджет туралы» Маңғыстау облыстық мәслихатының 2024 жылғы 13 желтоқсандағы № 17/177 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218839/rus
