act_code: '205052'
requisite: Решение Актауского городского маслихата Мангистауской области от 20 декабря 2024 года № 18/118
title:
  rus: О бюджете города Актау на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Ақтау қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-20
approved_by:
- '163002000002'
version_date:
  kaz: 2025-11-19
  rus: 2025-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/205052/kaz/19.11.2025
  rus: https://zan.gov.kz/client/#!/doc/205052/rus/19.11.2025
caused_by:
  code: '217466'
  requisite: Решение Актауского городского маслихата Мангистауской области от 19 ноября 2025 года № 25/163
  title:
    rus: О внесении изменений в решение Актауского городского маслихата Мангистауской области от 20 декабря 2024 года № 18/118 «О бюджете города Актау на 2025-2027 годы»
    kaz: Маңғыстау облысы Ақтау қалалық мәслихатының 2024 жылғы 20 желтоқсандағы № 18/118 «2025-2027 жылдарға арналған Ақтау қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217466/rus
