act_code: '41657'
requisite: Маңғыстау облысы Түпқараған ауданы мәслихатының 2008 жылғы 15 тамыздағы № 8/54 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2007 жылғы 19 ақпанда № 11-5-38 болып тіркелді
title:
  rus: Ойын бизнесі саласындағы жеке тұлғаларға тіркелген жиынтық салық көрсеткіштерін белгілеу туралы
  kaz: Ойын бизнесі саласындағы жеке тұлғаларға тіркелген жиынтық салық көрсеткіштерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-15
approved_by:
- '163006000002'
version_date:
  kaz: 2008-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/41657/kaz/15.08.2008
