act_code: '102022'
requisite: Маңғыстау облысы Бейнеу аудандық мәслихатының 2016 жылғы 15 сәуірдегі № 2/15 шешімі
title:
  rus: Бейнеу аудандық мәслихатының 2009 жылғы 12 қаңтардағы №13/91 "Бірыңғай тіркелген салық ставкаларын белгілеу туралы" шешімінің күшін жою туралы
  kaz: Бейнеу аудандық мәслихатының 2009 жылғы 12 қаңтардағы №13/91 "Бірыңғай тіркелген салық ставкаларын белгілеу туралы" шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-15
approved_by:
- '163007000002'
version_date:
  kaz: 2016-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/102022/kaz/15.04.2016
