act_code: '158579'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 26 августа 2021 года № 7/53
title:
  rus: Об утверждении плана управления и использования пастбищ Мангистаускому району на 2021-2022 годы
  kaz: Маңғыстау ауданы бойынша 2021-2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-08-26
approved_by:
- '163004000002'
version_date:
  kaz: 2022-09-05
  rus: 2022-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/158579/kaz/05.09.2022
  rus: https://zan.gov.kz/client/#!/doc/158579/rus/05.09.2022
caused_by:
  code: '171536'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 5 сентября 2022 года № 14/148
  title:
    rus: О внесении изменения и дополнений в решение Мангистауского районного маслихата от 26 августа 2021 года № 7/53 «Об утверждении плана управления и использования пастбищ Мангистаускому району на 2021-2022 годы»
    kaz: Маңғыстау аудандық мәслихатының 2021 жылғы 26 тамыздағы № 7/53 «Маңғыстау ауданы бойынша 2021-2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» шешіміне өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171536/rus
