act_code: '128747'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 23 января 2019 года № 28/227. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2019 года № 3797
title:
  rus: О районном бюджете на 2019 – 2021 годы
  kaz: 2019 - 2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163006000002'
version_date:
  kaz: 2019-01-23
  rus: 2019-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/128747/kaz/23.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128747/rus/23.01.2019
