act_code: '7701'
requisite: Решение акима Мангистауской области от 21 июня 2000 года № 438. Зарегистрировано Управлением юстиции Мангистауской области 28 июня 2000 года № 226. Утратило силу письмом Мангистауского областного акимата от 16 июля 2012 года № 01-30-1050
title:
  rus: Об утверждении областного комплексного плана мероприятий по борьбе с бешенством на 2000-2005 гг.
  kaz: Облыс бойынша 2000-2005 жылдарға арналған құтыру ауруына қарсы іс-шаралардың кешенді жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-20
approved_by:
- '163000000003'
version_date:
  kaz: 2000-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/7701/kaz/20.06.2000
