act_code: '4409'
requisite: Маңғыстау облысы Бейнеу ауданы Бейнеу селосы әкімінің 2008 жылғы 3 желтоқсандағы № 781 шешімі. Маңғыстау облысы Әділет департаменті Бейнеу ауданының әділет басқармасында 2009 жылғы 8 қаңтарда № 11-3-67 болып тіркелді
title:
  rus: Жаңа көшелерге есімдер беру туралы
  kaz: Жаңа көшелерге есімдер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-03
approved_by:
- '163007011001'
version_date:
  kaz: 2008-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/4409/kaz/03.12.2008
