act_code: '221135'
requisite: Решение акима села Баянды Мунайлинского района Мангистауской области от 8 января 2026 года № 01-ш
title:
  rus: О присвоениии наименования улице
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-08
approved_by:
- '163008005001'
version_date:
  kaz: 2026-01-08
  rus: 2026-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/221135/kaz/08.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221135/rus/08.01.2026
