act_code: '191115'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 21 декабря 2023 года № 11/92
title:
  rus: О бюджете города Жанаозен на 2024 – 2026 годы
  kaz: 2024 - 2026 жылдарға арналған Жаңаөзен қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-21
approved_by:
- '163003000002'
version_date:
  kaz: 2024-12-03
  rus: 2024-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/191115/kaz/03.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191115/rus/03.12.2024
caused_by:
  code: '203785'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 3 декабря 2024 года № 22/172.
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 21 декабря 2023 года № 11/92 «О бюджете города Жанаозен на 2024 - 2026 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2023 жылғы 21 желтоқсандағы № 11/92 «2024 - 2026 жылдарға арналған Жаңаөзен қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203785/rus
