act_code: '42581'
requisite: Маңғыстау облысы Бейнеу ауданы Сарға ауылы әкімінің 2008 жылғы 14 қазандағы № 83 шешімі. Маңғыстау облысы Бейнеу ауданының Әділет басқармасында 2008 жылғы 14 қарашада № 11-3-64 тіркелді.
title:
  rus: Жаңа көшеге ат беру туралы
  kaz: Жаңа көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-14
approved_by:
- '163007001001'
version_date:
  kaz: 2008-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/42581/kaz/14.10.2008
