act_code: '42581'
requisite: Маңғыстау облысы Бейнеу ауданы Сарға ауылы әкімінің 2008 жылғы 14 қазандағы № 83 шешімі. Маңғыстау облысы Бейнеу ауданының Әділет басқармасында 2008 жылғы 14 қарашада № 11-3-64 тіркелді.
title:
  rus: Жаңа көшеге ат беру туралы
  kaz: Жаңа көшеге ат беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-10-14
approved_by:
- '163007001001'
version_date:
  kaz: 2017-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/42581/kaz/10.07.2017
caused_by:
  code: '114068'
  requisite: Решение акима села Сарга Бейнеуского района Мангистауской области от 10 июля 2017 года № 60. Зарегистрировано Департаментом юстиции Мангистауской области 11 августа 2017 года № 3407
  title:
    rus: О внесении изменений в решение акима сельского округа Сарга от 14 октября 2008 года № 83 "Жаңа көшеге ат беру туралы"
    kaz: Сарға ауылдық округі әкімінің 2008 жылғы 14 қазандағы № 83 "Жаңа көшеге ат беру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114068/rus
