act_code: '39224'
requisite: Қарақия аудандық мәслихатының 2008 жылғы 20 ақпандағы № 5/37 шешімі. Қарақия ауданының Әділет басқармасында 2008 жылғы 19 наурызда № 11-4-54 тіркелді
title:
  rus: Құрық селосы бойынша жер учаскелері  құнының базалық мөлшерлемесіне түзету коэффициенттері және бағалық аймақтарға бөлу шекаралары туралы
  kaz: Құрық селосы бойынша жер учаскелері  құнының базалық мөлшерлемесіне түзету коэффициенттері және бағалық аймақтарға бөлу шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-20
approved_by:
- '163005000002'
version_date:
  kaz: 2008-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/39224/kaz/20.02.2008
