act_code: '39224'
requisite: Қарақия аудандық мәслихатының 2008 жылғы 20 ақпандағы № 5/37 шешімі. Қарақия ауданының Әділет басқармасында 2008 жылғы 19 наурызда № 11-4-54 тіркелді
title:
  rus: Құрық селосы бойынша жер учаскелері  құнының базалық мөлшерлемесіне түзету коэффициенттері және бағалық аймақтарға бөлу шекаралары туралы
  kaz: Құрық селосы бойынша жер учаскелері  құнының базалық мөлшерлемесіне түзету коэффициенттері және бағалық аймақтарға бөлу шекаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-20
approved_by:
- '163005000002'
version_date:
  kaz: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/39224/kaz/28.10.2015
caused_by:
  code: '96228'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 октября 2015 года № 29/298. Зарегистрировано Департаментом юстиции Мангистауской области от 9 декабря 2015 года № 2905
  title:
    rus: О внесении изменений в некоторые решения маслихата Каракиянского района
    kaz: Қарақия аудандық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96228/rus
