act_code: '191315'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 26 декабря 2023 года № 11/69. Зарегистрировано Департаментом юстиции Мангистауской области 29 декабря 2023 года № 4660-12
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Тупкараганском районе
  kaz: Түпқараған ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '163006000002'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/191315/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/191315/rus/15.09.2025
caused_by:
  code: '214735'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 15 сентября 2025 года № 34/160
  title:
    rus: О внесении изменении в решение Тупкараганского районного маслихата  от 26 декабря 2023 года № 11/69 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения  перечня отдельных категорий нуждающихся граждан в Тупкараганском районе»
    kaz: «Түпқараған ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Түпқараған аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 11/69 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214735/rus
