act_code: '45126'
requisite: Маңғыстау облысы Түпқараған ауданы мәслихатының 2009 жылғы 6 ақпандағы № 16/101 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2009 жылғы 10 наурызда № 11-6-88 болып тіркелді.
title:
  rus: Ойын бизнесі саласындағы жеке тұлғаларға тіркелген бірыңғай салық көрсеткіштерін белгілеу туралы
  kaz: Ойын бизнесі саласындағы жеке тұлғаларға тіркелген бірыңғай салық көрсеткіштерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '163006000002'
version_date:
  kaz: 2009-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/45126/kaz/06.02.2009
