act_code: '59775'
requisite: Решение акима Мунайлинского района Мангистауской области от 13 июля 2011 года № 46-ш. Зарегистрировано Департаментом юстиции Мангистауской области 28 июля 2011 года № 11-7-95. Утратило силу - решением акима Мунайлинского района от 18 февраля 2015 года № 7-ш.
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-13
approved_by:
- '163008000003'
version_date:
  kaz: 2011-07-13
  rus: 2011-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/59775/kaz/13.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59775/rus/13.07.2011
