act_code: '39594'
requisite: Маңғыстау облысы Қарақия ауданы әкімдігі Жетібай кентінің әкімінің 2008 жылғы 26 наурыздағы № 176 шешімі. Маңғыстау облысы Қарақия ауданының Әділет басқармасында 2008 жылғы 30 сәуірде № 11-4-57 болып тіркелді
title:
  rus: Жетібай ауылындағы жаңа тұрғын үй құрылысы салынып жатқан шағын ауданға атау беру туралы
  kaz: Жетібай ауылындағы жаңа тұрғын үй құрылысы салынып жатқан шағын ауданға атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-26
approved_by:
- '163005005001'
version_date:
  kaz: 2008-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/39594/kaz/26.03.2008
