act_code: '44843'
requisite: Маңғыстау облысы Маңғыстау аудандық мәслихатының 2009 жылғы 10 ақпандағы N 11/137 шешімі. Маңғыстау ауданының Әділет басқармасында 2009 жылғы 12 наурызда N 11-5-71 тіркелді. Күші жойылды - Маңғыстау облысы Маңғыстау аудандық мәслихатының 2016 жылғы 28 сәуірдегі № 2/20 шешімімен
title:
  rus: Ойын бизнесі түрлерінен алынатын жиынтық салық ставкаларының мөлшері туралы
  kaz: Ойын бизнесі түрлерінен алынатын жиынтық салық ставкаларының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-10
approved_by:
- '163004000002'
version_date:
  kaz: 2009-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/44843/kaz/10.02.2009
