act_code: '78137'
requisite: Решение маслихата Мангистауского района Мангистауской области от 11 марта 2014 года № 15/127. Зарегистрировано Департаментом юстиции Мангистауской области 18 марта 2014 года № 2367.Утратило силу-решением Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/52
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском районе
  kaz: Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-11
approved_by:
- '163004000002'
version_date:
  kaz: 2015-06-30
  rus: 2015-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/78137/kaz/30.06.2015
  rus: https://zan.gov.kz/client/#!/doc/78137/rus/30.06.2015
caused_by:
  code: '92178'
  requisite: Решение Мангистауского районного маслихата от 30 июня 2015 года № 25/208. Зарегистрировано Департаментом юстиции Мангистауской области от 14 июля 2015 года № 2757.Утратило силу-решением Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/52
  title:
    rus: О внесении изменений и дополнений в решение Мангистауского районного маслихата от 11 марта 2014 года № 15/127 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2014 жылғы 11 наурыздағы № 15/127 «Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92178/rus
