act_code: '56087'
requisite: Решение Мангистауского областного маслихата от 13 декабря 2010 года № 29/331. Зарегистрировано Департаментом юстиции Мангистауской области 24 декабря 2010 года № 2091
title:
  rus: Об областном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '163000000002'
version_date:
  kaz: 2011-01-28
  rus: 2011-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56087/kaz/28.01.2011
  rus: https://zan.gov.kz/client/#!/doc/56087/rus/28.01.2011
caused_by:
  code: '57152'
  requisite: Решение Мангистауского областного маслихата от 28 января 2011 года № 30/367. Зарегистрировано Департаментом юстиции Мангистауской области 3 февраля 2011 года № 2096
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 13 декабря 2010 года № 29/331 "Об областном бюджете на 2011-2013 годы"
    kaz: '"2011 - 2013 жылдарға арналған облыстық бюджет туралы" облыстық мәслихаттың 2010 жылғы 13 желтоқсандағы № 29/331 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57152/rus
