act_code: '162889'
requisite: Решение акима села Тажен Бейнеуского района Мангистауской области от 27 декабря 2021 года № 01-05/27
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '163007006001'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/162889/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162889/rus/27.12.2021
