act_code: '195769'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 16 апреля 2024 года № 11/84. Зарегистрировано Департаментом юстиции Мангистауской области 18 апреля 2024 года № 4696-12
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском районе
  kaz: Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-16
approved_by:
- '163004000002'
version_date:
  kaz: 2026-04-29
  rus: 2026-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195769/kaz/29.04.2026
  rus: https://zan.gov.kz/client/#!/doc/195769/rus/29.04.2026
caused_by:
  code: '224907'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 29 апреля 2026 года № 28/216
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 16 апреля 2024 года № 11/84 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Мангистауском районе»
    kaz: «Маңғыстау ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» Маңғыстау аудандық мәслихатының 2024 жылғы 16 сәуірдегі № 11/84 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224907/rus
