act_code: '109439'
requisite: Решение акима Мангистауского района Мангистауской области от 27 декабря 2016 года № 12. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2017 года № 3264
title:
  rus: О признании  утратившими  силу некоторых  решений акима Мангистауского  района
  kaz: Маңғыстау ауданы  әкімінің кейбір  шешімдерінің күші  жойылды  деп  тану  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-27
approved_by:
- '163004000001'
version_date:
  kaz: 2016-12-27
  rus: 2016-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/109439/kaz/27.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109439/rus/27.12.2016
