act_code: '137094'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2019 года № 32/387. Зарегистрировано Департаментом юстиции Мангистауской области 18 декабря 2019 года № 4057. Утратило силу решением Мангистауского областного маслихата от 29 марта 2022 года № 9/109
title:
  rus: О предоставлении бесплатного проезда гражданам Мангистауской области за пределы населенного пункта на лечение за счет бюджетных средств
  kaz: Маңғыстау облысы азаматтарына емделу үшін елді мекен шегінен тысқары жерлерге бюджет қаражаты есебінен тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2019-12-10
  rus: 2019-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/137094/kaz/10.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137094/rus/10.12.2019
