act_code: '172286'
requisite: Решение акима села Акжигит Бейнеуского района Мангистауской области от 22 сентября 2022 года № 21
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-22
approved_by:
- '163007008002'
version_date:
  kaz: 2022-09-22
  rus: 2022-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/172286/kaz/22.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172286/rus/22.09.2022
