act_code: '109276'
requisite: Решение Актауского городского маслихата Мангистауской области от 9 декабря 2016 года № 6/70. Зарегистрировано Департаментом юстиции Мангистауской области 20 января 2017 года № 3260. Утратило силу решением Актауского городского маслихата Мангистауской области от 20 августа 2021 года № 5/47
title:
  rus: О создании территориальных советов местного самоуправления города Актау
  kaz: Ақтау қаласының жергілікті өзін-өзі басқарудың аумақтық кеңестерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163002000002'
version_date:
  kaz: 2019-07-12
  rus: 2019-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/109276/kaz/12.07.2019
  rus: https://zan.gov.kz/client/#!/doc/109276/rus/12.07.2019
caused_by:
  code: '133918'
  requisite: Решение Актауского городского маслихата Мангистауской области от 12 июля 2019 года № 27/285. Зарегистрировано Департаментом юстиции Мангистауской области 9 августа 2019 года № 3969. Утратило силу решением Актауского городского маслихата Мангистауской области от 20 августа 2021 года № 5/47
  title:
    rus: О внесении изменений в решение Актауского городского маслихата от 9 декабря 2016 года № 6/70 «О создании территориальных советов местного самоуправления города Актау»
    kaz: Ақтау қалалық мәслихатының 2016 жылғы 9 желтоқсандағы № 6/70 «Ақтау қаласының жергілікті өзін-өзі басқарудың аумақтық кеңестерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133918/rus
