act_code: '190214'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 13 декабря 2023 года № 7/54
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества в населенных пунктах Мангистауского района
  kaz: Маңғыстау ауданының елді мекендерінде жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-13
approved_by:
- '163004000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/190214/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190214/rus/13.12.2023
