act_code: '76381'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 11 декабря 2013 года № 17/111. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2014 года № 2330. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '163006000002'
version_date:
  kaz: 2017-05-15
  rus: 2017-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/76381/kaz/15.05.2017
  rus: https://zan.gov.kz/client/#!/doc/76381/rus/15.05.2017
caused_by:
  code: '112592'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 15 мая 2017 года № 11/95. Зарегистрировано Департаментом юстиции Мангистауской области 2 июня 2017 года № 3366. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
  title:
    rus: О внесении изменений и дополнения в решение Тупкараганского районного маслихата от 11 декабря 2013 года № 17/111 «Об утверждении Правил  оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Түпқараған аудандық мәслихатының 2013 жылғы 11 желтоқсандағы № 17/111 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгерістер және толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112592/rus
