act_code: '76381'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 11 декабря 2013 года № 17/111. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2014 года № 2330. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '163006000002'
version_date:
  kaz: 2015-05-20
  rus: 2015-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/76381/kaz/20.05.2015
  rus: https://zan.gov.kz/client/#!/doc/76381/rus/20.05.2015
caused_by:
  code: '91040'
  requisite: Решение Тупкараганского районного маслихата от 20 мая 2015 года № 30/206. Зарегистрировано Департаментом юстиции Мангистауской области от 17 июня 2015 года № 2742. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
  title:
    rus: О внесении дополнения в решение Тупкараганского районного маслихата от 11  декабря  2013  года № 17/111 «Об утверждении  Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Түпқараған аудандық мәслихатының 2013 жылғы 11 желтоқсандағы №17/111 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының  тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91040/rus
