act_code: '76381'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 11 декабря 2013 года № 17/111. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2014 года № 2330. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '163006000002'
version_date:
  kaz: 2020-03-16
  rus: 2020-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/76381/kaz/16.03.2020
  rus: https://zan.gov.kz/client/#!/doc/76381/rus/16.03.2020
caused_by:
  code: '141119'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 16 марта 2020 года № 40/305. Зарегистрировано Департаментом юстиции Мангистауской области 2 апреля 2020 года № 4169. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 10 декабря 2020 года № 50/369
  title:
    rus: О внесении изменения в решение Тупкараганского районного маслихата от 11 декабря 2013 года № 17/111 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Түпқараған аудандық мәслихатының 2013 жылғы 11 желтоқсандағы № 17/111 «Әлеуметтік көмек көрсетудің, оның мөлшерлемелерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141119/rus
