act_code: '52916'
requisite: Маңғыстау ауданы әкімдігі Шебір селолық округі әкімінің 2010 жылғы 18 мамырдағы № 9 шешімі. Маңғыстау ауданының Әділет басқармасында 2010 жылғы 02 маусымда № 11-5-102 тіркелді
title:
  rus: Шебір селолық округінің құрамдас бөліктеріне атау беру туралы
  kaz: Шебір селолық округінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-18
approved_by:
- '163004005001'
version_date:
  kaz: 2010-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/52916/kaz/18.05.2010
