act_code: '217472'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 24 ноября 2025 года № 35/268
title:
  rus: О понижении размера ставки налога при применении специального налогового режима на основе упрощенной декларации в Бейнеуском районе
  kaz: Бейнеу ауданында оңайтылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-24
approved_by:
- '163007000002'
version_date:
  kaz: 2025-11-24
  rus: 2025-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/217472/kaz/24.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217472/rus/24.11.2025
