act_code: '76612'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 декабря 2013 года № 20/131. Зарегистрировано Департаментом юстиции Мангистауской области 10 января 2014 года № 2333
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '163007000002'
version_date:
  kaz: 2014-07-23
  rus: 2014-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76612/kaz/23.07.2014
  rus: https://zan.gov.kz/client/#!/doc/76612/rus/23.07.2014
caused_by:
  code: '81964'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 июля 2014 года № 25/170. Зарегистрировано Департаментом юстиции Мангистауской области от 12 августа 2014 года № 2484
  title:
    rus: О внесении изменений в решение районного маслихата от 23 декабря 2013 года № 20/131 "О районном бюджете на 2014-2016 годы"
    kaz: Аудандық мәслихаттың 2013 жылғы 23 желтоқсандағы № 20/131 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81964/rus
