act_code: '124320'
requisite: Решение акима сельского округа Отпан Мангистауского района Мангистауской области от 8 августа 2018 года № 29. Зарегистрировано Департаментом юстиции Мангистауской области 29 августа 2018 года № 3704
title:
  rus: О присвоении наименований улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-08
approved_by:
- '163004011002'
version_date:
  kaz: 2018-08-08
  rus: 2018-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/124320/kaz/08.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124320/rus/08.08.2018
