act_code: '128387'
requisite: Решение акима Бейнеуского района Мангистауской области от 27 декабря 2018 года № 5. Зарегистрировано Департаментом юстиции Мангистауской области 3 января 2019 года № 3772
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '163007000001'
version_date:
  kaz: 2026-02-02
  rus: 2026-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/128387/kaz/02.02.2026
  rus: https://zan.gov.kz/client/#!/doc/128387/rus/02.02.2026
caused_by:
  code: '221795'
  requisite: Решение акима села Бейнеу Бейнеуского района Мангистауской области от 2 февраля 2026 года № 1
  title:
    rus: О внесении изменения в решение акима Бейнеуского района от 27 декабря 2018 года № 5 «О образовании избирательных участков»
    kaz: '"Сайлау учаскелерін құру туралы" Бейнеу ауданы әкімінің 2018 жылғы 27 желтоқсандағы № 5 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/221795/rus
