act_code: '128387'
requisite: Решение акима Бейнеуского района Мангистауской области от 27 декабря 2018 года № 5. Зарегистрировано Департаментом юстиции Мангистауской области 3 января 2019 года № 3772
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '163007000001'
version_date:
  kaz: 2019-11-22
  rus: 2019-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/128387/kaz/22.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128387/rus/22.11.2019
caused_by:
  code: '136337'
  requisite: Решение акима Бейнеуского района Мангистауской области от 22 ноября 2019 года № 7. Зарегистрировано Департаментом юстиции Мангистауской области 26 ноября 2019 года № 4038
  title:
    rus: О внесении изменения в решение акима Бейнеуского района от 27 декабря 2018 года № 5 «Об образовании избирательных участков»
    kaz: Бейнеу ауданы әкімінің 2018 жылғы 27 желтоқсандағы № 5 «Сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136337/rus
