act_code: '138556'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 13 января 2020 года № 35/391. Зарегистрировано Департаментом юстиции Мангистауской области 15 января 2020 года № 4102
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '163004000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138556/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138556/rus/27.11.2020
caused_by:
  code: '149318'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 27 ноября 2020 года № 42/453. Зарегистрировано Департаментом юстиции Мангистауской области 4 декабря 2020 года № 4350
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 13 января 2020 года № 35/391 «О районном бюджете на 2020-2022 годы»
    kaz: Маңғыстау аудандық мәслихатының 2020 жылғы 13 қаңтардағы № 35/391 «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149318/rus
