act_code: '206051'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 30 декабря 2024 года № 24/198
title:
  rus: О бюджета села Рахат на 2025 - 2027 годы
  kaz: 2025 – 2027 жылдарға арналған Рахат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '163003000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206051/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206051/rus/30.12.2024
