act_code: '155868'
requisite: Решение акима села Тәжен Бейнеуского района Мангистауской области от 11 мая 2021 года № 01-05/16. Зарегистрировано Департаментом юстиции Мангистауской области 14 мая 2021 года № 4530
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-05-11
approved_by:
- '163007006001'
version_date:
  kaz: 2021-05-11
  rus: 2021-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/155868/kaz/11.05.2021
  rus: https://zan.gov.kz/client/#!/doc/155868/rus/11.05.2021
