act_code: '43889'
requisite: Маңғыстау облысы Жаңаөзен қалалық әкімдігінің 2008 жылғы 18 желтоқсандағы № 281 шешімі. Маңғыстау облысы Әділет департаментінде  Жаңаөзен қаласының Әділет басқармасында 2008 жылғы 22 қаңтарда нормативтік құқықтық кесімдерді мемлекеттік тіркеудің тізіліміне № 11-2-99 болып енгізілді
title:
  rus: 2009 жылдың қаңтар-наурыз айларында 1992 жылы туылған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 2009 жылдың қаңтар-наурыз айларында 1992 жылы туылған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '163003000001'
version_date:
  kaz: 2008-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43889/kaz/18.12.2008
