act_code: '29467'
requisite: Маңғыстау облысы Бейнеу ауданы мәслихатының 2006 жылғы 11 қаңтардағы № 21/164 шешімі. Маңғыстау облысы Әділет департаменті Бейнеу ауданының әділет басқармасында 2006 жылғы 3 ақпанда  № 11-3-17 болып тіркелді
title:
  rus: «Бейнеу ауданының құрметті азаматы» атағы жөніндегі Ережені бекіту туралы
  kaz: «Бейнеу ауданының құрметті азаматы» атағы жөніндегі Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-01-11
approved_by:
- '163007000002'
version_date:
  kaz: 2006-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/29467/kaz/11.01.2006
