act_code: '127301'
requisite: Решение Мунайлинского районного маслихата  Мангистауской области от 10 декабря 2018 года № 32/341. Зарегистрировано Департаментом юстиции Мангистауской области 19 декабря 2018 года № 3736. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 23 октября 2023 года № 6/39
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Мунайлинскому району
  kaz: Мұнайлы ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-10
approved_by:
- '163008000002'
version_date:
  kaz: 2018-12-10
  rus: 2018-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/127301/kaz/10.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127301/rus/10.12.2018
