act_code: '144818'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 2 июля 2020 года № 42/418. Зарегистрировано Департаментом юстиции Мангистауской области 16 июля 2020 года № 4257
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-02
approved_by:
- '163005000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/144818/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/144818/rus/15.12.2021
caused_by:
  code: '162884'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 15 декабря 2021 года № 10/105. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2021 года № 26326
  title:
    rus: О внесении изменения в решение Каракиянского районного маслихата от 2 июля 2020 года № 42/418  «Об определении специализированного места для организации и проведения мирных собраний, порядок использования специализированного места для организации и проведения мирных собраний, норма его предельной заполняемости, а также требования к материально-техническому и организационному обеспечению специализированного места для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Каракиянском районе»
    kaz: Қарақия аудандық мәслихатының 2020 жылғы 2 шілдедегі № 42/418 «Қарақия ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орынды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орынды пайдалану тәртібін, оның шекті толу нормасын, сондай-ақ жиналыстарды ұйымдастыру және өткізу үшін арнайы орынды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162884/rus
