act_code: '166885'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 14 января 2022 года № 10/113
title:
  rus: О бюджетах сел, сельских округов на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған  ауылдардың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-14
approved_by:
- '163004000002'
version_date:
  kaz: 2022-10-03
  rus: 2022-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/166885/kaz/03.10.2022
  rus: https://zan.gov.kz/client/#!/doc/166885/rus/03.10.2022
caused_by:
  code: '172401'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 3 октября 2022 года № 16/159
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 14 января 2022 года № 10/113 «О бюджетах сел, сельских округов на 2022-2024 годы»
    kaz: Маңғыстау аудандық мәслихатының 2022 жылғы 14 қаңтардағы № 10/113 «2022-2024 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172401/rus
