act_code: '108942'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 20 декабря 2016 года № 8/65. Зарегистрировано Департаментом юстиции Мангистауской области 5 января 2017 года № 3231
title:
  rus: О районном бюджете на 2017 - 2019 годы
  kaz: 2017 - 2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-20
approved_by:
- '163006000002'
version_date:
  kaz: 2017-11-30
  rus: 2017-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/108942/kaz/30.11.2017
  rus: https://zan.gov.kz/client/#!/doc/108942/rus/30.11.2017
caused_by:
  code: '116635'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 30 ноября 2017 года № 14/114. Зарегистрировано Департаментом юстиции Мангистауской области 13 декабря 2017 года № 3478
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 20 декабря 2016 года № 8/65 «О районном бюджете на 2017 - 2019 годы»
    kaz: Түпқараған аудандық мәслихатының 2016 жылғы 20 желтоқсандағы № 8/65 «2017 - 2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/116635/rus
