act_code: '109140'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 22 декабря 2016 года № 6/80. Зарегистрировано Департаментом юстиции Мангистауской области 17 января 2017 года № 3255
title:
  rus: '"О районном бюджете на 2017-2019 годы"'
  kaz: '"2017-2019 жылдарға арналған аудандық бюджет туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '163005000002'
version_date:
  kaz: 2017-08-15
  rus: 2017-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/109140/kaz/15.08.2017
  rus: https://zan.gov.kz/client/#!/doc/109140/rus/15.08.2017
caused_by:
  code: '114469'
  requisite: Решение Каракиянского  районного маслихата Мангистауской области от 15 августа 2017 года № 10/128. Зарегистрировано Департаментом юстиции Мангистауской области 5 сентября 2017 года № 3417
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 22 декабря 2016 года № 6/80 «О районном бюджете на 2017-2019 годы»
    kaz: Қарақия аудандық мәслихатының 2016 жылғы 22 желтоқсандағы № 6/80 «2017-2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114469/rus
