act_code: '128456'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 8 января 2019 года № 26/333. Зарегистрировано Департаментом юстиции Мангистауской области 16 января 2019 года № 3775
title:
  rus: О городском бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-08
approved_by:
- '163003000002'
version_date:
  kaz: 2019-11-07
  rus: 2019-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/128456/kaz/07.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128456/rus/07.11.2019
caused_by:
  code: '135935'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 7 ноября 2019 года № 37/432. Зарегистрировано Департаментом юстиции Мангистауской области 11 ноября 2019 года № 4019
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 8 января 2019 года № 26/333 «О городском бюджете на 2019 - 2021 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2019 жылғы 8 қаңтардағы № 26/333 «2019 - 2021 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135935/rus
