act_code: '128456'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 8 января 2019 года № 26/333. Зарегистрировано Департаментом юстиции Мангистауской области 16 января 2019 года № 3775
title:
  rus: О городском бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-08
approved_by:
- '163003000002'
version_date:
  kaz: 2019-05-17
  rus: 2019-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/128456/kaz/17.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128456/rus/17.05.2019
caused_by:
  code: '131666'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 17 мая 2019 года № 31/374. Зарегистрировано Департаментом юстиции Мангистауской области 22 мая 2019 года № 3893
  title:
    rus: О внесении изменений и дополнений в решение Жанаозенского городского маслихата от 8 января 2019 года № 26/333 «О городском бюджете на 2019 - 2021 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2019 жылғы 8 қаңтардағы № 26/333 «2019 - 2021 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131666/rus
