act_code: '67932'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 12 сентября 2012 года № 7/46. Зарегистрировано Департаментом юстиции Мангистауской области 3 октября 2012 года № 2164. Утратило силу решением Тупкараганского  районного маслихата Мангистауской области от 17 марта  2017 года № 10/88
title:
  rus: Об утверждении схем зонирования и поправочных коэффициентов на базовые налоговые ставки в целях налогообложения по городу Форт-Шевченко и селу Баутино
  kaz: Форт-Шевченко қаласы мен Баутин ауылы бойынша салық салу мақсатында аймақтарға бөлу схемасын және базалық салықтық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-12
approved_by:
- '163006000002'
version_date:
  kaz: 2012-09-12
  rus: 2012-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/67932/kaz/12.09.2012
  rus: https://zan.gov.kz/client/#!/doc/67932/rus/12.09.2012
