act_code: '2558'
requisite: Решение акима Мангистауской области от 30 марта 1999 года № 46. Зарегистрировано Управлением юстиции Мангистауской области 6 апреля 1999 года № 43. Утратило силу заключением начальника управление юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: О реорганизации органов Государственной службы занятости области и об утверждении структуры областного управления труда, занятости и социальной защиты населения.
  kaz: Облыстың мемлекеттік жұмыспен қамту қызмет органдарын қайта құру жене облыстық еңбек, халықты жұмыспен қамту және элеуметтік қорғау басқармасының құрылымын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-29
approved_by:
- '163000000003'
version_date:
  kaz: 1999-03-29
  rus: 1999-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/2558/kaz/29.03.1999
  rus: https://zan.gov.kz/client/#!/doc/2558/rus/29.03.1999
