act_code: '3502'
requisite: Решение акима  Мангистауской области от 24 июня 1999 года № 167. Зарегистрировано Управлением юстиции Мангистауской области 14 июля 1999 года № 103. Утратило силу заключением начальника департамента  юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: О реорганизации структуры культуры городов и районов области
  kaz: Облыс қалалары мен аудандары мәдениет мекемелерінің құрылымдарын қайта құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-23
approved_by:
- '163000000003'
version_date:
  kaz: 1999-06-23
  rus: 1999-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/3502/kaz/23.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3502/rus/23.06.1999
