act_code: '131850'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 15 мая 2019 года № 27/314. Зарегистрировано Департаментом юстиции Мангистауской области 22 мая 2019 года № 3894. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 13 декабря 2021 года № 9/73
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по Мангистаускому району
  kaz: Маңғыстау ауданы бойынша сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-15
approved_by:
- '163004000002'
version_date:
  kaz: 2019-05-15
  rus: 2019-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/131850/kaz/15.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131850/rus/15.05.2019
