act_code: '3768'
requisite: Решение акима  Мангистауской области от 9 июня 1999 года № 141. Зарегистрировано Управлением юстиции Мангистауской области 11 августа 1999 года № 124. Утратило силу решением акима Мангистауской области от 4 мая 2004 года № 41
title:
  rus: О мерах по недопущению заноса заболевания формой 1120 крупного рогатого скота на территорию области
  kaz: Ірі мүйізді малдың 1120 нысандағы ауруының облыс аумағына әкелуіне жол бермеу жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-08
approved_by:
- '163000000003'
version_date:
  kaz: 1999-06-08
  rus: 1999-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/3768/kaz/08.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3768/rus/08.06.1999
