act_code: '70039'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 20 декабря 2012 года № 6/74. Зарегистрировано Департаментом юстиции 15 января 2013 года № 2198
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '163005000002'
version_date:
  kaz: 2013-03-05
  rus: 2013-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/70039/kaz/05.03.2013
  rus: https://zan.gov.kz/client/#!/doc/70039/rus/05.03.2013
caused_by:
  code: '71737'
  requisite: Решение Каракиянского районного маслихата от 5 марта 2013 года № 7/79. Зарегистрировано Департаментом юстиции Мангистауской области 28 марта 2013 года № 2230
  title:
    rus: О внесении изменений в решение районного маслихата от 20 декабря 2012 года № 6/74 "О районном бюджете на 2013-2015 годы"
    kaz: Аудандық мәслихаттың 2012 жылғы 20 желтоқсандағы № 6/74 "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/71737/rus
