act_code: '128995'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 5 февраля 2019 года № 32/267. Зарегистрировано Департаментом юстиции Мангистауской области 8 февраля 2019 года № 3820. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 2 декабря 2020 года № 56/454
title:
  rus: Об утверждении тарифов на сбор, вывоз и захоронение твердых бытовых отходов по селу Бейнеу
  kaz: Бейнеу ауылы бойынша тұрмыстық қатты қалдықтарды жинау, әкету және көму тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-05
approved_by:
- '163007000002'
version_date:
  kaz: 2019-02-05
  rus: 2019-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/128995/kaz/05.02.2019
  rus: https://zan.gov.kz/client/#!/doc/128995/rus/05.02.2019
