act_code: '92206'
requisite: Решение Мунайлинского районного маслихата от 3 июля 2015 года № 33/347. Зарегистрировано Департаментом юстиции Мангистауской области 23 июля 2015 года № 2781. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 16 апреля 2021 года № 3/21
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан  в  Мунайлинском  районе
  kaz: Мұнайлы ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-03
approved_by:
- '163008000002'
version_date:
  kaz: 2016-03-16
  rus: 2016-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/92206/kaz/16.03.2016
  rus: https://zan.gov.kz/client/#!/doc/92206/rus/16.03.2016
caused_by:
  code: '101187'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 16 марта 2016 года № 42/458. Зарегистрировано Департаментом юстиции Мангистауской области  13 апреля 2016 года № 3009. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 16 апреля 2021 года № 3/21
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 3 июля 2015 года №33/347 «Об утверждении Правил оказания социальной помощи, установления размеров и  определения перечня отдельных категорий нуждающихся граждан в  Мунайлинском  районе»
    kaz: Мұнайлы аудандық мәслихатының 2015 жылғы 3 шілдедегі №33/347 «Мұнайлы ауданында әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101187/rus
