act_code: '191994'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 28 декабря 2023 года № 12/99
title:
  rus: О бюджете села Кызылсай на 2024 - 2026 годы
  kaz: 2024 – 2026 жылдарға арналған Қызылсай ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '163003000002'
version_date:
  kaz: 2024-12-09
  rus: 2024-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/191994/kaz/09.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191994/rus/09.12.2024
caused_by:
  code: '204185'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 9 декабря 2024 года № 22/183
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 28 декабря 2023 года № 12/99 «О бюджете села Кызылсай на 2024 - 2026 годы»
    kaz: Жаңаөзен қалалық мәслихатының 2023 жылғы 28 желтоқсандағы № 12/99 «2024 - 2026 жылдарға арналған Қызылсай ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204185/rus
