act_code: '217338'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 19 ноября 2025 года № 32/281
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации в городе Жанаозен
  kaz: Жаңаөзен қаласында оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-19
approved_by:
- '163003000002'
version_date:
  kaz: 2025-11-19
  rus: 2025-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/217338/kaz/19.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217338/rus/19.11.2025
