act_code: '38723'
requisite: Маңғыстау облысы Қарақия аудандық мәслихаттың 2008 жылдың 20 ақпанындағы № 5/38 шешімі.Маңғыстау облысы әділет департаментінің Қарақия аудандық әділет басқармасында 2008 жылы 20 наурызда № 11-4-55 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2012 жылғы 28 маусымдағы № 3/48 шешімімен
title:
  rus: Салық салу мақсатында Құрық селосы аумағын аймақтарға бөлу схемасы және жер салығының базалық ставкаларына түзету коэффициенттері туралы
  kaz: Салық салу мақсатында Құрық селосы аумағын аймақтарға бөлу схемасы және жер салығының базалық ставкаларына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-20
approved_by:
- '163005000002'
version_date:
  kaz: 2008-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/38723/kaz/20.02.2008
