act_code: '42377'
requisite: Маңғыстау облысы Мұнайлы ауданы әкімдігі Баянды селосы әкімінің 2008 жылғы 13 маусымдағы № 18 шешімі. Маңғыстау облысы Мұнайлы ауданының Әділет басқармасында 2008 жылғы 30 маусымда № 11-7-8 болып тіркелді
title:
  rus: Баянды-1 тұрғын үй массивіндегі тұрғын үйлердің көше аттарын өзгерту туралы
  kaz: Баянды-1 тұрғын үй массивіндегі тұрғын үйлердің көше аттарын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-13
approved_by:
- '163008005001'
version_date:
  kaz: 2008-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/42377/kaz/13.06.2008
