act_code: '183182'
requisite: Решение акима села Тенге города Жанаозен Мангистауской области от 13 июня 2023 года № 32. Зарегистрировано Департаментом юстиции Мангистауской области 22 июня 2023 года № 4580-12
title:
  rus: О переименовании улиц села Тенге города Жанаозен
  kaz: Жаңаөзен қаласы Теңге ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-13
approved_by:
- '163003001001'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/183182/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183182/rus/13.06.2023
