act_code: '45929'
requisite: Решение Мангистауского областного маслихата от 10 апреля 2009 года № 13/163. Зарегистрировано Департаментом юстиции Мангистауской области 14 мая 2009 года № 2046
title:
  rus: О поправочных коэффициентах к базовой ставке земельного налога и схема зонирования для целей налогообложения по городу Актау
  kaz: Ақтау қаласы бойынша жер салығының базалық ставкаларына түзету коэффициенттері мен салық салу мақсатында аймақтарға бөлу схемасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-10
approved_by:
- '163000000002'
version_date:
  kaz: 2009-04-10
  rus: 2009-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/45929/kaz/10.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45929/rus/10.04.2009
