act_code: '108611'
requisite: Решение Актауского городского маслихата Мангистауской области от 9 декабря 2016 года № 6/67. Зарегистрировано Департаментом юстиции Мангистауской области 29 декабря 2016 года № 3229
title:
  rus: О городском бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-09
approved_by:
- '163002000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/108611/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108611/rus/09.12.2016
