act_code: '46374'
requisite: Мұнайлы ауданы мәслихатының 2009 жылғы 8 мамырдағы № 15/159 шешімі. Мұнайлы ауданы Әділет басқармасында 2009 жылғы 9 маусымда № 11-7-43 тіркелді. Күші жойылды – Маңғыстау облысы Мұнайлы аудандық мәслихатының 2016 жылғы 11 шілдедегі № 3/38 шешімімен
title:
  rus: Басқұдық селолық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
  kaz: Басқұдық селолық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-08
approved_by:
- '163008000002'
version_date:
  kaz: 2014-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46374/kaz/24.11.2014
