act_code: '151885'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 8 января 2021 года № 58/475. Зарегистрировано Департаментом юстиции Мангистауской области 14 января 2021 года № 4427
title:
  rus: О районном бюджете на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '163007000002'
version_date:
  kaz: 2021-10-18
  rus: 2021-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/151885/kaz/18.10.2021
  rus: https://zan.gov.kz/client/#!/doc/151885/rus/18.10.2021
caused_by:
  code: '159665'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 18 октября 2021 года № 11/105. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 октября 2021 года № 24834
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 8 января 2021 года № 58/475 «О районном бюджете на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған аудандық бюджет туралы» Бейнеу аудандық мәслихатының 2021 жылғы 8 қаңтардағы № 58/475 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159665/rus
