act_code: '107454'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/51. Зарегистрировано Департаментом юстиции Мангистауской области от 11 ноября 2016 года № 3175. Утратило силу решением Манстауского районного маслихата Мангистауской области от 5 сентября 2022 года № 14/151
title:
  rus: Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе
  kaz: Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '163004000002'
version_date:
  kaz: 2018-02-28
  rus: 2018-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107454/kaz/28.02.2018
  rus: https://zan.gov.kz/client/#!/doc/107454/rus/28.02.2018
caused_by:
  code: '119772'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 28 февраля 2018 года № 14/160. Зарегистрировано Департаментом юстиции Мангистауской области 16 марта 2018 года № 3540. Утратило силу решением Манстауского районного маслихата Мангистауской области от 5 сентября 2022 года № 14/151
  title:
    rus: О внесении изменений в решение Мангистауского районного маслихата от 21 октября 2016 года №5/51 «Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2016 жылғы 21 қазандағы №5/51 «Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы» шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119772/rus
