act_code: '107454'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 21 октября 2016 года № 5/51. Зарегистрировано Департаментом юстиции Мангистауской области от 11 ноября 2016 года № 3175. Утратило силу решением Манстауского районного маслихата Мангистауской области от 5 сентября 2022 года № 14/151
title:
  rus: Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе
  kaz: Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-21
approved_by:
- '163004000002'
version_date:
  kaz: 2020-12-31
  rus: 2020-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/107454/kaz/31.12.2020
  rus: https://zan.gov.kz/client/#!/doc/107454/rus/31.12.2020
caused_by:
  code: '151661'
  requisite: Решение Мангистауского районного маслихата Мангистауской области от 31 декабря 2020 года № 43/478. Зарегистрировано Департаментом юстиции Мангистауской области 12 января 2021 года № 4418. Утратило силу решением Манстауского районного маслихата Мангистауской области от 5 сентября 2022 года № 14/151
  title:
    rus: О внесении изменения в решение Мангистауского районного маслихата от 21 октября 2016 года № 5/51 «Об утверждении размеров социальной помощи и перечня категорий нуждающихся граждан в Мангистауском районе»
    kaz: Маңғыстау аудандық мәслихатының 2016 жылғы 21 қазандағы № 5/51 «Маңғыстау ауданында әлеуметтік көмек мөлшерлерін және мұқтаж азаматтар санаттарының тізбесін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/151661/rus
