act_code: '138071'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 25 декабря 2019 года № 37/383. Зарегистрировано Департаментом юстиции Мангистауской области 8 января 2020 года № 4097
title:
  rus: О районном бюджете на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '163005000002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/138071/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138071/rus/27.11.2020
caused_by:
  code: '149533'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 27 ноября 2020 года № 45/449. Зарегистрировано Департаментом юстиции Мангистауской области 8 декабря 2020 года № 4360
  title:
    rus: О внесении изменений в решение Каракиянского районного маслихата от 25 декабря 2019 года № 37/383 «О районном бюджете на 2020 - 2022 годы»
    kaz: Қарақия аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 37/383 «2020 - 2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149533/rus
