act_code: '160532'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 3 ноября 2021 года № 11/65. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 ноября 2021 года № 25224
title:
  rus: Об утверждении Правил оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мунайлинского района
  kaz: Мұнайлы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-03
approved_by:
- '163008000002'
version_date:
  kaz: 2023-10-11
  rus: 2023-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/160532/kaz/11.10.2023
  rus: https://zan.gov.kz/client/#!/doc/160532/rus/11.10.2023
caused_by:
  code: '187395'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 11 октября 2023 года № 5/32. Зарегистрировано Департаментом юстиции Мангистауской области 20 октября 2023 года № 4616-12
  title:
    rus: О внесении изменение в решение Мунайлинского районного маслихата от 03 ноября 2021 года № 11/65 «Об утверждении Правил оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мунайлинского района»
    kaz: Мұнайлы аудандық мәслихатының 2021 жылғы 03 қарашадағы № 11/65 «Мұнайлы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187395/rus
