act_code: '53918'
requisite: Маңғыстау облысы Түпқараған ауданы Ақшұқыр селосының әкімінің 2010 жылғы 4 тамыздағы № 231 шешімі.Түпқараған ауданының Әділет басқармасында 2010 жылғы 9 тамызда № 11-6-123 тіркелді
title:
  rus: Ақшұқыр ауылы бойынша жаңадан пайда болған көшелерге атау беру туралы
  kaz: Ақшұқыр ауылы бойынша жаңадан пайда болған көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-04
approved_by:
- '163006003001'
version_date:
  kaz: 2010-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/53918/kaz/04.08.2010
