act_code: '41566'
requisite: 'ИМПОРТ: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2008 жылғы 4 қыркүйектегі № 10/71 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының әділет басқармасында 2008 жылғы 17 қыркүйекте № 11-2-89 болып тіркелді'
title:
  rus: 2008 жылға арналған қалалық бюджет туралы мәслихаттың 2007 жылғы 13 желтоқсандағы № 5/24 шешіміне өзгерістер
  kaz: 2008 жылға арналған қалалық бюджет туралы мәслихаттың 2007 жылғы 13 желтоқсандағы № 5/24 шешіміне өзгерістер
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-04
approved_by:
- '163003000002'
version_date:
  kaz: 2008-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/41566/kaz/04.09.2008
