act_code: '56435'
requisite: Решение Каракиянского районного маслихата от 21 декабря 2010 года № 32/228. Зарегистрировано Управлением юстиции Каракиянского района 27 декабря 2010 года № 11-4-112. Утратило силу решением маслихата Каракиянского  района Мангистауской области от 20 декабря 2013 года № 15/148
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '163005000002'
version_date:
  kaz: 2011-10-28
  rus: 2011-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56435/kaz/28.10.2011
  rus: https://zan.gov.kz/client/#!/doc/56435/rus/28.10.2011
caused_by:
  code: '61318'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 октября 2011 года № 40/286. Зарегистрировано Департаментом юстиции Мангистауской области 15 ноября 2011 года № 11-4-125. Утратило силу решением маслихата Каракиянского  района Мангистауской области от 20 декабря 2013 года № 15/148
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2010 года № 32/228 "О районном бюджете на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 21 желтоқсандағы № 32/228 "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61318/rus
