act_code: '50196'
requisite: Маңғыстау аудандық мәслихатының 2009 жылғы 11 желтоқсандағы № 19/198 шешімі. Маңғыстау ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда № 11-5-93 тіркелді. Күші жойылды - Маңғыстау аудандық мәслихатының 2013 жылғы 11 наурыздағы № 8/76 шешімімен.
title:
  rus: Базарларда тауар сатумен айналысатын тұлғалар үшін біржолғы талон ақысын белгілеу туралы
  kaz: Базарларда тауар сатумен айналысатын тұлғалар үшін біржолғы талон ақысын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '163004000002'
version_date:
  kaz: 2009-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/50196/kaz/11.12.2009
