act_code: '128859'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 23 января 2019 года № 28/229. Зарегистрировано Департаментом юстиции Мангистауской области 29 января 2019 года № 3805
title:
  rus: О бюджете города районного значения, сел, сельского округа на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163006000002'
version_date:
  kaz: 2019-06-12
  rus: 2019-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/128859/kaz/12.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128859/rus/12.06.2019
caused_by:
  code: '132601'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 12 июня 2019 года № 31/251. Зарегистрировано Департаментом юстиции Мангистауской области 19 июня 2019 года № 3933
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от  23 января 2019 года № 28/229 « О бюджете города районного значения, сел, сельского округа на 2019 - 2021 годы»
    kaz: Түпқараған аудандық мәслихатының 2019 жылғы 23 қаңтардағы № 28/229 «2019 - 2021 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132601/rus
