act_code: '124297'
requisite: Решение акима сельского округа Сайын Шапагатов Тупкараганского района Мангистауской области от 23 июля 2018 года № 229. Зарегистрировано Департаментом юстиции Мангистауской области 28 августа 2018 года № 3703
title:
  rus: О присвоении наименования безымянной улице сельского округа Сайын Шапагатов
  kaz: Сайын Шапағатов ауылдық округінің атаусыз көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-23
approved_by:
- '163006006002'
version_date:
  kaz: 2018-07-23
  rus: 2018-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/124297/kaz/23.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124297/rus/23.07.2018
