act_code: '111182'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 3 марта 2017 года № 9/101. Зарегистрировано Департаментом юстиции Мангистауской области 7 апреля 2017 года № 3323. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 19 октября 2023 года № 8/67
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Жанаозен
  kaz: Жаңаөзен қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-03
approved_by:
- '163003000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/111182/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/111182/rus/23.12.2019
caused_by:
  code: '137906'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 23 декабря 2019 года № 40/468. Зарегистрировано Департаментом юстиции Мангистауской области 6 января 2020 года № 4094. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 19 октября 2023 года № 8/67
  title:
    rus: О внесении изменения в решение Жанаозенского городского маслихата от 3 марта 2017 года № 9/101 «Об утверждении норм образования и накопления коммунальных отходов по городу Жанаозен»
    kaz: Жаңаөзен қалалық мәслихатының 2017 жылғы 3 наурыздағы № 9/101 «Жаңаөзен қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137906/rus
