act_code: '71832'
requisite: Решение Мангистауского областного маслихата от 27 февраля 2013 года № 9/123. Зарегистрировано Департаментом юстиции Мангистауской области 1 апреля 2013 года за № 2233
title:
  rus: Об утверждении перечня социально значимых убыточных маршрутов, подлежащих субсидированию в Мангистауской области на 2013 год
  kaz: Маңғыстау облысындағы субсидиялауға жататын 2013 жылға арналған әлеуметтік мәні бар залалды маршруттар тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2013-02-27
  rus: 2013-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/71832/kaz/27.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71832/rus/27.02.2013
