act_code: '26434'
requisite: Решение Мангистауского областного маслихата от 6 декабря 2005 года № 13/228. Зарегистрировано Департаментом юстиции Мангистауской области 22 декабря 2005 года № 1933. Утратило силу решением Мангистауского областного Маслихата от 30 мая 2007 года № 23/380
title:
  rus: О Среднесрочном плане социально-экономического развития Мангистауской области на 2006-2008 годы
  kaz: О Среднесрочном плане социально-экономического развития Мангистауской области на 2006-2008 годы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '163000000002'
version_date:
  rus: 2005-12-06
source:
  rus: https://zan.gov.kz/client/#!/doc/26434/rus/06.12.2005
