act_code: '3410'
requisite: Решение акима  Мангистауской области от 22 июня 1999 года № 156. Зарегистрировано Управлением юстиции Мангистауской области 5 июля 1999 года № 91. Утратило силу решением акима   Мангистауской области от 4 октября 2004 года № 58
title:
  rus: О реализации Постановления Правительства Республики Казахстан «О заимствовании исполнительным органом местным Мангистауской области» № 747 от 14 июня 1999
  kaz: «Маңғыстау облысы жергілікті атқарушы органының қарыз алу туралы» Қазақстан Республикасы Үкіметінің 1999 жылғы 14 маусымдағы № 747 Қаулысын іске асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-21
approved_by:
- '163000000003'
version_date:
  kaz: 1999-06-21
  rus: 1999-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/3410/kaz/21.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3410/rus/21.06.1999
