act_code: '195015'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 29 марта 2024 года № 10/77. Зарегистрировано Департаментом юстиции Мангистауской области 29 марта 2024 года № 4684-12
title:
  rus: О понижении размера ставки при применении специального налогового режима розничного налога по Мангистаускому району
  kaz: Маңғыстау ауданы бойынша бөлшек салықтың арнаулы салық режимін қолдану кезінде мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '163004000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195015/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195015/rus/29.03.2024
