act_code: '12709'
requisite: Решение маслихата Мангистауской области от 12 апреля 2002 года № 18/178. Зарегистрировано Управлением юстиции Мангистауской области 3 мая 2002 года № 894
title:
  rus: О Региональной программе реабилитации инвалидов Мангистауской области на 2002-2005 годы
  kaz: Маңғыстау облысы бойынша мүгедектердi оңалтудың 2002-2005 жылдарға арналған Аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-11
approved_by:
- '163000000002'
version_date:
  kaz: 2002-04-11
  rus: 2002-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/12709/kaz/11.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12709/rus/11.04.2002
