act_code: '43385'
requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2008 жылғы 12 желтоқсандағы № 13/77 шешімі. Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2008 жылғы 26 желтоқсанда № 11-6-77 тіркелді
title:
  rus: '"2009 жылға арналған аудандық бюджет" туралы'
  kaz: '"2009 жылға арналған аудандық бюджет" туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-12
approved_by:
- '163006000002'
version_date:
  kaz: 2009-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/43385/kaz/15.04.2009
caused_by:
  code: '45470'
  requisite: Маңғыстау облысы Түпқараған аудандық мәслихатының 2009 жылғы 15 сәуірдегі № 17/106 шешімі. Маңғыстау облысы Түпқараған ауданының Әділет басқармасында 2009 жылғы 28 сәуірдегі № 11-6-90 тіркелді
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 12 желтоқсандағы N 13/77 "209 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер еңгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 12 желтоқсандағы N 13/77 "209 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45470/rus
