act_code: '49331'
requisite: Маңғыстау облысы Бейнеу ауданы әкімдігі Тәжен селосы әкімдігінің 2009 жылғы 28 қазандағы № 3 шешімі. Бейнеу ауданының Әділет басқармасында 2009 жылғы 25 қарашада № 11-3-88 тіркелді
title:
  rus: Жаңа көшелерге ат қою туралы
  kaz: Жаңа көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-28
approved_by:
- '163007006001'
version_date:
  kaz: 2017-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/49331/kaz/09.02.2017
caused_by:
  code: '110337'
  requisite: Решение акима села Тажен Бейнеуского района Мангистауской области от 9 февраля 2017 года № 10. Зарегистрировано Департаментом юстиции Мангистауской области 10 марта 2017 года № 3286
  title:
    rus: О внесении изменений в решение акима села Тажен от 28 октября 2009 года №3 «Жаңа көшелерге ат қою туралы»
    kaz: Тәжен ауылы әкімінің 2009 жылғы 28 қазандағы №3 «Жаңа көшелерге ат қою туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/110337/rus
