act_code: '86075'
requisite: Решение Мангистауского районного маслихата от 24 декабря 2014 года № 22/187. Зарегистрировано Депараментом юстиции от 16 января 2015 года № 2593
title:
  rus: «О районном бюджете на 2015-2017 годы»
  kaz: «2015-2017 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '163004000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/86075/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/86075/rus/27.03.2015
caused_by:
  code: '88961'
  requisite: Решение маслихата Мангистауского района от 27 марта 2015 года № 24/201. Зарегистрировано Департаментом юстиции Мангистауской области от 14 апреля 2015 года № 2676
  title:
    rus: О  внесении   изменений  и дополнений в решение Мангистауского районного маслихата от 24 декабря 2014 года №22/187   «О районном бюджете на 2015-2017 годы»
    kaz: Маңғыстау аудандық мәслихатының 2014 жылғы 24 желтоқсандағы №22/187 «2015 - 2017 жылдарға  арналған  аудандық  бюджет  туралы»  шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88961/rus
