act_code: '86075'
requisite: Решение Мангистауского районного маслихата от 24 декабря 2014 года № 22/187. Зарегистрировано Депараментом юстиции от 16 января 2015 года № 2593
title:
  rus: «О районном бюджете на 2015-2017 годы»
  kaz: «2015-2017 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '163004000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86075/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86075/rus/24.12.2014
