act_code: '228873'
requisite: Решение акима сельского округа Баскудык Мунайлинского района Мангистауской области от 11 августа 2026 года № 155-Ш
title:
  rus: О присвоении наименований улицам сельского округа Баскудык
  kaz: Басқұдық ауылдық округінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-11
approved_by:
- '163008003001'
version_date:
  kaz: 2026-08-11
  rus: 2026-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/228873/kaz/11.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228873/rus/11.08.2026
