act_code: '59624'
requisite: Постановление акимата Тупкараганского района акима села Сайын Шапагатов Мангистауской области от 30 июня 2011 года № 43. Зарегистрировано Управлением юстиции Тупкараганского района Департамента юстиции Мангистауской области 18 июля 2011 года № 11-6-136
title:
  rus: О присвоении наименования улице по сельскому округу Сайын Шапагатов
  kaz: Сайын Шапағатов ауылдық округі бойынша көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-30
approved_by:
- '163006006002'
version_date:
  kaz: 2018-04-17
  rus: 2018-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/59624/kaz/17.04.2018
  rus: https://zan.gov.kz/client/#!/doc/59624/rus/17.04.2018
caused_by:
  code: '121511'
  requisite: Решение акима сельского округа Сайын Шапагатов Тупкараганского района Мангистауской области от 17 апреля 2018 года № 117. Зарегистрировано Департаментом юстиции Мангистауской области 5 мая 2018 года № 3595
  title:
    rus: О внесении изменений в решение акима села Сайын Шапагатов от 30 июня 2011 года № 43 «О наименовании улицы по селу Сайын Шапагатова»
    kaz: Сайын Шапағатов ауылы әкімінің 2011 жылғы 30 маусымдағы № 43 «Сайын Шапағатов селосы бойынша көшеге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121511/rus
