act_code: '40204'
requisite: Решение маслихата Мангистауской области от 16 мая 2008 года № 5/73. Зарегистрировано Департаментом юстиции Мангистауской области 18 июня 2008 года № 2017. Утратило силу решением Мангистауского областного маслихата от 10 августа 2012 года № 5/68
title:
  rus: О Правилах застройки территории Мангистауской области
  kaz: Маңғыстау облысы аумағында құрылыс салу Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-16
approved_by:
- '163000000002'
version_date:
  kaz: 2008-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/40204/kaz/16.05.2008
