act_code: '40204'
requisite: Решение маслихата Мангистауской области от 16 мая 2008 года № 5/73. Зарегистрировано Департаментом юстиции Мангистауской области 18 июня 2008 года № 2017. Утратило силу решением Мангистауского областного маслихата от 10 августа 2012 года № 5/68
title:
  rus: О Правилах застройки территории Мангистауской области
  kaz: Маңғыстау облысы аумағында құрылыс салу Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-16
approved_by:
- '163000000002'
version_date:
  kaz: 2008-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/40204/kaz/10.12.2008
caused_by:
  code: '43612'
  requisite: Решение Мангистауского областного маслихата от 10 декабря 2008 года № 10/127. Зарегистрировано Департаментом юстиции Мангистауской области 12 января 2009 года № 2037. Утратило силу решением Мангистауского областного маслихата от 10 августа 2012 года № 5/68
  title:
    rus: О внесении изменений в решение областного маслихата от 16 мая 2008 года № 5/73 "О правилах застройки территории Мангистауской области"
    kaz: '"Маңғыстау облысы аумағында құрылыс салу Қағидасы туралы" облыстық мәслихаттың 2008 жылғы 16 мамырдағы № 5/73 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/43612/rus
