act_code: '38713'
requisite: Решение Маслихата Мангистауской области от 12 февраля 2008 года № 4/63. Зарегистрировано Департаментом юстиции Мангистауской области 13 марта 2008 года № 2003. Утратило силу решением Мангистауского областного маслихата от 13 декабря 2010 года № 29/355
title:
  rus: О поправочных коэффициентах к базовой ставке земельного налога и схемы зонирования для целей налогообложения территории города Жанаозен
  kaz: Салық салу мақсатында Жаңаөзен қаласы аумағын аймақтарға бөлу схемасы және жер салығының базалық ставкаларына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-12
approved_by:
- '163000000002'
version_date:
  kaz: 2008-02-12
  rus: 2008-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/38713/kaz/12.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38713/rus/12.02.2008
