act_code: '59416'
requisite: Решение маслихата Мунайлинского района от 3 июня 2011 года. Зарегистрировано Департаментом юстиции Мангистауской области 28 июня 2011 года № 11-7-93. Утратила силу решением маслихата Мунайлинского района Мангистауской области от 6 мая 2014 года № 21/244.
title:
  rus: О размере и порядке оказания жилищной помощи малообеспеченным семьям (гражданам)
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-03
approved_by:
- '163008000002'
version_date:
  kaz: 2012-09-13
  rus: 2012-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/59416/kaz/13.09.2012
  rus: https://zan.gov.kz/client/#!/doc/59416/rus/13.09.2012
