act_code: '22578'
requisite: Решение акима Мангистауской области от 30 декабря 2004 года № 70. Зарегистрировано Департаментом юстиции Мангистауской области 19  января 2005 года № 1833. Утратило силу по истечению срока действия - письмом руководителя аппарата акима  Мангистауской области от 25 июня 2008 года № 08-12-985
title:
  rus: О проведении приписки граждан 1988 года рождения к призывным участкам в городских отделах и управлений по делам обороны Мангистауской области
  kaz: Маңғыстау облысының қалалық және аудандық әскери комиссариаттарының әскерге шақыру участкелерiне 1987 жылы туылған азаматтарды тiркеуді жүргiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-30
approved_by:
- '163000000003'
version_date:
  kaz: 2004-12-30
  rus: 2004-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/22578/kaz/30.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22578/rus/30.12.2004
