act_code: '58857'
requisite: Решение акима Бейнеуского района от 26 апреля 2011 года № 3. Зарегистрировано Департаментом юстиции Мангистауской области 18 мая 2011 года № 11-3-119. Утратило силу решением акима Бейнеуского  района Мангистауской области от 15 мая 2017 года № 1
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-26
approved_by:
- '163007000001'
version_date:
  rus: 2014-04-23
source:
  rus: https://zan.gov.kz/client/#!/doc/58857/rus/23.04.2014
caused_by:
  code: '91639'
  requisite: Решение акима Бейнеуского района от 19 июня 2015 года № 2. Зарегистрировано Депараментом юстиции Мангистауской области от 15 июля 2015 года № 2763. Утратило силу решением акима Бейнеуского  района Мангистауской области от 15 мая 2017 года № 1
  title:
    rus: О  внесении  изменений  в  некоторые  решения  акима Бейнеуского  района
    kaz: Бейнеу  ауданы  әкімінің  кейбір  шешімдеріне  өзгерістер  енгізу  туралы
  link: https://zan.gov.kz/client/#!/doc/91639/rus
