act_code: '47609'
requisite: Маңғыстау облысы Қарақия аудандық мәслихатының 2009 жылғы 17 шілдедегі № 18/144 шешімі. Қарақия ауданының әділет басқармасында 2009 жылғы 21 тамызда № 11-4-91 тіркелді. Күші жойылды - Қарақия ауданы мәслихатының 2012 жылғы 2 ақпандағы № 1/13 шешімімен.
title:
  rus: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну мөлшерін және ережесін бекіту туралы
  kaz: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну мөлшерін және ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-17
approved_by:
- '163005000002'
version_date:
  kaz: 2009-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/47609/kaz/17.07.2009
