act_code: '44703'
requisite: Қарақия аудандық мәслихатының 2009 жылғы 6 ақпандағы N 13/110 шешімі. Қарақия ауданының Әділет басқармасында 2009 жылғы 27 ақпанда N 11-4-73 тіркелді
title:
  rus: Жетібай және Мұнайшы ауылдары бойынша жер учаскелері құнының базалық мөлшерлемесіне түзету коэффициенттері бағалық аймақтарға бөлу жобасы (схемасы) туралы
  kaz: Жетібай және Мұнайшы ауылдары бойынша жер учаскелері құнының базалық мөлшерлемесіне түзету коэффициенттері бағалық аймақтарға бөлу жобасы (схемасы) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '163005000002'
version_date:
  kaz: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44703/kaz/28.10.2015
caused_by:
  code: '96228'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 28 октября 2015 года № 29/298. Зарегистрировано Департаментом юстиции Мангистауской области от 9 декабря 2015 года № 2905
  title:
    rus: О внесении изменений в некоторые решения маслихата Каракиянского района
    kaz: Қарақия аудандық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96228/rus
