act_code: '65742'
requisite: Решение маслихата города Актау Мангистауской области от 24 апреля 2012 года № 3/36. Зарегистрировано Департаментом юстиции Мангистауской области 29 мая 2012 года № 11-1-178. Утратило силу решением Актауского городского маслихата Мангистауской области от 12 декабря 2013 года № 16/154
title:
  rus: Об оказании единовременной социальной помощи
  kaz: Біржолғы әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-24
approved_by:
- '163002000002'
version_date:
  kaz: 2013-02-28
  rus: 2013-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/65742/kaz/28.02.2013
  rus: https://zan.gov.kz/client/#!/doc/65742/rus/28.02.2013
