act_code: '391'
requisite: Решение акима  Мангистауской области от 19 августа 1997 года № 487. Зарегистрировано Управлением юстиции Мангистауской области 3 апреля 1998 года № 3. Утратило силу решением акима  Мангистауской области от 4 марта  1999 года № 6
title:
  rus: О региональной программе развития языках
  kaz: Тілдерді дамытудың аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-08-18
approved_by:
- '163000000003'
version_date:
  kaz: 1997-08-18
  rus: 1997-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/391/kaz/18.08.1997
  rus: https://zan.gov.kz/client/#!/doc/391/rus/18.08.1997
