act_code: '85636'
requisite: Решение Актауского городского маслихата от 23 декабря 2014 года № 26/249. Зарегестрировано Департаментом юстиции Мангистауской области от 30 декабря 2014 года № 2568
title:
  rus: О городском бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '163002000002'
version_date:
  kaz: 2015-10-28
  rus: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/85636/kaz/28.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85636/rus/28.10.2015
caused_by:
  code: '95190'
  requisite: Решение Актауского городского маслихата Мангистауской области от 28 октября 2015 года № 34/318. Зарегистрировано Департаментом юстиции Мангистауской области от 04 ноября 2015 года № 2856
  title:
    rus: О внесении изменений в решение городского маслихата от 3 декабря 2014 года №26/249«О городском бюджете на 2015-2017 годы»
    kaz: Қалалық мәслихаттың 2014 жылғы  23 желтоқсандағы №26/249 «2015-2017 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95190/rus
