act_code: '76675'
requisite: Решение от 12.12.2013 №16/153, Маслихат города Актау   Утратило силу решением Актауского городского маслихата Мангистауской области от 03.07.2015 № 30/283
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по городу Актау
  kaz: Ақтау қаласы бойынша әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-12
approved_by:
- '163002000002'
version_date:
  kaz: 2013-12-12
  rus: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/76675/kaz/12.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76675/rus/12.12.2013
