act_code: '640'
requisite: Решение акима Мангистауской области от 6 мая 1998 года № 145. Зарегистрировано Управлением юстиции Мангистауской области  26 мая 1998 года № 10
title:
  rus: «О дополнительных мерах по укреплению общественного порядка на территории Мангистауской области»
  kaz: Маңғыстау облысы аумағында қоғамдық тәртіпті нығайту жөніндегі қосымша шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-05
approved_by:
- '163000000003'
version_date:
  kaz: 1998-05-05
  rus: 1998-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/640/kaz/05.05.1998
  rus: https://zan.gov.kz/client/#!/doc/640/rus/05.05.1998
