act_code: '128770'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 января 2019 года № 31/257. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2019 года № 3795
title:
  rus: О бюджете села Акжигит на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Ақжігіт ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163007000002'
version_date:
  kaz: 2019-01-23
  rus: 2019-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/128770/kaz/23.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128770/rus/23.01.2019
