act_code: '128770'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 января 2019 года № 31/257. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2019 года № 3795
title:
  rus: О бюджете села Акжигит на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Ақжігіт ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163007000002'
version_date:
  kaz: 2019-11-19
  rus: 2019-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/128770/kaz/19.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128770/rus/19.11.2019
caused_by:
  code: '136196'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 19 ноября 2019 года № 42/330. Зарегистрировано Департаментом юстиции Мангистауской области 21 ноября 2019 года № 4030
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 23 января 2019 года № 31/257 «О бюджете села Акжигит на 2019 – 2021 годы»
    kaz: Бейнеу аудандық мәслихатының 2019 жылғы 23 қаңтардағы № 31/257 «2019 - 2021 жылдарға арналған Ақжігіт ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136196/rus
