act_code: '128770'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 23 января 2019 года № 31/257. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2019 года № 3795
title:
  rus: О бюджете села Акжигит на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Ақжігіт ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-23
approved_by:
- '163007000002'
version_date:
  kaz: 2019-05-20
  rus: 2019-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/128770/kaz/20.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128770/rus/20.05.2019
caused_by:
  code: '131901'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 20 мая 2019 года № 36/294. Зарегистрировано Департаментом юстиции Мангистауской области 22 мая 2019 года № 3898
  title:
    rus: О внесении изменений в решение Бейнеуского районного маслихата от 23 января 2019 года № 31/257 «О бюджете села Акжигит на 2019 – 2021 годы»
    kaz: Бейнеу аудандық мәслихатының 2019 жылғы 23 қаңтардағы № 31/257 «2019 - 2021 жылдарға арналған Ақжігіт ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131901/rus
