act_code: '3769'
requisite: Решение акима  Мангистауской области от 20 июля 1999 года № 186. Зарегистрировано Управлением юстиции Мангистауской области 11 августа 1999 года № 125. Утратило силу заключением начальника департамента  юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: О государственных закупках работ и услуг
  kaz: Жұмыстар мен қызметтерді мемлекеттік сатып алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-07-19
approved_by:
- '163000000003'
version_date:
  kaz: 1999-07-19
  rus: 1999-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/3769/kaz/19.07.1999
  rus: https://zan.gov.kz/client/#!/doc/3769/rus/19.07.1999
