act_code: '217167'
requisite: Решение акима села Онды Мангистауского района Мангистауской области от 10 ноября 2025 года № 01-05/27
title:
  rus: О названии улиц
  kaz: Онды ауылында көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-10
approved_by:
- '163004010001'
version_date:
  kaz: 2025-11-10
  rus: 2025-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/217167/kaz/10.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217167/rus/10.11.2025
