act_code: '3767'
requisite: Решение акима  Мангистауской области от 24 июня 1999 года № 164. Зарегистрировано Управлением юстиции Мангистауской области 11 августа 1999 года № 123
title:
  rus: О реализации Постановления Правительства Республики Казахстан от 11 мая 1999 года № 561 "Об оказании помощи районам с депрессивной экономикой"
  kaz: Қазақстан Республикасы Үкiметiнiң 1999 жылғы мамырдың 11-iндегi № 561 "Экономикасы тоқыраған аудандарға көмек көрсету туралы" Қаулысын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-23
approved_by:
- '163000000003'
version_date:
  kaz: 1999-06-23
  rus: 1999-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/3767/kaz/23.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3767/rus/23.06.1999
