act_code: '23999'
requisite: Маңғыстау облысы Жаңаөзен қаласы әкімінің 2005 жылғы 1 тамыздағы № 292 шешімі. Маңғыстау облысы Әділет департаменті Жаңаөзен қаласының Әділет басқармасында 2005 жылғы 11 тамызда № 11-2-7 болып тіркелді
title:
  rus: Әскер қатарына дейінгі жасөспірімдерді дәрігерлік байқаудан өткізу туралы
  kaz: Әскер қатарына дейінгі жасөспірімдерді дәрігерлік байқаудан өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-08-01
approved_by:
- '163003000003'
version_date:
  kaz: 2005-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/23999/kaz/01.08.2005
