act_code: '18735'
requisite: Решение Мангистауского областного маслихата от 10 декабря 2003г за № 2/18. Зарегистрировано Департаментом юстиции Мангистауской области 5 января 2004 года № 1582
title:
  rus: Об Индикативном плане социально-экономического развития Мангистауской области на 2004-2006 годы
  kaz: Маңғыстау облысының әлеуметтік-экономикалың дамуының 2004-2006 жылдарға арналған Индикативтік жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-10
approved_by:
- '163000000002'
version_date:
  kaz: 2003-12-10
  rus: 2003-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/18735/kaz/10.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18735/rus/10.12.2003
