act_code: '57053'
requisite: Решение маслихата Бейнеуского района от 13 декабря 2010 года № 34/202. Зарегистрировано Управлением юстиции Бейнеуского района 29 декабря 2010 года № 11-3-106
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '163007000002'
version_date:
  kaz: 2011-12-08
  rus: 2011-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/57053/kaz/08.12.2011
  rus: https://zan.gov.kz/client/#!/doc/57053/rus/08.12.2011
caused_by:
  code: '61941'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 8 декабря 2011 года № 49/283. Зарегистрировано Департаментом юстиции Мангистауской области 15 декабря 2011 года № 11-3-127
  title:
    rus: О внесении изменений в решение районного маслихата от 13 декабря 2010 года № 34/202 "О районном бюджете на 2011 - 2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 13 желтоқсандағы № 34/202 "2011 - 2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61941/rus
