act_code: '46824'
requisite: Бейнеу аудандық мәслихатының 2008 жылғы 13 желтоқсандағы № 12/78 шешімі. Бейнеу ауданының әділет басқармасында 2008 жылғы 19 желтоқсанда № 11-3-66 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-13
approved_by:
- '163007000002'
version_date:
  kaz: 2008-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/46824/kaz/13.12.2008
