act_code: '171703'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 13 сентября 2022 года № 16/98. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 сентября 2022 года № 29595
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Тупкараганскому району
  kaz: Түпқараған ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-13
approved_by:
- '163006000002'
version_date:
  kaz: 2022-09-13
  rus: 2022-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/171703/kaz/13.09.2022
  rus: https://zan.gov.kz/client/#!/doc/171703/rus/13.09.2022
