act_code: '54777'
requisite: Маңғыстау облысы Мұнайлы ауданы Дәулет селолық округінің әкімінің 2010 жылғы 28 қыркүйектегі № 43 шешімі. Маңғыстау облысының Әділет департаменті Мұнайлы ауданының Әділет басқармасында 2010 жылғы 6 қазанда № 11-7-80 тіркелді
title:
  rus: Көшеге атау беру туралы
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-28
approved_by:
- '163008004001'
version_date:
  kaz: 2014-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/54777/kaz/10.11.2014
