act_code: '46020'
requisite: Решение Мангистауского областного маслихата от 10 апреля 2009 года № 13/162. Зарегистрировано Департаментом юстиции Мангистауской области 14 мая 2009 года № 2047
title:
  rus: О границах зон города Актау и поправочный коэффициентах к базовой ставке платы за земельные участки
  kaz: Ақтау қаласы аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкасына түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-10
approved_by:
- '163000000002'
version_date:
  kaz: 2009-04-10
  rus: 2009-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/46020/kaz/10.04.2009
  rus: https://zan.gov.kz/client/#!/doc/46020/rus/10.04.2009
