act_code: '111495'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 17 марта 2017 года № 10/88. Зарегистрировано Департаментом юстиции Мангистауской области 21 апреля 2017 года № 3336
title:
  rus: Об утверждении проекта (схемы) зонирования земель, поправочных коэффициентов к базовым ставкам платы за земельные участки и земельного налога по городу Форт-Шевченко
  kaz: Форт-Шевченко қаласы бойынша жерді аймақтарға бөлу жобасын (схемасын), жер учаскелері үшін төлемақының және жер салығының базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-17
approved_by:
- '163006000002'
version_date:
  kaz: 2018-05-18
  rus: 2018-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/111495/kaz/18.05.2018
  rus: https://zan.gov.kz/client/#!/doc/111495/rus/18.05.2018
caused_by:
  code: '122376'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 18 мая 2018 года № 20/175. Зарегистрировано Департаментом юстиции Мангистауской области 12 июня 2018 года № 3641
  title:
    rus: О внесении изменения в решение Тупкараганского районного маслихата от 17 марта 2017 года № 10/88 «Об утверждении проекта (схемы) зонирования земель, поправочных коэффициентов к базовым ставкам платы за земельные участки и земельного налога по городу Форт-Шевченко»
    kaz: Түпқараған аудандық мәслихатының 2017 жылғы 17 наурыздағы № 10/88 «Форт-Шевченко қаласы бойынша жерді аймақтарға бөлу жобасын (схемасын), жер учаскелері үшін төлемақының және жер салығының базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122376/rus
