act_code: '36770'
requisite: Маңғыстау облысы Түпқараған ауданы мәслихатының 2007 жылғы 14 желтоқсандағы № 4/20 шешімі. Маңғыстау облысы Әділет департаменті Маңғыстау ауданының әділет басқармасында 2008 жылғы 1 қаңтарда  № 11-6-47 болып тіркелді
title:
  rus: «2008 жылға арналған аудандық бюджет» туралы
  kaz: «2008 жылға арналған аудандық бюджет» туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-14
approved_by:
- '163006000002'
version_date:
  kaz: 2007-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/36770/kaz/14.12.2007
