act_code: '95607'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 29 октября 2015 года № 34/235. Зарегистрировано Департаментом юстиции Мангистауской области от 20 ноября 2015 года № 2874. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 26 июня 2020 года № 45/336
title:
  rus: О повышении ставок земельного налога на не используемые земли сельскохозяйственного назначения в Тупкараганском  районе
  kaz: Түпқараған ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге  жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-29
approved_by:
- '163006000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/95607/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/95607/rus/29.03.2018
caused_by:
  code: '120810'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 29 марта 2018 года № 18/157. Зарегистрировано Департаментом юстиции Мангистауской области 13 апреля 2018 года № 3569. Утратило силу решением Тупкараганского районного маслихата Мангистауской области от 26 июня 2020 года № 45/336
  title:
    rus: О внесении изменения в решение Тупкараганского районного маслихата от 29 октября 2015 года № 34/235 «О повышении ставок земельного налога на не используемые земли сельскохозяйственного назначения в Тупкараганском районе»
    kaz: Түпқараған аудандық мәслихатының 2015 жылғы 29 қазандағы № 34/235 «Түпқараған ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы  жерлерге жер салығының мөлшерлемелерін жоғарылату туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120810/rus
