act_code: '42376'
requisite: Маңғыстау облысы Мұнайлы ауданы әкімдігі Баянды селосы әкімінің 2008 жылғы 13 маусымдағы № 24 шешімі. Маңғыстау облысы Мұнайлы ауданының Әділет басқармасында 2008 жылғы 30 маусымда № 11-7-7 болып тіркелді
title:
  rus: Баянды ауылының әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы
  kaz: Баянды ауылының әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-13
approved_by:
- '163008005001'
version_date:
  kaz: 2017-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/42376/kaz/27.01.2017
caused_by:
  code: '109912'
  requisite: Решение акима села Баянды Мунайлинского района Мангистауской области от 27 января 2017 года № 27. Зарегистрировано Департаментом юстиции Мангистауской области 23 февраля 2017 года № 3274
  title:
    rus: О внесении изменений в некоторые решения акима села Баянды
    kaz: Баянды ауылы әкімінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109912/rus
