act_code: '206062'
requisite: Решение Каракиянского районного маслихата Мангистауской области от 6 января 2025 года № 24/205
title:
  rus: «О бюджетах сел, сельских округов на 2025 - 2027 годы»
  kaz: «2025 - 2027 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-06
approved_by:
- '163005000002'
version_date:
  kaz: 2025-10-06
  rus: 2025-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/206062/kaz/06.10.2025
  rus: https://zan.gov.kz/client/#!/doc/206062/rus/06.10.2025
caused_by:
  code: '215486'
  requisite: Решение Каракиянского районного маслихата Мангистауской области от 6 октября 2025 года № 30/253
  title:
    rus: О внесении изменения в решение  Каракиянского районного маслихата от 06 января 2025 года № 24/205 «О бюджете сел, сельских округов на 2025 - 2027 годы»
    kaz: Қарақия аудандық мәслихатының 2025 жылғы 06 қаңтардағы № 24/205 «2025 - 2027 жылдарға арналған ауылдардың, ауылдық округтердің бюджеттері туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215486/rus
