act_code: '41658'
requisite: Маңғыстау облысы Түпқараған ауданы мәслихатының 2008 жылғы 15 тамыздағы № 8/53 шешімі. Маңғыстау облысы Әділет департаменті Түпқараған ауданының әділет басқармасында 2008 жылғы 19 қыркүйекте № 11-6-67 болып тіркелді
title:
  rus: Жергілікті маңызы бар жалпыға ортақ пайдаланатын автомобиль жолдарының белгіленген белдеуінде және елді мекендерде орналастырылатын жарнама объектілері бойынша бір айға төленетін төлем мөлшерін белгілеу туралы
  kaz: Жергілікті маңызы бар жалпыға ортақ пайдаланатын автомобиль жолдарының белгіленген белдеуінде және елді мекендерде орналастырылатын жарнама объектілері бойынша бір айға төленетін төлем мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-15
approved_by:
- '163006000002'
version_date:
  kaz: 2008-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/41658/kaz/15.08.2008
