act_code: '227453'
requisite: Решение Мангистауского областного маслихата от 29 июня 2026 года № 28/335
title:
  rus: Об утверждении программы реновации жилищного фонда по Мангистауской области
  kaz: Маңғыстау облысы бойынша тұрғын үй қорын жаңғырту бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-29
approved_by:
- '163000000002'
version_date:
  kaz: 2026-06-29
  rus: 2026-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/227453/kaz/29.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227453/rus/29.06.2026
