act_code: '82962'
requisite: Решение маслихата Мангистауской области от 30 июля 2014 года № 18/276. Зарегистрировано Департаментом юстиции Мангистауской области 4 августа 2014 года № 2489. Утратило силу решением маслихата Мангистауской области от 28 августа 2020 года № 37/446
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-30
approved_by:
- '163000000002'
version_date:
  kaz: 2014-07-30
  rus: 2014-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/82962/kaz/30.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82962/rus/30.07.2014
