act_code: '82962'
requisite: Решение маслихата Мангистауской области от 30 июля 2014 года № 18/276. Зарегистрировано Департаментом юстиции Мангистауской области 4 августа 2014 года № 2489. Утратило силу решением маслихата Мангистауской области от 28 августа 2020 года № 37/446
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-30
approved_by:
- '163000000002'
version_date:
  kaz: 2019-12-10
  rus: 2019-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/82962/kaz/10.12.2019
  rus: https://zan.gov.kz/client/#!/doc/82962/rus/10.12.2019
caused_by:
  code: '137096'
  requisite: Решение Мангистауского областного маслихата от 10 декабря 2019 года № 32/388. Зарегистрировано Департаментом юстиции Мангистауской области 18 декабря 2019 года № 4056. Утратило силу решением маслихата Мангистауской области от 28 августа 2020 года № 37/446
  title:
    rus: О внесении изменений и дополнений в решение Мангистауского областного маслихата от 30 июля 2014 года № 18/276 «О дополнительном бесплатном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении»
    kaz: Маңғыстау облыстық мәслихатының 2014 жылғы 30 шілдедегі № 18/276 «Амбулаториялық емдеу барысында азаматтардың жекелеген санаттарына дәрі-дәрмектерді қосымша тегін ұсыну туралы»  шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137096/rus
