act_code: '42378'
requisite: Маңғыстау облысы Мұнайлы ауданы Қызылтөбе селолық округі әкімінің 2008 жылғы 13 маусымдағы № 238-а шешімі. Маңғыстау облысы Мұнайлы аудынының Әділет басқармасында 2008 жылғы 30 маусымда № 11-7-9 болып тіркелді
title:
  rus: Қызылтөбе ауылдық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы
  kaz: Қызылтөбе ауылдық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-13
approved_by:
- '163008001000'
version_date:
  kaz: 2017-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/42378/kaz/25.01.2017
caused_by:
  code: '110005'
  requisite: Решение акима сельского округа Кызылтобе Мунайлинского района Мангистауской области от 25 января 2017 года № 12. Зарегистрировано Департаментом юстиции Мангистауской области 24 февраля 2017 года № 3276
  title:
    rus: О внесении изменений в решение акима сельского округа Кызылтобе от 13 июня 2008 года №238-а «Қызылтөбе селолық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы»
    kaz: Қызылтөбе ауылдық округі әкімінің 2008 жылғы 13 маусымдағы №238-а «Қызылтөбе селолық округінің әкімшілік-аумақтық құрылысына қарасты құрамдас бөліктеріне атаулар беру туралы»  шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/110005/rus
