act_code: '79947'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 11 апреля 2014 года № 20/223. Зарегистрировано Департаментом юстиции Мангистауской области 13 мая 2014 года № 2414. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 23 октября 2023 года № 6/39
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в Мунайлинском районе
  kaz: Мұнайлы ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-11
approved_by:
- '163008000002'
version_date:
  kaz: 2022-09-22
  rus: 2022-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/79947/kaz/22.09.2022
  rus: https://zan.gov.kz/client/#!/doc/79947/rus/22.09.2022
caused_by:
  code: '172211'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 22 сентября 2022 года № 22/138. Утратило силу решением Мунайлинского районного маслихата Мангистауской области от 23 октября 2023 года № 6/39
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 11 апреля 2014 года № 20/223 «Об утверждении Правил проведения раздельных сходов местного сообщества в Мунайлинском районе»
    kaz: Мұнайлы аудандық мәслихатының 2014 жылғы 11 сәуірдегі № 20/223 «Мұнайлы ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172211/rus
