act_code: '57733'
requisite: Решение акима Мунайлинского района от 22 февраля 2011 года № 19-ш. Зарегистрировано Департаментом юстиции Мангистауской области 9 марта 2011 года № 11-7-90
title:
  rus: О мерах по организации приписки граждан к призывному участку отдела по делам обороны Мунайлинского района
  kaz: Мұнайлы ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне азаматтарды тіркеуді ұйымдастыру жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-22
approved_by:
- '163008000003'
version_date:
  kaz: 2011-02-22
  rus: 2011-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/57733/kaz/22.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57733/rus/22.02.2011
