act_code: '221280'
requisite: Решение акима села Мангистау Мунайлинского района Мангистауской области от 12 января 2026 года № 6
title:
  rus: О присвоении наименования улице села Мангистау
  kaz: Маңғыстау ауылындағы көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-12
approved_by:
- '163008007001'
version_date:
  kaz: 2026-01-12
  rus: 2026-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/221280/kaz/12.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221280/rus/12.01.2026
