act_code: '192001'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 28 декабря 2023 года № 12/101
title:
  rus: О бюджете села Рахат на 2024 - 2026 годы
  kaz: 2024 - 2026 жылдарға арналған Рахат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '163003000002'
version_date:
  kaz: 2024-10-21
  rus: 2024-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/192001/kaz/21.10.2024
  rus: https://zan.gov.kz/client/#!/doc/192001/rus/21.10.2024
caused_by:
  code: '202079'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 21 октября 2024 года № 21/168
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 28 декабря 2023 года № 12/101 «О бюджете села Рахат на 2024 - 2026 годы
    kaz: Жаңаөзен қалалық мәслихатының 2023 жылғы 28 желтоқсандағы № 12/101 «2024 - 2026 жылдарға арналған Рахат ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202079/rus
