act_code: '3928'
requisite: Решение акима  Мангистауской области от 17 августа 1999 года № 199. Зарегистрировано Управлением юстиции Мангистауской области 25 августа 1999 года № 129
title:
  rus: О социальной защите ветеранов Великой Отечественной войны, инвалидов Чернобыльской АЭС и одиноких инвалидов, нуждающихся в постороннем уходе.
  kaz: Ұлы Отан соғысының ардагерлерiн, Чернобыль АЭС-ғы апаттың мүгедектерiн және сырттай көмекке мұқтаж жалғызiлiктi мүгедектердi әлеуметтiк қорғау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-08-16
approved_by:
- '163000000003'
version_date:
  kaz: 1999-08-16
  rus: 1999-08-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/3928/kaz/16.08.1999
  rus: https://zan.gov.kz/client/#!/doc/3928/rus/16.08.1999
