act_code: '102661'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 19 апреля 2016 года №2/18. Зарегистрировано Департаментом юстиции Мангистауской области от 27 мая 2016 года № 3047. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 30 июня 2020 года № 51/413
title:
  rus: О  дополнительном  регламентировании  порядка    проведения  мирных  собраний,  митингов,  шествий,  пикетов  и  демонстраций
  kaz: Бейбіт  жиналыстар,  митингілер,  шерулер,  пикеттер  және  демонстрацияларды    өткізу  тәртібін  қосымша  реттеу  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-19
approved_by:
- '163007000002'
version_date:
  kaz: 2017-05-15
  rus: 2017-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/102661/kaz/15.05.2017
  rus: https://zan.gov.kz/client/#!/doc/102661/rus/15.05.2017
caused_by:
  code: '112958'
  requisite: Решение Бейнеуского районного маслихата Мангистауской области от 15 мая 2017 года № 13/107. Зарегистрировано Департаментом юстиции Мангистауской области 21 июня 2017 года № 3381. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 30 июня 2020 года № 51/413
  title:
    rus: О внесении изменения в решение Бейнеуского районного маслихата от 19 апреля 2016 года № 2/18 «О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий,  пикетов и демонстраций»
    kaz: Бейнеу аудандық мәслихатының 2016 жылғы 19 сәуірдегі № 2/18 «Бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрацияларды өткізу тәртібін қосымша реттеу туралы» шешіміне  өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112958/rus
