act_code: '102661'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 19 апреля 2016 года №2/18. Зарегистрировано Департаментом юстиции Мангистауской области от 27 мая 2016 года № 3047. Утратило силу решением Бейнеуского районного маслихата Мангистауской области от 30 июня 2020 года № 51/413
title:
  rus: О  дополнительном  регламентировании  порядка    проведения  мирных  собраний,  митингов,  шествий,  пикетов  и  демонстраций
  kaz: Бейбіт  жиналыстар,  митингілер,  шерулер,  пикеттер  және  демонстрацияларды    өткізу  тәртібін  қосымша  реттеу  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-19
approved_by:
- '163007000002'
version_date:
  kaz: 2016-04-19
  rus: 2016-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/102661/kaz/19.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102661/rus/19.04.2016
