act_code: '17070'
requisite: Решение Мангистауского областного маслихата от 12 сентября 2003 года № 28/308. Зарегистрировано в областном управлении юстиции Мангистауской области 23 сентября 2003 года № 1519
title:
  rus: О Программе развития туристской отрасли в Мангистауской области на 2003-2005 годы
  kaz: Маңғыстау облысында туристік саланы дамытудың 2003-2005 жылдарға арналған бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-11
approved_by:
- '163000000002'
version_date:
  kaz: 2003-09-11
  rus: 2003-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/17070/kaz/11.09.2003
  rus: https://zan.gov.kz/client/#!/doc/17070/rus/11.09.2003
