act_code: '180839'
requisite: Решение Актауского городского маслихата Мангистауской области от 2 мая 2023 года № 2/8. Зарегистрировано Департаментом юстиции Мангистауской области 5 мая 2023 года № 4557-12. Утратило силу решением Актауского городского маслихата Мангистауской области от 6 декабря 2023 года № 8/45
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по городу Актау
  kaz: Ақтау қаласы бойынша 2023 жылға арналған шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-02
approved_by:
- '163002000002'
version_date:
  kaz: 2023-05-02
  rus: 2023-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/180839/kaz/02.05.2023
  rus: https://zan.gov.kz/client/#!/doc/180839/rus/02.05.2023
