act_code: '89461'
requisite: Решение маслихата Мунайлинского района от 20 марта 2015 года № 30/309. Зарегистрировано Департаментом юстиции Мангистауской области от 30 апреля 2015 года № 2706
title:
  rus: О границах ценового зонирования и поправочных коэффициентов к базовым ставкам платы за земельные участки по сельскому округу Кызылтобе
  kaz: Қызылтөбе ауылдық округі бойынша бағалық аймақтарға бөлу шекаралары және жер учаскелері үшін төлемақының базалық мөлшерлемесіне түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-20
approved_by:
- '163008000002'
version_date:
  rus: 2015-10-28
source:
  rus: https://zan.gov.kz/client/#!/doc/89461/rus/28.10.2015
