act_code: '182445'
requisite: Решение Мангистауского районного маслихата Мангистауской области от 24 мая 2023 года № 3/19. Зарегистрировано Департаментом юстиции Мангистауской области 2 июня 2023 года № 4577-12. Утратило силу решением Мангистауского районного маслихата Мангистауской области от 13 декабря 2023 года № 7/50
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по Мангистаускому району
  kaz: Маңғыстау ауданы бойынша 2023 жылға арналған шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-24
approved_by:
- '163004000002'
version_date:
  kaz: 2023-05-24
  rus: 2023-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/182445/kaz/24.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182445/rus/24.05.2023
