act_code: '150419'
requisite: Решение Мангистауского областного маслихата от 11 декабря 2020 года № 39/462. Зарегистрировано Департаментом юстиции Мангистауской области 24 декабря 2020 года № 4399
title:
  rus: Об областном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-11
approved_by:
- '163000000002'
version_date:
  kaz: 2021-08-12
  rus: 2021-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/150419/kaz/12.08.2021
  rus: https://zan.gov.kz/client/#!/doc/150419/rus/12.08.2021
caused_by:
  code: '157950'
  requisite: Решение Мангистауского областного маслихата от 12 августа 2021 года № 4/58. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 августа 2021 года № 24013
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 11 декабря 2020 года № 39/462 «Об областном бюджете на 2021-2023 годы»
    kaz: Маңғыстау облыстық мәслихатының 2020 жылғы 11 желтоқсандағы № 39/462 «2021-2023 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157950/rus
