act_code: '163250'
requisite: Решение Актауского городского маслихата Мангистауской области от 30 декабря 2021 года № 10/86
title:
  rus: О бюджете села Умирзак на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Өмірзақ ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '163002000002'
version_date:
  kaz: 2022-12-13
  rus: 2022-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/163250/kaz/13.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163250/rus/13.12.2022
caused_by:
  code: '175274'
  requisite: Решение Актауского городского маслихата Мангистауской области от 13 декабря 2022 года № 21/165
  title:
    rus: О внесении изменений в решение Актауского городского маслихата Мангистауской области от 30 декабря 2021 года № 10/86 «О бюджете села Умирзак на 2022-2024 годы»
    kaz: Маңғыстау облысы Ақтау қалалық мәслихатының 2021 жылғы 30 желтоқсандағы № 10/86 «2022-2024 жылдарға арналған Өмірзақ ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175274/rus
