act_code: '52521'
requisite: Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2010 жылғы 8 сәуірдегі № 28/190 шешімі. Маңғыстау облысы Әділет департаментінде Жаңаөзен қаласының Әділет басқармасында 2010 жылғы 7 мамырда № 11-2-137 тіркелді. Күші жойылды - Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2012 жылғы 25 шілдедегі № 7/68 шешімімен
title:
  rus: Жаңаөзен қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы
  kaz: Жаңаөзен қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-08
approved_by:
- '163003000002'
version_date:
  kaz: 2010-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/52521/kaz/24.11.2010
caused_by:
  code: '55853'
  requisite: Маңғыстау облысы  Жаңаөзен қалалық мәслихатының 2010 жылғы 24 қарашадағы № 32/242 шешімі. Маңғыстау облысы Әділет департаментінде Жаңаөзен қаласының Әділет басқармасында 2010 жылғы 8 желтоқсанда № 11-2-147 тіркелді. Күші жойылды - Маңғыстау облысы Жаңаөзен қалалық мәслихатының 2012 жылғы 25 шілдедегі № 7/68 шешімімен
  title:
    rus: '"Жаңаөзен қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы" Жаңаөзен қалалық Мәслихатының 2010 жылғы 8 сәуірдегі № 28/190 шешіміне өзгерістер енгізу туралы'
    kaz: '"Жаңаөзен қаласындағы білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қалалық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүруді белгілеу және төлеуінің нұсқаулығын бекіту туралы" Жаңаөзен қалалық Мәслихатының 2010 жылғы 8 сәуірдегі № 28/190 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55853/rus
