act_code: '155338'
requisite: Решение Жанаозенского городского маслихата Мангистауской области от 16 апреля 2021 года № 3/27. Зарегистрировано Департаментом юстиции Мангистауской области 27 апреля 2021 года № 4502. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 28 марта 2024 года № 14/111
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-16
approved_by:
- '163003000002'
version_date:
  kaz: 2022-05-05
  rus: 2022-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/155338/kaz/05.05.2022
  rus: https://zan.gov.kz/client/#!/doc/155338/rus/05.05.2022
caused_by:
  code: '167654'
  requisite: Решение Жанаозенского городского маслихата Мангистауской области от 5 мая 2022 года № 18/147. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28035. Утратило силу решением Жанаозенского городского маслихата Мангистауской области от 28 марта 2024 года № 14/111
  title:
    rus: О внесении изменений в решение Жанаозенского городского маслихата от 16 апреля 2021 года № 3/27 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Жаңаөзен қалалық мәслихатының 2021 жылғы 16 сәуірдегі № 3/27 «Әлеуметтік көмек көрсетудің, оның мөлшерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167654/rus
