act_code: '201950'
requisite: Решение Бейнеуского районного маслихата Мангистауской области от 22 октября 2024 года № 21/166
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Бейнеускому району на 2024 - 2028 годы
  kaz: Бейнеу ауданы бойынша 2024 - 2028 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-22
approved_by:
- '163007000002'
version_date:
  kaz: 2024-10-22
  rus: 2024-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/201950/kaz/22.10.2024
  rus: https://zan.gov.kz/client/#!/doc/201950/rus/22.10.2024
