act_code: '215398'
requisite: Решение Актауского городского маслихата Мангистауской области от 6 октября 2025 года № 24/158
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по городу Актау
  kaz: Ақтау қаласы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-06
approved_by:
- '163002000002'
version_date:
  kaz: 2025-10-06
  rus: 2025-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/215398/kaz/06.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215398/rus/06.10.2025
