act_code: '128554'
requisite: Решение акима Мунайлинского района Мангистауской области от 15 января 2019 года № 1. Зарегистрировано Департаментом юстиции Мангистауской области 17 января 2019 года № 3777
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-15
approved_by:
- '163008000003'
version_date:
  kaz: 2024-07-18
  rus: 2024-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/128554/kaz/18.07.2024
  rus: https://zan.gov.kz/client/#!/doc/128554/rus/18.07.2024
caused_by:
  code: '198902'
  requisite: Решение акима Мунайлинского района Мангистауской области от 18 июля 2024 года № 6-ш. Зарегистрировано Департаментом юстиции Мангистауской области 19 июля 2024 года № 4721-12
  title:
    rus: О внесении изменений и дополнения в решение акима Мунайлинского района от 15 января 2019 года № 1 «Об образовании избирательных участков»
    kaz: Мұнайлы ауданы әкімінің 2019 жылғы 15 қаңтардағы № 1 «Сайлау учаскелерін құру туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198902/rus
