act_code: '32254'
requisite: Маңғыстау облысы Ақтау қаласы Өмірзақ ауылы әкімінің 2007 жылғы 2 наурыздағы № 18 шешімі. Ақтау қаласы  Әділет басқармасында 2007 жылғы 7 наурызда № 11-1-54 болып тіркелді
title:
  rus: Өмірзақ ауылы көшелерінің аттарын қайта қою туралы
  kaz: Өмірзақ ауылы көшелерінің аттарын қайта қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-03-02
approved_by:
- '163002001001'
version_date:
  kaz: 2017-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/32254/kaz/28.06.2017
caused_by:
  code: '113929'
  requisite: Решение акима села Умирзак города Актау Мангистауской области от 28 июня 2017 года № 51. Зарегистрировано Департаментом юстиции Мангистауской области 1 августа 2017 года № 3394
  title:
    rus: О внесении изменений в решение акима села Умирзак от 2 марта 2007 года № 18 "Өмірзақ ауылы көшелерінің аттарын қайта қою туралы"
    kaz: Өмірзақ ауылы әкімінің 2007 жылғы 2 наурыздағы № 18 "Өмірзақ ауылы көшелерінің аттарын қайта қою туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/113929/rus
