act_code: '70113'
requisite: Решение Мангистауского областного маслихата от 07 декабря 2012 года № 7/80. Зарегистрировано Департаментом юстиции Мангистауской области 18 января 2013 года № 2200
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2013 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша қоршаған ортаға эмиссиялар үшін 2013 жылға арналған төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-07
approved_by:
- '163000000002'
version_date:
  kaz: 2012-12-07
  rus: 2012-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/70113/kaz/07.12.2012
  rus: https://zan.gov.kz/client/#!/doc/70113/rus/07.12.2012
