act_code: '78604'
requisite: Решение маслихата Мангистауской области от 27 февраля 2014 года № 15/227. Зарегистрировано Департаментом юстиции Мангистауской области 9 апреля 2014 года № 2384
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников на 2014 год по Мангистауской области
  kaz: Маңғыстау облысы бойынша жер үстi көздерiндегі су ресурстарын пайдаланғаны үшін 2014 жылға арналған төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2014-02-27
  rus: 2014-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78604/kaz/27.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78604/rus/27.02.2014
