act_code: '203810'
requisite: Решение акима села Курык Каракиянского района Мангистауской области от 18 октября 2024 года № 222.
title:
  rus: Об установлений публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-18
approved_by:
- '163005006002'
version_date:
  kaz: 2024-10-18
  rus: 2024-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/203810/kaz/18.10.2024
  rus: https://zan.gov.kz/client/#!/doc/203810/rus/18.10.2024
