act_code: '196103'
requisite: Решение Актауского городского маслихата Мангистауской области от 19 апреля 2024 года № 12/77. Зарегистрировано Департаментом юстиции Мангистауской области 25 апреля 2024 года № 4703-12. Утратило силу решением Актауского городского маслихата Мангистауской области от 6 декабря 2024 года № 17/107.
title:
  rus: Об установлении размера дополнительной социальной помощи отдельным категориям граждан города Актау к 35 – летию вывода ограниченного контингента советских войск из Демократической Республики Афганистан
  kaz: Ауғанстан Демократиялық Республикасынан Кеңес әскерлерінің шектеулі контингентін шығаруының 35 - жылдығына Ақтау қаласы азаматтарының жекелеген санаттарына қосымша әлеуметтік көмектің мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-19
approved_by:
- '163002000002'
version_date:
  kaz: 2024-04-19
  rus: 2024-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/196103/kaz/19.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196103/rus/19.04.2024
