act_code: '190118'
requisite: Решение акима села Жетыбай Каракиянского района Мангистауской области от 11 декабря 2023 года № 83
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-11
approved_by:
- '163005005001'
version_date:
  kaz: 2023-12-11
  rus: 2023-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/190118/kaz/11.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190118/rus/11.12.2023
