act_code: '46194'
requisite: Мұнайлы ауданы мәслихатының 2009 жылғы 8 мамырдағы № 15/168 шешімі. Мұнайлы ауданы Әділет басқармасында 2009 жылғы 27 мамырда № 11-7-41 тіркелді. Күші жойылды – Маңғыстау облысы Мұнайлы аудандық мәслихатының 2016 жылғы 11 шілдедегі № 3/38 шешімімен
title:
  rus: Бильярд ойындары жиынтық салық ставкаларын бекіту туралы
  kaz: Бильярд ойындары жиынтық салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-08
approved_by:
- '163008000002'
version_date:
  kaz: 2009-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/46194/kaz/08.05.2009
