act_code: '2557'
requisite: Решение акима Мангистауской области от 15 марта 1999 года № 20. Зарегистрировано Управлением юстиции Мангистауской области  25 марта  1999 года № 42. Утратило силу заключением начальника управление юстиции Мангистауской области от 2 декабря 2003 года
title:
  rus: Об усилении ответственности должностных лиц в области защиты населения, окружающей среды и объектов хозяйствования от чрезвычайных ситуаций в области
  kaz: Маңғыстау облсысындағы төтенше жағдайлардан жене солардың кесірінен болған зардаптан халықты, қоршаған ортаны және шаруашылық объектілерін қорғау саласындағы лауазымды қызметкерлердің жауапкершілігін күшейту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-15
approved_by:
- '163000000003'
version_date:
  kaz: 1999-03-15
  rus: 1999-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/2557/kaz/15.03.1999
  rus: https://zan.gov.kz/client/#!/doc/2557/rus/15.03.1999
