act_code: '88354'
requisite: Решение акимата Мангистауской области от 27 февраля 2015 года № 22/350. Зарегистрировано Департаментом юстиции Мангистауской области от 03 апреля 2015 года № 2659
title:
  rus: О дополнительном бесплатном предоставлении лекарственных средств при амбулаторном лечении участникам Великой Отечественной войны, лицам с инвалидностью и лицам, приравненным к ним
  kaz: Ұлы Отан соғысының қатысушыларына, мүгедектігі бар адамдарға және соларға теңестірілген тұлғаларға амбулаториялық емделу кезінде дәрілік заттарды қосымша тегін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-27
approved_by:
- '163000000002'
version_date:
  kaz: 2022-12-09
  rus: 2022-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/88354/kaz/09.12.2022
  rus: https://zan.gov.kz/client/#!/doc/88354/rus/09.12.2022
caused_by:
  code: '175522'
  requisite: Решение Мангистауского областного маслихата от 9 декабря 2022 года № 16/180. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 декабря 2022 года № 31117
  title:
    rus: О внесении изменений в решение Мангистауского областного маслихата от 27 февраля 2015 года № 22/350 «О дополнительном бесплатном предоставлении лекарственных средств инвалидам и участникам Великой Отечественной войны и лицам, приравненным к ним при амбулаторном лечении»
    kaz: Маңғыстау облыстық мәслихатының 2015 жылғы 27 ақпандағы № 22/350 «Ұлы Отан соғысының қатысушылары мен мүгедектеріне және соларға теңестірілген тұлғаларға амбулаториялық емделу кезінде дәрілік заттарды қосымша тегін беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175522/rus
