act_code: '166785'
requisite: Решение Мунайлинского районного маслихата Мангистауской области от 8 апреля 2022 года № 18/110. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 апреля 2022 года № 27640
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Мунайлинском районе
  kaz: Мұнайлы ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-08
approved_by:
- '163008000002'
version_date:
  kaz: 2022-09-07
  rus: 2022-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/166785/kaz/07.09.2022
  rus: https://zan.gov.kz/client/#!/doc/166785/rus/07.09.2022
caused_by:
  code: '172209'
  requisite: Решение Мунайлинского районного маслихата Мангистауской области от 7 сентября 2022 года № 21/127. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 сентября 2022 года № 29871
  title:
    rus: О внесении изменений в решение Мунайлинского районного маслихата от 8 апреля 2022 года № 18/110 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Мунайлинском районе»
    kaz: Мұнайлы аудандық мәслихатының 2022 жылғы 8 сәуірдегі № 18/110 «Мұнайлы ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172209/rus
