act_code: '118456'
requisite: Решение Тупкараганского районного маслихата Мангистауской области от 30 декабря 2017 года № 16/133. Зарегистрировано Департаментом юстиции Мангистауской области 23 января 2018 года № 3519
title:
  rus: О бюджете города районного значения, сел, сельского округа на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-30
approved_by:
- '163006000002'
version_date:
  kaz: 2018-12-21
  rus: 2018-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/118456/kaz/21.12.2018
  rus: https://zan.gov.kz/client/#!/doc/118456/rus/21.12.2018
caused_by:
  code: '127438'
  requisite: Решение Тупкараганского районного маслихата Мангистауской области от 21 декабря 2018 года № 26/215. Зарегистрировано Департаментом юстиции Мангистауской области 25 декабря 2018 года № 3755
  title:
    rus: О внесении изменений в решение Тупкараганского районного маслихата от 30 декабря 2017 года № 16/133 «О бюджете города районного значения, сел, сельского округа на 2018-2020 годы»
    kaz: Түпқараған аудандық мәслихатының 2017 жылғы 30 желтоқсандағы № 16/133 «2018 - 2020 жылдарға арналған аудандық маңызы бар қаланың, ауылдардың, ауылдық округтің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127438/rus
