act_code: '50192'
requisite: Мұнайлы аудандық мәслихатының 2009 жылғы 12 желтоқсандағы № 21/225 шешімі. Мұнайлы ауданының Әділет басқармасында 2010 жылғы 11 қаңтарда № 11-7-65 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-12
approved_by:
- '163008000002'
version_date:
  kaz: 2010-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/50192/kaz/02.04.2010
caused_by:
  code: '51942'
  requisite: Маңғыстау облысы Мұнайлы аудандық мәслихатының 2010 жылғы 2 сәуірдегі № 24/251 шешімі. Мұнайлы ауданының Әділет басқармасында 2010 жылғы 19 сәуірде № 11-7-73 тіркелді
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 12 желтоқсандағы № 21/225 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 12 желтоқсандағы № 21/225 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51942/rus
