act_code: '30395'
requisite: Решение Маслихата Мангистауской области от 14 октября 2006 года № 17/313. Зарегистрировано Департаментом юстиции Мангистауской области 17 ноября 2006 года № 1958. Утратило силу решением Мангистауского областного маслихата от 6 декабря 2011 года № 39/453
title:
  rus: О Правилах содержания и защиты зеленых насаждений в Мангистауской области
  kaz: Маңғыстау облысының жасыл желекті екпелерін күтіп ұстау және қорғау Ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-10-14
approved_by:
- '163000000002'
version_date:
  kaz: 2006-10-14
  rus: 2006-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/30395/kaz/14.10.2006
  rus: https://zan.gov.kz/client/#!/doc/30395/rus/14.10.2006
